#!/usr/bin/env python
import os

def translate_file(src_path, dst_path, translations):
    with open(src_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for eng, chn in translations.items():
        content = content.replace(eng, chn)

    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Translated: {src_path} -> {dst_path}')

# LangChain translation
langchainTranslations = {
    'Trace LangChain applications (Python and JS/TS)': '追踪 LangChain 应用程序（Python 和 JS/TS）',
    'LangChain': 'LangChain',
    'LangSmith integrates seamlessly with LangChain (Python and JavaScript), the popular open-source framework for building LLM applications.': 'LangSmith 与 LangChain（用于构建大型语言模型应用程序的流行开源框架）无缝集成。',
    '## Installation': '## 安装',
    'Install the following for Python or JS (the code snippets use the OpenAI integration).': '安装以下适用于 Python 或 JS 的包（代码片段使用 OpenAI 集成）。',
    'For a full list of packages available, see the [LangChain docs](/oss/integrations/providers/overview).': '有关可用包的完整列表，请参阅 [LangChain 文档](/oss/integrations/providers/overview)。',
    '## Quick start': '## 快速入门',
    '### 1. Configure your environment': '### 1. 配置您的环境',
    'This example uses OpenAI, but you can use any LLM provider of choice': '此示例使用 OpenAI，但您可以使用任何您选择的大型语言模型提供商',
    'For LangSmith API keys linked to multiple workspaces, set the LANGSMITH_WORKSPACE_ID environment variable to specify which workspace to use.': '对于链接到多个工作区的 LangSmith API 密钥，请设置 LANGSMITH_WORKSPACE_ID 环境变量以指定要使用哪个工作区。',
    'If you are using LangChain.js with LangSmith and are not in a serverless environment, we also recommend setting the following explicitly to reduce latency:': '如果您在非无服务器环境中将 LangChain.js 与 LangSmith 一起使用，我们还建议明确设置以下内容以减少延迟：',
    'If you are in a serverless environment, we recommend setting the reverse to allow tracing to finish before your function ends:': '如果您在无服务器环境中，我们建议设置相反的值以允许追踪在函数结束前完成：',
    '### 2. Log a trace': '### 2. 记录追踪',
    'No extra code is needed to log a trace to LangSmith. Just run your LangChain code as you normally would.': '无需额外代码即可向 LangSmith 记录追踪。只需像往常一样运行您的 LangChain 代码。',
    '### 3. View your trace': '### 3. 查看您的追踪',
    'By default, the trace will be logged to the project with the name `default`. You can view an example of a trace logged using the above code [publicly in LangSmith](https://smith.langchain.com/public/e6a46eb2-d785-4804-a1e3-23f167a04300/r).': '默认情况下，追踪将记录到名为 `default` 的项目中。您可以[在 LangSmith 中公开查看](https://smith.langchain.com/public/e6a46eb2-d785-4804-a1e3-23f167a04300/r)使用上述代码记录的追踪示例。',
    '## Trace selectively': '## 选择性追踪',
    'The [previous section](#quick-start) showed how to trace all invocations of a LangChain runnables within your applications by setting a single environment variable. While this is a convenient way to get started, you may want to trace only specific invocations or parts of your application.': '[上一节](#quick-start)介绍了如何通过设置单个环境变量来追踪应用程序中所有 LangChain runnable 的调用。虽然这是开始的便捷方式，但您可能只想追踪特定的调用或应用程序的特定部分。',
    'There are two ways to do this in Python: by manually passing in a `LangChainTracer` instance as a [callback](https://reference.langchain.com/python/langchain_core/callbacks/), or by using the [`tracing_context` context manager](https://reference.langchain.com/python/langsmith/observability/sdk/run_helpers/#langsmith.run_helpers.tracing_context).': '在 Python 中有两种方法：手动传入一个 `LangChainTracer` 实例作为[回调](https://reference.langchain.com/python/langchain_core/callbacks/)，或使用 [`tracing_context` 上下文管理器](https://reference.langchain.com/python/langsmith/observability/sdk/run_helpers/#langsmith.run_helpers.tracing_context)。',
    'In JS/TS, you can pass a [`LangChainTracer`](https://reference.langchain.com/javascript/classes/_langchain_core.tracers_tracer_langchain.LangChainTracer.html) instance as a callback.': '在 JS/TS 中，您可以传递一个 [`LangChainTracer`](https://reference.langchain.com/javascript/classes/_langchain_core.tracers_tracer_langchain.LangChainTracer.html) 实例作为回调。',
    '# You can opt-in to specific invocations..': '# 您可以选择加入特定调用...',
    '# This will NOT be traced (assuming LANGSMITH_TRACING is not set)': '# 这不会被追踪（假设未设置 LANGSMITH_TRACING）',
    '# This would not be traced, even if LANGSMITH_TRACING=true': '# 即便 LANGSMITH_TRACING=true，这也不会被追踪',
    '// You can configure a LangChainTracer instance to trace a specific invocation.': '// 您可以配置 LangChainTracer 实例来追踪特定调用。',
    '## Log to a specific project': '## 记录到特定项目',
    '### Statically': '### 静态设置',
    'As mentioned in the [tracing conceptual guide](/langsmith/observability-concepts) LangSmith uses the concept of a Project to group traces. If left unspecified, the tracer project is set to default. You can set the `LANGSMITH_PROJECT` environment variable to configure a custom project name for an entire application run. This should be done before executing your application.': '如[追踪概念指南](/langsmith/observability-concepts)中所述，LangSmith 使用项目概念对追踪进行分组。如果未指定，追踪器项目设置为 default。您可以设置 `LANGSMITH_PROJECT` 环境变量来为整个应用程序运行配置自定义项目名称。这应在执行应用程序之前完成。',
    'The `LANGSMITH_PROJECT` flag is only supported in JS SDK versions >= 0.2.16, use `LANGCHAIN_PROJECT` instead if you are using an older version.': '`LANGSMITH_PROJECT` 标志仅在 JS SDK 版本 >= 0.2.16 中支持，如果您使用的是旧版本，请改用 `LANGCHAIN_PROJECT`。',
    '### Dynamically': '### 动态设置',
    'This largely builds off of the [previous section](#trace-selectively) and allows you to set the project name for a specific `LangChainTracer` instance or as parameters to the `tracing_context` context manager in Python.': '这主要基于[上一节](#trace-selectively)构建，允许您为特定 `LangChainTracer` 实例或作为 Python 中 `tracing_context` 上下文管理器的参数设置项目名称。',
    '# You can set the project name using the project_name parameter.': '# 您可以使用 project_name 参数设置项目名称。',
    '// You can set the project name for a specific tracer instance:': '// 您可以为特定追踪器实例设置项目名称：',
    '## Add metadata and tags to traces': '## 向追踪添加元数据和标签',
    'You can annotate your traces with arbitrary metadata and tags by providing them in the [`RunnableConfig`](https://reference.langchain.com/python/langchain_core/runnables/?h=runnablecon#langchain_core.runnables.RunnableConfig). This is useful for associating additional information with a trace, such as the environment in which it was executed, or the user who initiated it. For information on how to query traces and runs by metadata and tags, see [Query traces (SDK)](/langsmith/export-traces)': '您可以通过在 [`RunnableConfig`](https://reference.langchain.com/python/langchain_core/runnables/?h=runnablecon#langchain_core.runnables.RunnableConfig) 中提供任意元数据和标签来为追踪添加注释。这对于将附加信息与追踪关联很有用，例如执行它的环境或启动它的用户。有关如何按元数据和标签查询追踪和运行的信息，请参阅[查询追踪（SDK）](/langsmith/export-traces)',
    'When you attach metadata or tags to a runnable (either through the @[`RunnableConfig`] or at runtime with invocation params), they are inherited by all child runnables of that runnable.': '当您将元数据或标签附加到 runnable（无论是通过 @[`RunnableConfig`] 还是在运行时通过调用参数）时，它们会被该 runnable 的所有子 runnable 继承。',
    '# The tag "model-tag" and metadata {"model-key": "model-value"} will be attached to the ChatOpenAI run only': '# 标签 "model-tag" 和元数据 {"model-key": "model-value"} 将仅附加到 ChatOpenAI 运行',
    '# Tags and metadata can be configured with RunnableConfig': '# 标签和元数据可以通过 RunnableConfig 配置',
    '# Tags and metadata can also be passed at runtime': '# 标签和元数据也可以在运行时传递',
    '// The tag "model-tag" and metadata {"model-key": "model-value"} will be attached to the ChatOpenAI run only': '// 标签 "model-tag" 和元数据 {"model-key": "model-value"} 将仅附加到 ChatOpenAI 运行',
    '// Tags and metadata can be configured with RunnableConfig': '// 标签和元数据可以通过 RunnableConfig 配置',
    '// Tags and metadata can also be passed at runtime': '// 标签和元数据也可以在运行时传递',
    '## Customize run name': '## 自定义运行名称',
    'You can customize the name of a given run when invoking or streaming your LangChain code by providing it in the [Config](https://reference.langchain.com/python/langchain_core/runnables/?h=runnablecon#langchain_core.runnables.RunnableConfig). This name is used to identify the run in LangSmith and can be used to filter and group runs. The name is also used as the title of the run in the LangSmith UI. This can be done by setting a `run_name` in the @[`RunnableConfig`] object at construction or by passing a `run_name` in the invocation parameters in JS/TS.': '您可以通过在[配置](https://reference.langchain.com/python/langchain_core/runnables/?h=runnablecon#langchain_core.runnables.RunnableConfig)中提供它来在调用或流式传输 LangChain 代码时自定义给定运行的名称。此名称用于在 LangSmith 中标识运行，并可用于过滤和分组运行。该名称也用作 LangSmith UI 中运行的标题。这可以通过在构造时在 @[`RunnableConfig`] 对象中设置 `run_name` 或在 JS/TS 中调用参数中传递 `run_name` 来完成。',
    '# When tracing within LangChain, run names default to the class name of the traced object (e.g., \'ChatOpenAI\').': '# 在 LangChain 中追踪时，运行名称默认为被追踪对象的类名（例如 \'ChatOpenAI\'）。',
    '# You can also configure the run name at invocation time, like below': '# 您也可以在调用时配置运行名称，如下所示',
    '// When tracing within LangChain, run names default to the class name of the traced object (e.g., \'ChatOpenAI\').': '// 在 LangChain 中追踪时，运行名称默认为被追踪对象的类名（例如 \'ChatOpenAI\'）。',
    '// You can also configure the run name at invocation time, like below': '// 您也可以在调用时配置运行名称，如下所示',
    'The `run_name` parameter only changes the name of the runnable you invoke (e.g., a chain, function). It does not rename the nested run automatically created when you invoke an LLM object like @[`ChatOpenAI`] (`gpt-5.4-mini`). In the example, the enclosing run will appear in LangSmith as `MyCustomChain`, while the nested LLM run still shows the model\'s default name.': '`run_name` 参数仅更改您调用的 runnable 的名称（例如链、函数）。它不会重命名在调用大型语言模型对象（如 @[`ChatOpenAI`]（`gpt-5.4-mini`））时自动创建的嵌套运行。在示例中，封闭运行将显示在 LangSmith 中为 `MyCustomChain`，而嵌套的大型语言模型运行仍显示模型的默认名称。',
    'To give the LLM run a more meaningful name, you can either:': '要为大型语言模型运行提供更有意义的名称，您可以：',
    'Wrap the model in another runnable and assign a `run_name` to that step.': '将模型包装在另一个 runnable 中并为该步骤分配一个 `run_name`。',
    'Use a tracing decorator or helper (e.g., `@traceable` in Python, or `traceable` from `langsmith` in JS/TS) to create a custom run around the model call.': '使用追踪装饰器或辅助函数（例如 Python 中的 `@traceable` 或 JS/TS 中来自 `langsmith` 的 `traceable`）围绕模型调用创建一个自定义运行。',
    '## Override model name in traces': '## 在追踪中覆盖模型名称',
    'When tracing LangChain model calls, LangSmith automatically captures the model identifier used in the API call. However, you may want to display a different, more descriptive name in traces for organizational purposes or to distinguish between different model configurations. You can do this by passing the `ls_model_name` [metadata parameter](/langsmith/ls-metadata-parameters#ls_model_name) when constructing or configuring your LangChain model.': '在追踪 LangChain 模型调用时，LangSmith 会自动捕获 API 调用中使用的模型标识符。但是，您可能希望在追踪中显示不同的、更具描述性的名称，以用于组织目的或区分不同的模型配置。您可以通过在构建或配置 LangChain 模型时传递 `ls_model_name` [元数据参数](/langsmith/ls-metadata-parameters#ls_model_name) 来实现此目的。',
    'This is particularly useful when:': '这在以下情况下特别有用：',
    'Working with self-hosted or local models where the model ID might not be descriptive.': '使用自托管或本地模型时，模型 ID 可能不具有描述性。',
    'Using the same model with different configurations and wanting to distinguish them in traces.': '使用具有不同配置的相同模型并希望在追踪中区分它们。',
    'Creating aliases for models to make traces more readable for your team.': '为模型创建别名，使追踪对您的团队更易读。',
    'Standardizing model names across different deployment environments.': '跨不同部署环境标准化模型名称。',
    '# Override model name for a local model': '# 覆盖本地模型的模型名称',
    '# Actual model ID': '# 实际模型 ID',
    '# Name shown in LangSmith': '# 在 LangSmith 中显示的名称',
    '# Or with OpenAI to distinguish configurations': '# 或使用 OpenAI 区分配置',
    '# The metadata is inherited when the model is used in a chain': '# 当模型在链中使用时，元数据被继承',
    '// Override model name for a local model': '// 覆盖本地模型的模型名称',
    '// Actual model ID': '// 实际模型 ID',
    '// Name shown in LangSmith': '// 在 LangSmith 中显示的名称',
    '// Or with OpenAI to distinguish configurations': '// 或使用 OpenAI 区分配置',
    '// The metadata is inherited when the model is used in a chain': '// 当模型在链中使用时，元数据被继承',
    'When you pass `ls_model_name` in the model\'s metadata, this name will appear in the LangSmith UI for all traces involving that model instance. This works for any LangChain chat model or LLM and is inherited by all runs that use the model, including when it\'s part of a chain.': '当您在模型的元数据中传递 `ls_model_name` 时，此名称将出现在涉及该模型实例的所有追踪的 LangSmith UI 中。这适用于任何 LangChain 聊天模型或大型语言模型，并被所有使用该模型的运行继承，包括当它是链的一部分时。',
    'The `ls_model_name` metadata parameter is also used for [cost tracking](/langsmith/cost-tracking). When combined with the `ls_provider` parameter, LangSmith can automatically calculate costs for custom or self-hosted models. For more information about all available metadata parameters, see the [metadata parameters reference](/langsmith/ls-metadata-parameters).': '`ls_model_name` 元数据参数也用于[成本追踪](/langsmith/cost-tracking)。当与 `ls_provider` 参数结合使用时，LangSmith 可以自动计算自定义或自托管模型的成本。有关所有可用元数据参数的更多信息，请参阅[元数据参数参考](/langsmith/ls-metadata-parameters)。',
    '## Customize run ID': '## 自定义运行 ID',
    'You can customize the ID of a given run when invoking or streaming your LangChain code by providing it in the [Config](https://reference.langchain.com/python/langchain_core/runnables/?h=runnablecon#langchain_core.runnables.RunnableConfig). This ID is used to uniquely identify the run in LangSmith and can be used to query specific runs. The ID can be useful for linking runs across different systems or for implementing custom tracking logic. This can be done by setting a `run_id` in the @[`RunnableConfig`] object at construction or by passing a `run_id` in the invocation parameters.': '您可以通过在[配置](https://reference.langchain.com/python/langchain_core/runnables/?h=runnablecon#langchain_core.runnables.RunnableConfig)中提供它来在调用或流式传输 LangChain 代码时自定义给定运行的 ID。此 ID 用于在 LangSmith 中唯一标识运行，并可用于查询特定运行。ID 可用于跨不同系统链接运行或实现自定义追踪逻辑。这可以通过在构造时在 @[`RunnableConfig`] 对象中设置 `run_id` 或在调用参数中传递 `run_id` 来完成。',
    'This feature is not currently supported directly for LLM objects.': '此功能目前不直接支持大型语言模型对象。',
    '# You can configure the run ID at invocation time:': '# 您可以在调用时配置运行 ID：',
    '// You can configure the run ID at invocation time, like below': '// 您可以在调用时配置运行 ID，如下所示',
    'Note that if you do this at the **root** of a trace (i.e., the top-level run, that run ID will be used as the `trace_id`).': '请注意，如果您在追踪的**根**级别执行此操作（即顶级运行），该运行 ID 将被用作 `trace_id`。',
    '## Access run (span) ID for LangChain invocations': '## 访问 LangChain 调用的运行（跨度）ID',
    'When you invoke a LangChain object, you can manually specify the run ID of the invocation. This run ID can be used to query the run in LangSmith.': '当您调用 LangChain 对象时，您可以手动指定调用的运行 ID。此运行 ID 可用于在 LangSmith 中查询运行。',
    'In JS/TS, you can use a `RunCollectorCallbackHandler` instance to access the run ID.': '在 JS/TS 中，您可以使用 `RunCollectorCallbackHandler` 实例来访问运行 ID。',
    '## Ensure all traces are submitted before exiting': '## 确保在退出前提交所有追踪',
    'In LangChain Python, LangSmith\'s tracing is done in a background thread to avoid obstructing your production application. This means that your process may end before all traces are successfully posted to LangSmith. This is especially prevalent in a serverless environment, where your VM may be terminated immediately once your chain or agent completes.': '在 LangChain Python 中，LangSmith 的追踪在后台线程中完成，以避免阻碍您的生产应用程序。这意味着您的进程可能在所有追踪成功发布到 LangSmith 之前结束。这在无服务器环境中尤为普遍，因为您的 VM 可能在链或代理完成后立即被终止。',
    'You can make callbacks synchronous by setting the `LANGCHAIN_CALLBACKS_BACKGROUND` environment variable to `"false"`.': '您可以通过将 `LANGCHAIN_CALLBACKS_BACKGROUND` 环境变量设置为 `"false"` 来使回调同步。',
    'For both languages, LangChain exposes methods to wait for traces to be submitted before exiting your application. Below is an example:': '对于两种语言，LangChain 都公开了在退出应用程序之前等待追踪提交的方法。以下是一个示例：',
    '## Trace without setting environment variables': '## 无需设置环境变量即可追踪',
    'As mentioned in other guides, the following environment variables allow you to configure tracing enabled, the api endpoint, api key, and the tracing project:': '如其他指南中所述，以下环境变量允许您配置追踪启用、api 端点、api 密钥和追踪项目：',
    'However, in some environments, it is not possible to set environment variables. In these cases, you can set the tracing configuration programmatically.': '但是，在某些环境中，可能无法设置环境变量。在这些情况下，您可以以编程方式设置追踪配置。',
    'This largely builds off of the [previous section](#trace-selectively).': '这主要基于[上一节](#trace-selectively)。',
    '# You can create a client instance with an api key and api url': '# 您可以创建带有 api 密钥和 api url 的客户端实例',
    '# This can be retrieved from a secrets manager': '# 这可以从密钥管理器中检索',
    '# Self-hosted, EU (GCP) (`eu.api...`), or US (AWS) (`aws.api...`) as needed': '# 根据需要，自托管、欧盟（GCP）（`eu.api...`）或美国（AWS）（`aws.api...`）',
    '# You can pass the client and project_name to the tracing_context': '# 您可以将客户端和 project_name 传递给 tracing_context',
    '// You can create a client instance with an api key and api url': '// 您可以创建带有 api 密钥和 api url 的客户端实例',
    '// Self-hosted, EU (GCP) (`eu.api...`), or US (AWS) (`aws.api...`) as needed': '// 根据需要，自托管、欧盟（GCP）（`eu.api...`）或美国（AWS）（`aws.api...`）',
    '// You can pass the client and project_name to the LangChainTracer instance': '// 您可以将客户端和 project_name 传递给 LangChainTracer 实例',
    '## Distributed tracing with LangChain (Python)': '## 使用 LangChain 进行分布式追踪（Python）',
    'LangSmith supports distributed tracing with LangChain Python. This allows you to link runs (spans) across different services and applications. The principles are similar to the [distributed tracing guide](/langsmith/distributed-tracing) for the LangSmith SDK.': 'LangSmith 支持使用 LangChain Python 进行分布式追踪。这允许您跨不同服务和应用程序链接运行（跨度）。原理与 LangSmith SDK 的[分布式追踪指南](/langsmith/distributed-tracing)类似。',
    '-- This code should be in a separate file or service --': '-- 此代码应在单独的文件或服务中 --',
    '## Interoperability between LangChain (Python) and LangSmith SDK': '## LangChain（Python）和 LangSmith SDK 之间的互操作性',
    'If you are using LangChain for part of your application and the LangSmith SDK (see [Custom instrumentation](/langsmith/annotate-code)) for other parts, you can still trace the entire application seamlessly.': '如果您在应用程序的一部分使用 LangChain 而在其他部分使用 LangSmith SDK（请参阅[自定义检测](/langsmith/annotate-code)），您仍然可以无缝追踪整个应用程序。',
    'LangChain objects will be traced when invoked within a `traceable` function and be bound as a child run of the `traceable` function.': 'LangChain 对象在 `traceable` 函数中调用时将被追踪，并作为 `traceable` 函数的子运行绑定。',
    '# The above chain will be traced as a child run of the traceable function': '# 上面的链将作为 traceable 函数的子运行被追踪',
    '## Interoperability between LangChain.JS and LangSmith SDK': '## LangChain.JS 和 LangSmith SDK 之间的互操作性',
    '### Tracing LangChain objects inside `traceable` (JS only)': '### 在 `traceable` 内部追踪 LangChain 对象（仅 JS）',
    'Starting with `langchain@0.2.x`, LangChain objects are traced automatically when used inside `@traceable` functions, inheriting the client, tags, metadata and project name of the traceable function.': '从 `langchain@0.2.x` 开始，LangChain 对象在 `@traceable` 函数内部使用时自动追踪，继承 traceable 函数的客户端、标签、元数据和项目名称。',
    'For older versions of LangChain below `0.2.x`, you will need to manually pass an instance `LangChainTracer` created from the tracing context found in `@traceable`.': '对于低于 `0.2.x` 的旧版 LangChain，您需要手动传递从 `@traceable` 中找到的追踪上下文创建的 `LangChainTracer` 实例。',
    '### Tracing LangChain child runs via `traceable` / RunTree API (JS only)': '### 通过 `traceable` / RunTree API 追踪 LangChain 子运行（仅 JS）',
    'We\'re working on improving the interoperability between `traceable` and LangChain. The following limitations are present when using combining LangChain with `traceable`:': '我们正在努力改进 `traceable` 和 LangChain 之间的互操作性。结合 LangChain 与 `traceable` 时存在以下限制：',
    'Mutating RunTree obtained from `getCurrentRunTree()` of the RunnableLambda context will result in a no-op.': '改变从 RunnableLambda 上下文的 `getCurrentRunTree()` 获得的 RunTree 将导致无操作。',
    'It\'s discouraged to traverse the RunTree obtained from RunnableLambda via `getCurrentRunTree()` as it may not contain all the RunTree nodes.': '不建议通过 `getCurrentRunTree()` 遍历从 RunnableLambda 获得的 RunTree，因为它可能不包含所有 RunTree 节点。',
    'Different child runs may have the same `execution_order` and `child_execution_order` value. Thus in extreme circumstances, some runs may end up in a different order, depending on the `start_time`.': '不同的子运行可能具有相同的 `execution_order` 和 `child_execution_order` 值。因此，在极端情况下，某些运行可能最终处于不同顺序，取决于 `start_time`。',
    'In some uses cases, you might want to run `traceable` functions as part of the RunnableSequence or trace child runs of LangChain run imperatively via the `RunTree` API. Starting with LangSmith 0.1.39 and @langchain/core 0.2.18, you can directly invoke `traceable`-wrapped functions within RunnableLambda.': '在某些用例中，您可能希望将 `traceable` 函数作为 RunnableSequence 的一部分运行，或通过 `RunTree` API 命令式地追踪 LangChain 的子运行。从 LangSmith 0.1.39 和 @langchain/core 0.2.18 开始，您可以直接在 RunnableLambda 中调用 `traceable` 包装的函数。',
    'Alternatively, you can convert LangChain\'s @[`RunnableConfig`] to a equivalent RunTree object by using `RunTree.fromRunnableConfig` or pass the @[`RunnableConfig`] as the first argument of `traceable`-wrapped function.': '或者，您可以使用 `RunTree.fromRunnableConfig` 将 LangChain 的 @[`RunnableConfig`] 转换为等效的 RunTree 对象，或将 @[`RunnableConfig`] 作为 `traceable` 包装函数的第一个参数传递。',
    'If you prefer a video tutorial, check out the [Alternative Ways to Trace video](https://academy.langchain.com/pages/intro-to-langsmith-preview) from the Introduction to LangSmith Course.': '如果您喜欢视频教程，请查看 LangChain 入门课程中的[追踪替代方法视频](https://academy.langchain.com/pages/intro-to-langsmith-preview)。',
}

src = 'src/langsmith/trace-with-langchain.mdx'
dst = 'docs_zh/langsmith/trace-with-langchain.mdx'
translate_file(src, dst, langchainTranslations)
