#!/usr/bin/env python
import os
import sys

def translate_file(src_path, dst_path, translations):
    with open(src_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for eng, chn in translations.items():
        content = content.replace(eng, chn)

    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Translated: {src_path} -> {dst_path}')

# Translation mappings for batch4
translations_batch4 = {
    'test-react-agent-pytest': {
        'Test a ReAct agent with Pytest/Vitest and LangSmith': '使用 Pytest/Vitest 和 LangSmith 测试 ReAct 智能体',
        'This tutorial will show you how to use LangSmith\'s integrations with popular testing tools (Pytest, Vitest, and Jest) to evaluate your LLM application. We will create a ReAct agent that answers questions about publicly traded stocks and write a comprehensive test suite for it.': '本教程将向您展示如何使用 LangSmith 与流行测试工具（Pytest、Vitest 和 Jest）的集成来评估您的大型语言模型应用程序。我们将创建一个能够回答公开交易股票问题的 ReAct 智能体，并为其编写一套全面的测试用例。',
        '## Setup': '## 设置',
        'This tutorial uses [LangGraph](https://langchain-ai.github.io/langgraph/tutorials/introduction/) for agent orchestration, [OpenAI\'s GPT-4o](https://platform.openai.com/docs/models#gpt-4o), [Tavily](https://tavily.com/) for search, [E2B\'s](https://e2b.dev/) code interpreter, and [Polygon](https://polygon.io/stocks) to retrieve stock data but it can be adapted for other frameworks, models and tools with minor modifications. Tavily, E2B and Polygon are free to sign up for.': '本教程使用 [LangGraph](https://langchain-ai.github.io/langgraph/tutorials/introduction/) 进行智能体编排、[OpenAI 的 GPT-4o](https://platform.openai.com/docs/models#gpt-4o) 进行搜索、[Tavily](https://tavily.com/) 进行搜索、[E2B](https://e2b.dev/) 的代码解释器以及 [Polygon](https://polygon.io/stocks) 来检索股票数据，但只需稍作修改即可适配其他框架、模型和工具。Tavily、E2B 和 Polygon 均可免费注册。',
        '### Installation': '### 安装',
        'First, install the packages required for making the agent:': '首先，安装创建智能体所需的包：',
        'Next, install the testing framework:': '接下来，安装测试框架：',
        '### Environment variables': '### 环境变量',
        'Set the following environment variables:': '设置以下环境变量：',
        '## Create your app': '## 创建您的应用',
        'To define our React agent, we will use LangGraph/LangGraph.js for the orchestation and LangChain for the LLM and tools.': '为了定义我们的 ReAct 智能体，我们将使用 LangGraph/LangGraph.js 进行编排，使用 LangChain 处理大型语言模型和工具。',
        '### Define tools': '### 定义工具',
        'First we are going to define the tools we are going to use in our agent. There are going to be 3 tools:': '首先，我们定义将在智能体中使用的工具。将有 3 个工具：',
        '* A search tool using Tavily': '* 使用 Tavily 的搜索工具',
        '* A code interpreter tool using E2B': '* 使用 E2B 的代码解释器工具',
        '* A stock information tool using Polygon': '* 使用 Polygon 的股票信息工具',
        'Now that we have defined all of our tools, we can use @[`create_agent`] to create our agent.': '现在我们已经定义了所有工具，可以使用 @[`create_agent`] 来创建我们的智能体。',
        '## Write tests': '## 编写测试',
        'Now that we have defined our agent, let\'s write a few tests to ensure basic functionality. In this tutorial we are going to test whether the agent\'s tool calling abilities are working, whether the agent knows to ignore irrelevant questions, and whether it is able to answer complex questions that involve using all of the tools.': '现在我们已经定义了智能体，让我们编写一些测试以确保基本功能。本教程中，我们将测试智能体的工具调用能力是否正常工作，智能体是否知道忽略无关问题，以及它是否能够回答涉及使用所有工具的复杂问题。',
        'We need to first set up a test file and add the imports needed at the top of the file.': '我们首先需要设置一个测试文件，并在文件顶部添加所需的导入。',
        '### Test 1: Handle off-topic questions': '### 测试 1：处理无关问题',
        'The first test will be a simple check that the agent does not use tools on irrelevant queries.': '第一个测试将是一个简单检查，确认智能体不会对无关查询使用工具。',
        '### Test 2: Simple tool calling': '### 测试 2：简单工具调用',
        'For tool calling, we are going to verify that the agent calls the correct tool with the correct parameters.': '对于工具调用，我们将验证智能体是否使用正确的参数调用了正确的工具。',
        '### Test 3: Complex tool calling': '### 测试 3：复杂工具调用',
        'Some tool calls are easier to test than others. With the ticker lookup, we can assert that the correct ticker is searched. With the coding tool, the inputs and outputs of the tool are much less constrained, and there are lots of ways to get to the right answer. In this case, it\'s simpler to test that the tool is used correctly by running the full agent and asserting that it both calls the coding tool and that it ends up with the right answer.': '某些工具调用比其他工具调用更容易测试。通过股票代码查找，我们可以断言正确的股票代码被搜索到。对于编码工具，工具的输入和输出的约束要少得多，并且有多种方法可以获得正确答案。在这种情况下，通过运行完整的智能体并断言它既调用了编码工具又得到了正确答案来测试工具是否被正确使用会更简单。',
        '### Test 4: LLM-as-a-judge': '### 测试 4：大型语言模型作为评判者',
        'We are going to ensure that the agent\'s answer is grounded in the search results by running an LLM-as-a-judge evaluation. In order to trace the LLM-as-a-Judge call separately from our agent, we will use the LangSmith provided `trace_feedback` context manager in Python and `wrapEvaluator` function in JS/TS.': '我们将通过运行大型语言模型作为评判者的评估来确保智能体的答案是基于搜索结果的。为了将大型语言模型作为评判者的调用与我们的智能体分开追踪，我们将在 Python 中使用 LangSmith 提供的 `trace_feedback` 上下文管理器，在 JS/TS 中使用 `wrapEvaluator` 函数。',
        '## Run tests': '## 运行测试',
        'Once you have setup your config files (if you are using Vitest or Jest), you can run your tests using the following commands:': '一旦您设置好了配置文件（如果您使用的是 Vitest 或 Jest），可以使用以下命令运行测试：',
        'Remember to also add the config files for Vitest and Jest to your project.': '请记得也将 Vitest 和 Jest 的配置文件添加到您的项目中。',
        '### Agent': '### 智能体',
        '### Tests': '### 测试',
        'The first test will be a simple check that the agent does not use tools on irrelevant queries.': '第一个测试将是一个简单检查，确认智能体不会对无关查询使用工具。',
        'Test that the agent does not use tools on offtopic queries.': '测试智能体不会对无关问题使用工具。',
        'Test that the model looks up the correct ticker on simple query.': '测试模型在简单查询时查找正确的股票代码。',
        'Test that the agent executes code when needed': '测试智能体在需要时执行代码',
        'Test that response is grounded in the tool outputs.': '测试响应是基于工具输出的。',
        'Evaluate the groundedness of an answer in source documents.': '评估答案在源文档中的有据可查性。',
        'Create a `tests/test_agent.py` file.': '创建一个 `tests/test_agent.py` 文件。',
        'Name your test file `agent.vitest.eval.ts`': '将您的测试文件命名为 `agent.vitest.eval.ts`',
        'Name your test file `agent.jest.eval.ts`': '将您的测试文件命名为 `agent.jest.eval.ts`',
        'Optional, but recommended to group tests together': '可选，但建议将测试分组在一起',
        'Agent Tests': '智能体测试',
        'PLACE TESTS Here': '在此处放置测试',
    },
    'trace-with-strands-agents': {
        'Trace Strands Agents applications': '追踪 Strands Agents 应用程序',
        '[Strands Agents](https://strandsagents.com/) is an SDK for building model-driven agents. LangSmith provides a Strands Agents integration that exports Strands OpenTelemetry spans in a LangSmith-compatible format, including agent runs, model calls, tool calls, prompts, completions, and token usage.': '[Strands Agents](https://strandsagents.com/) 是一个用于构建模型驱动智能体的 SDK。LangSmith 提供了 Strands Agents 集成，以 LangSmith 兼容的格式导出 Strands OpenTelemetry 跨度，包括智能体运行、模型调用、工具调用、提示词、完成内容和令牌使用情况。',
        '## Installation': '## 安装',
        'Install LangSmith with Strands Agents support:': '安装带有 Strands Agents 支持的 LangSmith：',
        'This installs LangSmith, Strands Agents, Strands Agents tools, and the OpenTelemetry OTLP HTTP exporter.': '这将安装 LangSmith、Strands Agents、Strands Agents 工具和 OpenTelemetry OTLP HTTP 导出器。',
        '## Setup': '## 设置',
        '### 1. Configure environment variables': '### 1. 配置环境变量',
        'Set your [LangSmith API key](/langsmith/create-account-api-key) and project name. If you use Amazon Bedrock as the model provider for Strands Agents, also configure AWS credentials with your preferred AWS authentication method.': '设置您的 [LangSmith API 密钥](/langsmith/create-account-api-key) 和项目名称。如果您使用 Amazon Bedrock 作为 Strands Agents 的模型提供商，还请使用您首选的 AWS 身份验证方法配置 AWS 凭据。',
        '<Note>': '<Note>',
        'The Strands Agents integration uses the standard OpenTelemetry OTLP exporter. Configure the LangSmith endpoint and headers before calling `setup_langsmith_telemetry()`.': 'Strands Agents 集成使用标准的 OpenTelemetry OTLP 导出器。在调用 `setup_langsmith_telemetry()` 之前配置 LangSmith 端点和头。',
        '### 2. Enable Strands Agents telemetry': '### 2. 启用 Strands Agents 遥测',
        'Call `setup_langsmith_telemetry()` once at application startup before creating or invoking agents:': '在应用程序启动时创建或调用智能体之前，调用一次 `setup_langsmith_telemetry()`：',
        'For local debugging, pass `console=True` to also print transformed spans to stdout:': '对于本地调试，传入 `console=True` 以将转换后的跨度也打印到 stdout：',
        '### 3. Create and run your agent': '### 3. 创建并运行您的智能体',
        'Once configured, Strands Agents traces are exported to LangSmith automatically:': '配置完成后，Strands Agents 追踪会自动导出到 LangSmith：',
        '## View traces in LangSmith': '## 在 LangSmith 中查看追踪',
        'After running your application, open your LangSmith project to view traces that include:': '运行应用程序后，打开您的 LangSmith 项目以查看包含以下内容的追踪：',
        '- Agent invocation spans': '- 智能体调用跨度',
        '- Event loop cycle spans': '- 事件循环周期跨度',
        '- LLM call spans with prompts, completions, and token usage': '- 带提示词、完成内容和令牌使用情况的大型语言模型调用跨度',
        '- Tool call spans with tool inputs and outputs when your agent uses tools': '- 当智能体使用工具时，带有工具输入和输出的工具调用跨度',
        '## Customize the OTLP exporter': '## 自定义 OTLP 导出器',
        'If you need to pass custom options to the underlying OpenTelemetry exporter, create a `LangSmithSpanExporter` with `create_langsmith_exporter()` and attach it to the Strands tracer provider manually:': '如果您需要将自定义选项传递给底层 OpenTelemetry 导出器，请使用 `create_langsmith_exporter()` 创建 `LangSmithSpanExporter`，并将其手动附加到 Strands 追踪器提供者：',
        'Use this approach when you want to configure exporter options in code instead of environment variables.': '当您想在代码中而不是通过环境变量配置导出器选项时，请使用此方法。',
        '## Resources': '## 资源',
        '- [Strands Agents documentation](https://strandsagents.com/)': '- [Strands Agents 文档](https://strandsagents.com/)',
        '- [LangSmith OpenTelemetry guide](/langsmith/trace-with-opentelemetry)': '- [LangSmith OpenTelemetry 指南](/langsmith/trace-with-opentelemetry)',
    },
    'trace-with-temporal': {
        'Trace with Temporal': '使用 Temporal 进行追踪',
        '[Temporal](https://temporal.io/) is a durable execution platform that enables developers to build resilient distributed applications. This guide shows you how to trace Temporal workflows and activities in LangSmith using OpenTelemetry.': '[Temporal](https://temporal.io/) 是一个持久执行平台，使开发者能够构建弹性的分布式应用程序。本指南向您展示如何使用 OpenTelemetry 在 LangSmith 中追踪 Temporal 工作流和活动。',
        'LangSmith supports OpenTelemetry (OTEL) trace ingestion, which integrates seamlessly with Temporal\'s native OpenTelemetry interceptors. This enables full distributed tracing across your workflow executions, activities, and any LLM calls within them.': 'LangSmith 支持 OpenTelemetry (OTEL) 追踪摄取，与 Temporal 的原生 OpenTelemetry 拦截器无缝集成。这使得您的工作流执行、活动及其中的任何大型语言模型调用都能实现完整的分布式追踪。',
        '## Prerequisites': '## 前置条件',
        '- A [LangSmith account](https://smith.langchain.com/) and API key': '- 一个 [LangSmith 账户](https://smith.langchain.com/) 和 API 密钥',
        '- Temporal server running (local or cloud)': '- 运行中的 Temporal 服务器（本地或云）',
        '- OpenTelemetry SDK for your language': '- 您所使用语言的 OpenTelemetry SDK',
        '## Environment variables': '## 环境变量',
        'Set the following environment variables for all implementations:': '为所有实现设置以下环境变量：',
        '<Note>': '<Note>',
        'For EU region or self-hosted LangSmith installations, also set `LANGCHAIN_BASE_URL` to your LangSmith instance URL.': '对于 EU 区域或自托管的 LangSmith 安装，还要将 `LANGCHAIN_BASE_URL` 设置为您的 LangSmith 实例 URL。',
        '## Set up tracing': '## 设置追踪',
        'Go uses the `langsmith-go` SDK with Temporal\'s OpenTelemetry interceptors to automatically trace workflows and activities.': 'Go 使用 `langsmith-go` SDK 和 Temporal 的 OpenTelemetry 拦截器自动追踪工作流和活动。',
        'Python uses the `temporalio` SDK with OpenTelemetry interceptors, exporting traces to LangSmith via OTLP.': 'Python 使用 `temporalio` SDK 和 OpenTelemetry 拦截器，通过 OTLP 将追踪导出到 LangSmith。',
        'TypeScript uses the `@temporalio/sdk` with OpenTelemetry interceptors to send traces to LangSmith.': 'TypeScript 使用 `@temporalio/sdk` 和 OpenTelemetry 拦截器将追踪发送到 LangSmith。',
        '## View traces in LangSmith': '## 在 LangSmith 中查看追踪',
        'Once configured, traces will appear in your LangSmith project:': '配置完成后，追踪将出现在您的 LangSmith 项目中：',
        '1. Navigate to your LangSmith instance.': '1. 导航到您的 LangSmith 实例。',
        '2. Select your project.': '2. 选择您的项目。',
        '3. View traces in the **Tracing** tab.': '3. 在 **追踪** 选项卡中查看追踪。',
        '4. Click on individual traces to see the full span hierarchy.': '4. 点击单个追踪以查看完整的跨度层次结构。',
        '## Configuration options': '## 配置选项',
        '### Set a custom service name': '### 设置自定义服务名称',
        'Set a custom service name to distinguish different Temporal workers or services:': '设置自定义服务名称以区分不同的 Temporal 工作线程或服务：',
        '### Add custom span attributes': '### 添加自定义跨度属性',
        'Add custom attributes to enrich your traces:': '添加自定义属性以丰富您的追踪：',
        '### Configure sampling': '### 配置采样',
        'For high-volume workflows, configure sampling to reduce trace volume:': '对于高流量工作流，配置采样以减少追踪量：',
        '## Troubleshooting': '## 故障排除',
        '### Traces not appearing': '### 追踪不出现',
        '1. **Verify API key**: Ensure `LANGSMITH_API_KEY` is set correctly': '1. **验证 API 密钥**：确保正确设置 `LANGSMITH_API_KEY`',
        '2. **Check endpoint**: Confirm you\'re using `https://api.smith.langchain.com/otel/v1/traces`': '2. **检查端点**：确认您正在使用 `https://api.smith.langchain.com/otel/v1/traces`',
        '3. **Flush on shutdown**: Call `provider.shutdown()` to flush pending spans before the application exits': '3. **关闭时刷新**：在应用程序退出之前调用 `provider.shutdown()` 来刷新待处理的跨度',
        '4. **Check project**: Verify traces are sent to the correct project (default is `"default"`)': '4. **检查项目**：验证追踪是否发送到正确的项目（默认是 `"default"`）',
        '### Missing activity spans': '### 缺少活动跨度',
        'Ensure the tracing interceptor is configured on both the client and worker:': '确保在客户端和工作线程上都配置了追踪拦截器：',
        '- **Client**: Needs interceptor for starting workflows': '- **客户端**：需要拦截器来启动工作流',
        '- **Worker**: Needs interceptor for executing activities': '- **工作线程**：需要拦截器来执行活动',
        '### Context propagation issues': '### 上下文传播问题',
        'Verify propagators are configured correctly:': '验证传播者配置正确：',
        '- **Go**: `langsmith.NewTracer()` automatically configures propagators': '- **Go**：`langsmith.NewTracer()` 自动配置传播者',
        '- **Python/TypeScript**: Ensure OpenTelemetry SDK is properly initialized with trace propagators': '- **Python/TypeScript**：确保 OpenTelemetry SDK 使用追踪传播者正确初始化',
        '### Worker shutdown hangs': '### 工作线程关闭挂起',
        'If traces aren\'t flushing, ensure you\'re calling the shutdown method with proper timeout:': '如果追踪没有刷新，请确保您使用正确的超时时间调用关闭方法：',
        '## Next steps': '## 下一步',
        '- [Learn about LangSmith tracing concepts](/langsmith/observability-concepts)': '- [了解 LangSmith 追踪概念](/langsmith/observability-concepts)',
        '- [Explore OpenTelemetry semantic conventions](/langsmith/trace-with-opentelemetry#supported-opentelemetry-attribute-and-event-mapping)': '- [探索 OpenTelemetry 语义约定](/langsmith/trace-with-opentelemetry#supported-opentelemetry-attribute-and-event-mapping)',
        '## Additional resources': '## 其他资源',
        '- [Temporal Documentation](https://docs.temporal.io/)': '- [Temporal 文档](https://docs.temporal.io/)',
        '- [Temporal Go SDK](https://github.com/temporalio/sdk-go)': '- [Temporal Go SDK](https://github.com/temporalio/sdk-go)',
        '- [Temporal Python SDK](https://github.com/temporalio/sdk-python)': '- [Temporal Python SDK](https://github.com/temporalio/sdk-python)',
        '- [Temporal TypeScript SDK](https://github.com/temporalio/sdk-typescript)': '- [Temporal TypeScript SDK](https://github.com/temporalio/sdk-typescript)',
        '- [OpenTelemetry Documentation](https://opentelemetry.io/docs/)': '- [OpenTelemetry 文档](https://opentelemetry.io/docs/)',
        '- [LangSmith Go SDK](https://github.com/langchain-ai/langsmith-go)': '- [LangSmith Go SDK](https://github.com/langchain-ai/langsmith-go)',
    },
    'trace-with-vercel-ai-sdk': {
        'Trace Vercel AI SDK applications (JS/TS only)': '追踪 Vercel AI SDK 应用程序（仅限 JS/TS）',
        'You can use LangSmith to trace runs from the Vercel AI SDK. This guide will walk through an example.': '您可以使用 LangSmith 追踪来自 Vercel AI SDK 的运行。本指南将通过一个示例进行讲解。',
        '## Installation': '## 安装',
        '<Note>': '<Note>',
        'This wrapper requires AI SDK v5 and `langsmith>=0.3.63`. If you are using an older version of the AI SDK or `langsmith`, see the OpenTelemetry (OTEL) based approach [on this page](/langsmith/legacy-trace-with-vercel-ai-sdk).': '此包装器需要 AI SDK v5 和 `langsmith>=0.3.63`。如果您使用的是旧版本的 AI SDK 或 `langsmith`，请参阅[此页面](/langsmith/legacy-trace-with-vercel-ai-sdk)上基于 OpenTelemetry (OTEL) 的方法。',
        'Install the Vercel AI SDK. This guide uses Vercel\'s OpenAI integration for the code snippets below, but you can use any of their other options as well.': '安装 Vercel AI SDK。本指南在下面的代码片段中使用 Vercel 的 OpenAI 集成，您也可以使用他们的其他选项。',
        '## Environment configuration': '## 环境配置',
        '## Basic setup': '## 基本设置',
        'Import and wrap AI SDK methods, then use them as you normally would:': '导入并包装 AI SDK 方法，然后按常规使用：',
        'You should see a trace in your LangSmith dashboard [like this one](https://smith.langchain.com/public/4f0e689e-c801-44d3-8857-93b47ab100cc/r).': '您应该在 LangSmith 仪表板中看到追踪[像这样](https://smith.langchain.com/public/4f0e689e-c801-44d3-8857-93b47ab100cc/r)。',
        'You can also trace runs with tool calls:': '您也可以追踪带有工具调用的运行：',
        'Which results in a trace like [this one](https://smith.langchain.com/public/6075fa2c-d255-4885-a66a-4fc798afaa9f/r).': '这将产生一个像[这样](https://smith.langchain.com/public/6075fa2c-d255-4885-a66a-4fc798afaa9f/r)的追踪。',
        'You can use other AI SDK methods exactly as you usually would.': '您可以完全按照平常的方式使用其他 AI SDK 方法。',
        '### With `traceable`': '### 使用 `traceable`',
        'You can wrap `traceable` calls around AI SDK calls or within AI SDK tool calls. This is useful if you want to group runs together in LangSmith:': '您可以在 AI SDK 调用周围或 AI SDK 工具调用内部包装 `traceable` 调用。如果您想将运行分组在一起以便在 LangSmith 中查看，这会很有用：',
        'The resulting trace will look [like this](https://smith.langchain.com/public/ff25bc26-9389-4798-8b91-2bdcc95d4a8e/r).': '结果追踪看起来[像这样](https://smith.langchain.com/public/ff25bc26-9389-4798-8b91-2bdcc95d4a8e/r)。',
        '## Tracing in serverless environments': '## 无服务器环境中的追踪',
        'When tracing in serverless environments, you must wait for all runs to flush before your environment shuts down. To do this, you can pass a LangSmith [`Client`](https://docs.smith.langchain.com/reference/js/classes/client.Client) instance when wrapping the AI SDK method, then call `await client.awaitPendingTraceBatches()`.': '在无服务器环境中追踪时，必须等待所有运行刷新后再关闭环境。为此，您可以在包装 AI SDK 方法时传递 LangSmith [`Client`](https://docs.smith.langchain.com/reference/js/classes/client.Client) 实例，然后调用 `await client.awaitPendingTraceBatches()`。',
        'Make sure to also pass it into any `traceable` wrappers you create:': '请确保也将它传递给您创建的任何 `traceable` 包装器：',
        'If you are using `Next.js`, there is a convenient [`after`](https://nextjs.org/docs/app/api-reference/functions/after) hook where you can put this logic:': '如果您使用的是 `Next.js`，有一个方便的 [`after`](https://nextjs.org/docs/app/api-reference/functions/after) 钩子，您可以在其中放置此逻辑：',
        'See [Trace JS functions in serverless environments](/langsmith/serverless-environments) for more detail, including information around managing rate limits in serverless environments.': '有关更多详细信息，包括在无服务器环境中管理速率限制的信息，请参阅[在无服务器环境中追踪 JS 函数](/langsmith/serverless-environments)。',
        '## Passing LangSmith config': '## 传递 LangSmith 配置',
        'You can pass LangSmith-specific config to your wrapper both when initially wrapping your AI SDK methods and while running them via `providerOptions.langsmith`.': '您可以在最初包装 AI SDK 方法时以及通过 `providerOptions.langsmith` 运行它们时，将 LangSmith 特定配置传递给您的包装器。',
        'This includes metadata (which you can later use to filter runs in LangSmith), top-level run name, tags, custom client instances, and more.': '这包括元数据（您稍后可用它来在 LangSmith 中过滤运行）、顶级运行名称、标签、自定义客户端实例等。',
        'Config passed while wrapping will apply to all future calls you make with the wrapped method:': '包装时传递的配置将适用于您使用该包装方法进行的所有未来调用：',
        'While passing config at runtime via `providerOptions.langsmith` will apply only to that run.': '虽然通过 `providerOptions.langsmith` 在运行时传递的配置仅适用于该运行。',
        'We suggest importing and wrapping your config in `createLangSmithProviderOptions` to ensure proper typing:': '我们建议在 `createLangSmithProviderOptions` 中导入和包装您的配置以确保正确的类型：',
        '## Specify a custom run ID': '## 指定自定义运行 ID',
        'You can pre-specify a run ID per call using `providerOptions` with [`createLangSmithProviderOptions`](https://reference.langchain.com/javascript/langsmith/experimental/vercel#member-createLangSmithProviderOptions-1). Use `uuid7()` from the LangSmith SDK to generate a valid ID:': '您可以使用 `providerOptions` 和 [`createLangSmithProviderOptions`](https://reference.langchain.com/javascript/langsmith/experimental/vercel#member-createLangSmithProviderOptions-1) 为每次调用预先指定运行 ID。使用 LangSmith SDK 中的 `uuid7()` 生成有效 ID：',
        'For more details on specifying a run ID manually, refer to [Specify a custom run ID](/langsmith/annotate-code#specify-a-custom-run-id).': '有关手动指定运行 ID 的更多详细信息，请参阅[指定自定义运行 ID](/langsmith/annotate-code#specify-a-custom-run-id)。',
        '## Redacting data': '## 数据编辑',
        'You can customize what inputs and outputs the AI SDK sends to LangSmith by specifying custom input/output processing functions. This is useful if you are dealing with sensitive data that you would like to avoid sending to LangSmith.': '您可以通过指定自定义输入/输出处理函数来自定义 AI SDK 发送到 LangSmith 的输入和输出。如果您处理的是敏感数据且不想发送到 LangSmith，这将很有用。',
        'Because output formats vary depending on which AI SDK method you are using, we suggest defining and passing config individually into wrapped methods. You will also need to provide separate functions for child LLM runs within AI SDK calls, since calling `generateText` at top level calls the LLM internally and can do so multiple times.': '因为输出格式因您使用的 AI SDK 方法而异，我们建议在包装方法中单独定义和传递配置。您还需要为 AI SDK 调用中的子大型语言模型运行提供单独的函数，因为在顶层调用 `generateText` 会在内部调用大型语言模型，并且可以多次调用。',
        'We also suggest passing a generic parameter into `createLangSmithProviderOptions` to get proper types for inputs and outputs.': '我们还建议将泛型参数传递到 `createLangSmithProviderOptions` 中，以获取输入和输出的正确类型。',
        'The actual return value will contain the original, non-redacted result but the trace in LangSmith will be redacted. [Here\'s an example](https://smith.langchain.com/public/b4c69c8e-285b-4c0c-8492-e571e2cf562f/r).': '实际返回值将包含原始的、未编辑的结果，但 LangSmith 中的追踪将被编辑。[这是一个示例](https://smith.langchain.com/public/b4c69c8e-285b-4c0c-8492-e571e2cf562f/r)。',
        'For redacting tool input/output, wrap your `execute` method in a `traceable` like this:': '要编辑工具输入/输出，请将您的 `execute` 方法包装在 `traceable` 中，如下所示：',
        'The `traceable` return type is complex, which makes the cast necessary. You may also omit the AI SDK `tool` wrapper function if you wish to avoid the cast.': '`traceable` 返回类型很复杂，因此需要类型转换。如果您希望避免类型转换，也可以省略 AI SDK `tool` 包装函数。',
    },
    'trace-without-env-vars': {
        'Trace without setting environment variables': '无需设置环境变量即可追踪',
        'As mentioned in other guides, the following environment variables allow you to configure tracing enabled, the api endpoint, the api key, and the tracing project:': '如其他指南中提到的，以下环境变量允许您配置追踪启用、API 端点、API 密钥和追踪项目：',
        'If you need to trace runs with a custom configuration, are working in an environment that doesn\'t support typical environment variables (such as Cloudflare Workers), or would simply prefer not to rely on environment variables, LangSmith allows you to configure tracing programmatically.': '如果您需要使用自定义配置追踪运行，正在一个不支持典型环境变量的环境中工作（如 Cloudflare Workers），或者只是不想依赖环境变量，LangSmith 允许您以编程方式配置追踪。',
        '<Warning>': '<Warning>',
        'Due to a number of asks for finer-grained control of tracing using the `trace` context manager, **we changed the behavior** of `with trace` to honor the `LANGSMITH_TRACING` environment variable in version **0.1.95** of the Python SDK. You can find more details in the [release notes](https://github.com/langchain-ai/langsmith-sdk/releases/tag/v0.1.95). The recommended way to disable/enable tracing without setting environment variables is to use the `with tracing_context` context manager, as shown in the example below.': '由于许多用户要求使用 `trace` 上下文管理器对追踪进行更细粒度的控制，**我们改变了** `with trace` **的行为**，使其在 Python SDK 版本 **0.1.95** 中遵循 `LANGSMITH_TRACING` 环境变量。您可以在[发布说明](https://github.com/langchain-ai/langsmith-sdk/releases/tag/v0.1.95)中找到更多详细信息。在不设置环境变量的情况下禁用/启用追踪的推荐方法是使用 `with tracing_context` 上下文管理器，如下例所示。',
        '- Python: The recommended way to do this in Python is to use the `tracing_context` context manager. This works for both code annotated with `traceable` and code within the `trace` context manager.': '- Python：在 Python 中这样做推荐的方法是使用 `tracing_context` 上下文管理器。这适用于使用 `traceable` 注解的代码和 `trace` 上下文管理器内的代码。',
        '- TypeScript: You can pass in both the client and the `tracingEnabled` flag to the `traceable` decorator.': '- TypeScript：您可以同时将客户端和 `tracingEnabled` 标志传递给 `traceable` 装饰器。',
        'If you prefer a video tutorial, check out the [Alternative Ways to Trace video](https://academy.langchain.com/pages/intro-to-langsmith-preview) from the Introduction to LangSmith Course.': '如果您更喜欢视频教程，请查看 LangSmith 入门课程中的[追踪替代方法视频](https://academy.langchain.com/pages/intro-to-langsmith-preview)。',
        '## Related': '## 相关内容',
        'If you need to dynamically enable or disable tracing based on runtime conditions (such as client requirements, data sensitivity, or compliance policies), refer to [Conditional tracing](/langsmith/conditional-tracing) for examples.': '如果您需要根据运行时条件动态启用或禁用追踪（如客户端要求、数据敏感性或合规策略），请参阅[条件追踪](/langsmith/conditional-tracing)以获取示例。',
    },
    'trajectory-evals': {
        'How to evaluate your agent with trajectory evaluations': '如何使用轨迹评估来评估您的智能体',
        'Many agent behaviors only emerge when using a real LLM, such as which tool the agent decides to call, how it formats responses, or whether a prompt modification affects the entire execution trajectory. LangChain\'s [`agentevals`](https://github.com/langchain-ai/agentevals) package provides evaluators specifically designed for testing agent trajectories with live models.': '许多智能体行为只有在使用真实大型语言模型时才会出现，例如智能体决定调用哪个工具、如何格式化响应，或者提示词修改是否影响整个执行轨迹。LangChain 的 [`agentevals`](https://github.com/langchain-ai/agentevals) 包提供了专门为使用实时模型测试智能体轨迹而设计的评估器。',
        '<Note>': '<Note>',
        'This guide covers the open source [LangChain](/oss/langchain/overview) `agentevals` package, which integrates with LangSmith for trajectory evaluation.': '本指南涵盖开源的 [LangChain](/oss/langchain/overview) `agentevals` 包，它与 LangSmith 集成进行轨迹评估。',
        'AgentEvals allows you to evaluate the trajectory of your agent (the exact sequence of messages, including tool calls) by performing a _trajectory match_ or by using an _LLM judge_:': 'AgentEvals 允许您通过执行轨迹匹配或使用大型语言模型评判器来评估智能体的轨迹（精确的消息序列，包括工具调用）：',
        'Hard-code a reference trajectory for a given input and validate the run via a step-by-step comparison.': '为给定输入硬编码一个参考轨迹，并通过逐步比较验证运行。',
        'Ideal for testing well-defined workflows where you know the expected behavior. Use when you have specific expectations about which tools should be called and in what order. This approach is deterministic, fast, and cost-effective since it doesn\'t require additional LLM calls.': '非常适合测试您知道预期行为的定义良好的工作流。在您对应该调用哪些工具以及以什么顺序调用有特定期望时使用。由于不需要额外的大型语言模型调用，这种方法是确定性的、快速的且具有成本效益的。',
        'Use a LLM to qualitatively validate your agent\'s execution trajectory. The "judge" LLM reviews the agent\'s decisions against a prompt rubric (which can include a reference trajectory).': '使用大型语言模型对智能体的执行轨迹进行定性验证。"评判者"大型语言模型根据提示词评分标准（可以包括参考轨迹）审查智能体的决策。',
        'More flexible and can assess nuanced aspects like efficiency and appropriateness, but requires an LLM call and is less deterministic. Use when you want to evaluate the overall quality and reasonableness of the agent\'s trajectory without strict tool call or ordering requirements.': '更灵活，可以评估效率和适当性等细微方面，但需要大型语言模型调用且确定性较低。当您想评估智能体轨迹的整体质量和合理性，而没有严格的工具调用或排序要求时使用。',
        '## Installing AgentEvals': '## 安装 AgentEvals',
        'Or, clone the [AgentEvals repository](https://github.com/langchain-ai/agentevals) directly.': '或者，直接克隆 [AgentEvals 仓库](https://github.com/langchain-ai/agentevals)。',
        '## Trajectory match evaluator': '## 轨迹匹配评估器',
        'AgentEvals offers the `create_trajectory_match_evaluator` function in Python and `createTrajectoryMatchEvaluator` in TypeScript to match your agent\'s trajectory against a reference trajectory.': 'AgentEvals 在 Python 中提供 `create_trajectory_match_evaluator` 函数，在 TypeScript 中提供 `createTrajectoryMatchEvaluator`，以将您的智能体轨迹与参考轨迹进行匹配。',
        'You can use the following modes:': '您可以使用以下模式：',
        '| Mode | Description | Use Case |': '| 模式 | 描述 | 使用场景 |',
        '| [`strict`](#strict-match) | Exact match of messages and tool calls in the same order | Testing specific sequences (e.g., policy lookup before authorization) |': '| [`strict`](#strict-match) | 消息和工具调用完全按相同顺序匹配 | 测试特定序列（例如，授权前的策略查找） |',
        '| [`unordered`](#unordered-match) | Same tool calls allowed in any order | Verifying information retrieval when order doesn\'t matter |': '| [`unordered`](#unordered-match) | 相同的工具调用允许以任何顺序出现 | 验证信息检索（当顺序不重要时） |',
        '| [`subset`](#subset-and-superset-match) | Agent calls only tools from reference (no extras) | Ensuring agent doesn\'t exceed expected scope |': '| [`subset`](#subset-and-superset-match) | 智能体仅调用参考中的工具（无额外项） | 确保智能体不超过预期范围 |',
        '| [`superset`](#subset-and-superset-match) | Agent calls at least the reference tools (extras allowed) | Verifying minimum required actions are taken |': '| [`superset`](#subset-and-superset-match) | 智能体至少调用参考工具（允许额外项） | 验证采取了最小要求的操作 |',
        '### Strict match': '### 严格匹配',
        'The `strict` mode ensures trajectories contain identical messages in the same order with the same tool calls, though it allows for differences in message content. This is useful when you need to enforce a specific sequence of operations, such as requiring a policy lookup before authorizing an action.': '`strict` 模式确保轨迹包含相同顺序的相同消息和相同的工具调用，尽管它允许消息内容存在差异。当您需要强制执行特定的操作序列时，这很有用，例如要求在授权操作之前进行策略查找。',
        '### Unordered match': '### 无序匹配',
        'The `unordered` mode allows the same tool calls in any order, which is helpful when you want to verify that the correct set of tools are being invoked but don\'t care about the sequence. For example, an agent might need to check both weather and events for a city, but the order doesn\'t matter.': '`unordered` 模式允许以任何顺序调用相同的工具，这在您想验证是否正在调用正确的工具集但不关心顺序时很有帮助。例如，智能体可能需要检查某个城市的天气和事件，但顺序并不重要。',
        '### Subset and superset match': '### 子集和超集匹配',
        'The `superset` and `subset` modes focus on which tools are called rather than the order of tool calls, allowing you to control how strictly the agent\'s tool calls must align with the reference.': '`superset` 和 `subset` 模式专注于调用了哪些工具而不是工具调用的顺序，允许您控制智能体的工具调用必须与参考对齐的严格程度。',
        '- Use `superset` mode when you want to verify that a few key tools are called in the execution, but you\'re okay with the agent calling additional tools. The agent\'s trajectory must include at least all the tool calls in the reference trajectory, and may include additional tool calls beyond the reference.': '- 当您想验证在执行中调用了一些关键工具，但可以接受智能体调用额外工具时，使用 `superset` 模式。智能体的轨迹必须至少包含参考轨迹中的所有工具调用，并且可以包括超出参考的额外工具调用。',
        '- Use `subset` mode to ensure agent efficiency by verifying that the agent did not call any irrelevant or unnecessary tools beyond those in the reference. The agent\'s trajectory must include only tool calls that appear in the reference trajectory.': '- 使用 `subset` 模式通过验证智能体没有调用参考中之外的任何无关或不必要的工具来确保智能体效率。智能体的轨迹必须仅包含出现在参考轨迹中的工具调用。',
        '<Info>': '<Info>',
        'You can also customize how the evaluator considers equality between tool calls in the actual trajectory vs. the reference by setting the `tool_args_match_mode` (Python) or `toolArgsMatchMode` (TypeScript) property, as well as the `tool_args_match_overrides` (Python) or `toolArgsMatchOverrides` (TypeScript) property. By default, only tool calls with the same arguments to the same tool are considered equal. Visit the [repository](https://github.com/langchain-ai/agentevals?tab=readme-ov-file#tool-args-match-modes) for more details.': '您还可以通过设置 `tool_args_match_mode`（Python）或 `toolArgsMatchMode`（TypeScript）属性以及 `tool_args_match_overrides`（Python）或 `toolArgsMatchOverrides`（TypeScript）属性来自定义评估器如何考虑实际轨迹与参考之间工具调用的相等性。默认情况下，只有具有相同参数的相同工具的工具调用被认为是相等的。访问[仓库](https://github.com/langchain-ai/agentevals?tab=readme-ov-file#tool-args-match-modes)了解更多详细信息。',
        '## LLM-as-judge evaluator': '## 大型语言模型作为评判者评估器',
        '<Note>': '<Note>',
        'This section covers the trajectory-specific LLM-as-a-judge evaluator from the `agentevals` package. For general-purpose LLM-as-a-judge evaluators in LangSmith, refer to the [LLM-as-a-judge evaluator](/langsmith/llm-as-judge).': '本节涵盖来自 `agentevals` 包的特定于轨迹的大型语言模型作为评判者评估器。对于 LangSmith 中通用的大型语言模型作为评判者评估器，请参阅[大型语言模型作为评判者评估器](/langsmith/llm-as-judge)。',
        'You can also use an LLM to evaluate the agent\'s execution path. Unlike the trajectory match evaluators, it doesn\'t require a reference trajectory, but one can be provided if available.': '您也可以使用大型语言模型来评估智能体的执行路径。与轨迹匹配评估器不同，它不需要参考轨迹，但如果可用，可以提供一个。',
        '### Without reference trajectory': '### 无参考轨迹',
        '### With reference trajectory': '### 带参考轨迹',
        'If you have a reference trajectory, you can add an extra variable to your prompt and pass in the reference trajectory. Below, we use the prebuilt `TRAJECTORY_ACCURACY_PROMPT_WITH_REFERENCE` prompt and configure the `reference_outputs` variable:': '如果您有参考轨迹，可以向提示词添加一个额外变量并传入参考轨迹。下面，我们使用预构建的 `TRAJECTORY_ACCURACY_PROMPT_WITH_REFERENCE` 提示词并配置 `reference_outputs` 变量：',
        '<Info>': '<Info>',
        'For more configurability over how the LLM evaluates the trajectory, visit the [repository](https://github.com/langchain-ai/agentevals?tab=readme-ov-file#trajectory-llm-as-judge).': '有关大型语言模型如何评估轨迹的更多可配置性，请访问[仓库](https://github.com/langchain-ai/agentevals?tab=readme-ov-file#trajectory-llm-as-judge)。',
        '## Async support (Python)': '## 异步支持（Python）',
        'All `agentevals` evaluators support Python asyncio. For evaluators that use factory functions, async versions are available by adding `async` after `create_` in the function name.': '所有 `agentevals` 评估器都支持 Python asyncio。对于使用工厂函数的评估器，通过在函数名中的 `create_` 后面添加 `async` 来提供异步版本。',
        'Here\'s an example using the async judge and evaluator:': '以下是使用异步评判器和评估器的示例：',
    },
    'troubleshooting-studio': {
        'Studio troubleshooting': 'Studio 故障排除',
        '## Safari connection issues': '## Safari 连接问题',
        'Safari blocks plain-HTTP traffic on localhost. When running Studio with `langgraph dev`, you may see "Failed to load assistants" errors.': 'Safari 阻止 localhost 上的纯 HTTP 流量。当使用 `langgraph dev` 运行 Studio 时，您可能会看到"Failed to load assistants"错误。',
        '### Solution 1: Use Cloudflare Tunnel': '### 解决方案 1：使用 Cloudflare Tunnel',
        'The command outputs a tunnel URL. To connect Studio:': '命令输出一个隧道 URL。要连接 Studio：',
        '1. Copy the tunnel URL (e.g., `https://hamilton-praise-heart-costumes.trycloudflare.com`)': '1. 复制隧道 URL（例如 `https://hamilton-praise-heart-costumes.trycloudflare.com`）',
        '2. Open Studio at `https://smith.langchain.com/studio/`': '2. 在 `https://smith.langchain.com/studio/` 打开 Studio',
        '3. Click **Connect to a local server**': '3. 点击**连接到本地服务器**',
        '4. Paste the tunnel URL and add it to **Allowed Origins**': '4. 粘贴隧道 URL 并将其添加到**允许的来源**',
        '5. Click **Connect**': '5. 点击**连接**',
        'This manual step is required for security - Studio requires explicit user confirmation before connecting to external URLs.': '此手动步骤是出于安全考虑 - Studio 在连接到外部 URL 之前需要用户的明确确认。',
        '<Note>': '<Note>',
        'Cloudflare tunnels can be unreliable and may intermittently disconnect.': 'Cloudflare 隧道可能不可靠，可能会间歇性断开连接。',
        '### Solution 2: Use Chromium browser': '### 解决方案 2：使用 Chromium 浏览器',
        'Chrome and other Chromium browsers allow HTTP on localhost. Use `langgraph dev` without additional configuration.': 'Chrome 和其他 Chromium 浏览器允许 localhost 上的 HTTP。使用 `langgraph dev` 无需额外配置。',
        '## Chrome connection issues': '## Chrome 连接问题',
        'Starting with Chrome version 142, you may experience "Failed to initialize Studio" errors with "TypeError: Failed to fetch" when trying to connect [LangSmith Studio](/langsmith/studio) to your local development server via [`langgraph dev`](/langsmith/cli). This occurs even when the API server at `http://127.0.0.1:2024/docs` loads successfully.': '从 Chrome 版本 142 开始，当您尝试通过 [`langgraph dev`](/langsmith/cli) 将 [LangSmith Studio](/langsmith/studio) 连接到本地开发服务器时，您可能会遇到"Failed to initialize Studio"错误，提示"TypeError: Failed to fetch"。即使 `http://127.0.0.1:2024/docs` 处的 API 服务器成功加载，也会发生这种情况。',
        '**Root Cause:** Chrome 142 fully enforces the Private Network Access (PNA) specification with no fallback, which blocks HTTPS sites (like `https://smith.langchain.com`) from accessing HTTP localhost servers by default.': '**根本原因：** Chrome 142 完全强制执行私有网络访问 (PNA) 规范，没有回退机制，这会阻止 HTTPS 网站（如 `https://smith.langchain.com`）默认访问 HTTP localhost 服务器。',
        '### Symptoms': '### 症状',
        '- Running `langgraph dev` starts the server successfully.': '- 运行 `langgraph dev` 成功启动服务器。',
        '- Navigating to `http://127.0.0.1:2024/docs` shows the API documentation correctly.': '- 导航到 `http://127.0.0.1:2024/docs` 正确显示 API 文档。',
        '- LangSmith Studio at `https://smith.langchain.com` shows: "Failed to initialize Studio - Please verify if the API server is running or accessible from the browser. TypeError: Failed to fetch".': '- `https://smith.langchain.com` 上的 LangSmith Studio 显示："Failed to initialize Studio - Please verify if the API server is running or accessible from the browser. TypeError: Failed to fetch"。',
        "- Browser console shows errors like: `Permission was denied for this request to access the 'unknown' address space`.": "- 浏览器控制台显示错误，例如：`Permission was denied for this request to access the 'unknown' address space`。",
        '### Solution: Allow local network access in Chrome': '### 解决方案：在 Chrome 中允许本地网络访问',
        '1. Open LangSmith Studio at `https://smith.langchain.com` in Chrome.': '1. 在 Chrome 中打开 `https://smith.langchain.com` 上的 LangSmith Studio。',
        '2. Click the **lock icon** (or site information icon) to the left of the address bar.': '2. 点击地址栏左侧的**锁图标**（或网站信息图标）。',
        '3. Look for the **"Local network access"** option in the dropdown.': '3. 在下拉菜单中查找**"本地网络访问"**选项。',
        '4. Change the setting from **"Ask (default)"** or **"Block"** to **"Allow"**.': '4. 将设置从**"询问（默认）"**或**"阻止"**更改为**"允许"**。',
        '5. Reload the page.': '5. 重新加载页面。',
        'Studio should now connect to your local development server successfully.': 'Studio 现在应该能够成功连接到您的本地开发服务器。',
        '### Additional troubleshooting': '### 其他故障排除',
        '**Check for browser extension conflicts**': '**检查浏览器扩展冲突**',
        'Browser extensions (especially Ollama Chrome extension or AI model extensions) can interfere with localhost connections:': '浏览器扩展（尤其是 Ollama Chrome 扩展或 AI 模型扩展）可能会干扰 localhost 连接：',
        '1. Disable all browser extensions temporarily.': '1. 临时禁用所有浏览器扩展。',
        '2. Restart Chrome.': '2. 重启 Chrome。',
        '3. Try connecting to Studio again.': '3. 再次尝试连接到 Studio。',
        '4. If it works, re-enable extensions one by one to identify the culprit.': '4. 如果有效，逐个重新启用扩展以找出问题所在。',
        '**Verify dependencies are up to date**': '**验证依赖项是最新的**',
        '**Clear browser cache and site data**': '**清除浏览器缓存和网站数据**',
        '## Brave connection issues': '## Brave 连接问题',
        'Brave blocks plain-HTTP traffic on localhost when Brave Shields are enabled. When running Studio with `langgraph dev`, you may see "Failed to load assistants" errors.': '当 Brave Shields 启用时，Brave 会阻止 localhost 上的纯 HTTP 流量。当使用 `langgraph dev` 运行 Studio 时，您可能会看到"Failed to load assistants"错误。',
        '### Solution 1: Disable Brave shields': '### 解决方案 1：禁用 Brave shields',
        'Disable Brave Shields for LangSmith using the Brave icon in the URL bar.': '使用 URL 栏中的 Brave 图标为 LangSmith 禁用 Brave Shields。',
        '### Solution 2: Use Cloudflare Tunnel': '### 解决方案 2：使用 Cloudflare Tunnel',
        '## Graph edge issues': '## 图边缘问题',
        'Undefined conditional edges may show unexpected connections in your graph. This is because without proper definition, Studio assumes the conditional edge could access all other nodes. To address this, explicitly define the routing paths using one of these methods:': '未定义的条件边可能在您的图中显示意外的连接。这是因为如果没有正确定义，Studio 会假设条件边可以访问所有其他节点。要解决此问题，请使用以下方法之一明确定义路由路径：',
        '### Solution 1: Path map': '### 解决方案 1：路径映射',
        'Define a mapping between router outputs and target nodes:': '定义路由器输出和目标节点之间的映射：',
        '<a id="python"></a>': '<a id="python"></a>',
        '### Solution 2: Router type definition': '### 解决方案 2：路由器类型定义',
        'Specify possible routing destinations using Python\'s `Literal` type:': '使用 Python 的 `Literal` 类型指定可能的路由目标：',
        '## Experiment troubleshooting in Studio': '## Studio 中的实验故障排除',
        '### **Run experiment** button is disabled': '### **运行实验**按钮被禁用',
        'Check the following:': '检查以下内容：',
        '- **Deployed application**: If your application is deployed on LangSmith, you may need to create a new revision to enable this feature.': '- **已部署的应用程序**：如果您的应用程序部署在 LangSmith 上，您可能需要创建一个新修订版来启用此功能。',
        '- **Local development server**: If you are running your application locally, make sure you have upgraded to the latest version of the `langgraph-cli` (`pip install -U langgraph-cli`). Additionally, ensure you have tracing enabled by setting the `LANGSMITH_API_KEY` in your project\'s `.env` file.': '- **本地开发服务器**：如果您在本地运行应用程序，请确保已升级到最新版本的 `langgraph-cli`（`pip install -U langgraph-cli`）。此外，通过在项目的 `.env` 文件中设置 `LANGSMITH_API_KEY` 来确保已启用追踪。',
        '### Evaluator results are missing': '### 评估器结果缺失',
        'When you run an experiment, any attached evaluators are scheduled for execution in a queue. If you don\'t see results immediately, it likely means they are still pending.': '当您运行实验时，任何附加的评估器都会被安排在队列中执行。如果您没有立即看到结果，可能意味着它们仍在待处理中。',
    },
    'troubleshooting-variable-caching': {
        'Troubleshoot variable caching': '排查变量缓存问题',
        'If you\'re not seeing traces in your tracing project or notice traces logged to the wrong project/workspace, the issue might be due to LangSmith\'s default environment variable caching. This is especially common when running LangSmith within a Jupyter notebook. Follow these steps to diagnose and resolve the issue:': '如果您在追踪项目中没有看到追踪，或者注意到追踪记录到了错误的项目/工作区，问题可能是由于 LangSmith 的默认环境变量缓存。这在使用 Jupyter notebook 运行 LangSmith 时尤其常见。按照以下步骤诊断和解决问题：',
        '## 1. Verify your environment variables': '## 1. 验证您的环境变量',
        'First, check that the environment variables are set correctly by running:': '首先，通过运行以下命令检查环境变量是否正确设置：',
        'If the output does not match what\'s defined in your .env file, it\'s likely due to environment variable caching.': '如果输出与您的 .env 文件中定义的不匹配，可能是由于环境变量缓存造成的。',
        '## 2. Clear the cache': '## 2. 清除缓存',
        'Clear the cached environment variables with the following command:': '使用以下命令清除缓存的环境变量：',
        '## 3. Reload the environment variables': '## 3. 重新加载环境变量',
        'Reload your environment variables from the .env file by executing:': '通过执行以下命令从 .env 文件重新加载环境变量：',
        'After reloading, your environment variables should be set correctly.': '重新加载后，您的环境变量应该正确设置。',
        'If you continue to experience issues, please reach out to us via a shared Slack channel or email support (available for Plus and Enterprise plans), or in the [LangChain Forum](https://forum.langchain.com/).': '如果您继续遇到问题，请通过共享的 Slack 频道或电子邮件支持联系我们（适用于 Plus 和 Enterprise 计划），或在 [LangChain 论坛](https://forum.langchain.com/)中联系我们。',
    },
    'troubleshooting': {
        'Troubleshooting': '故障排除',
        'This guide will walk you through common issues you may encounter when running a self-hosted instance of LangSmith.': '本指南将引导您了解运行自托管 LangSmith 实例时可能遇到的常见问题。',
        'While running LangSmith, you may encounter unexpected 500 errors, slow performance, or other issues. This guide will help you diagnose and resolve these issues.': '在运行 LangSmith 时，您可能会遇到意外的 500 错误、性能缓慢或其他问题。本指南将帮助您诊断和解决这些问题。',
        '## Getting helpful information': '## 获取有用信息',
        'To diagnose and resolve an issue, you will first need to retrieve some relevant information. The following sections explain how to do this for a Kubernetes or a Docker setup, and how to pull helpful browser information.': '要诊断和解决问题，您首先需要检索一些相关信息。以下部分解释如何为 Kubernetes 或 Docker 设置执行此操作，以及如何提取有用的浏览器信息。',
        'Generally, the main services you will want to analyze are the:': '通常，您想要分析的主要服务是：',
        '- `langsmith-backend`: Handles CRUD API requests, business logic, requests from the frontend and SDK, trace preparation for ingestion, and the hub API.': '- `langsmith-backend`：处理 CRUD API 请求、业务逻辑、前端和 SDK 的请求、用于摄取的追踪准备以及 hub API。',
        '- `langsmith-platform-backend`: Handles authentication, run ingestion, and other high-volume tasks.': '- `langsmith-platform-backend`：处理身份验证、运行摄取和其他高容量任务。',
        '- `langsmith-queue`: Handles incoming traces and feedback, asynchronous ingestion and persistence into the datastore, data integrity checks, and retries during database errors or connection issues.': '- `langsmith-queue`：处理传入的追踪和反馈、异步摄取和持久化到数据存储、数据完整性检查以及数据库错误或连接问题时的重试。',
        'For more details on these services, refer to the [self-hosted overview](/langsmith/self-hosted).': '有关这些服务的更多详细信息，请参阅[自托管概述](/langsmith/self-hosted)。',
        '#### Kubernetes': '#### Kubernetes',
        'The first step in troubleshooting is to gather important debugging information about your LangSmith deployment. Service logs, kubernetes events, and resource utilization of containers can help identify the root cause of an issue.': '故障排除的第一步是收集有关 LangSmith 部署的重要调试信息。服务日志、kubernetes 事件和容器资源利用率可以帮助识别问题的根本原因。',
        'You can run our [k8s troubleshooting script](https://github.com/langchain-ai/helm/blob/main/charts/langsmith/scripts/get_k8s_debugging_info.sh) which will pull all of the relevant kubernetes information and output it to a folder for investigation. The script also compresses this folder into a zip file for sharing. Here is an example of how to run this script, assuming your langsmith deployment was brought up in a `langsmith` namespace:': '您可以运行我们的 [k8s 故障排除脚本](https://github.com/langchain-ai/helm/blob/main/charts/langsmith/scripts/get_k8s_debugging_info.sh)，它将提取所有相关的 kubernetes 信息并将其输出到一个文件夹中进行调查。该脚本还将此文件夹压缩成一个 zip 文件以便共享。以下是运行此脚本的示例，假设您的 langsmith 部署是在 `langsmith` 命名空间中启动的：',
        'You can then inspect the contents of the produced folder for any relevant errors or information. If you would like the LangSmith team to assist in debugging, please share this zip file with the team.': '然后，您可以检查生成的文件夹的内容以获取任何相关错误或信息。如果您希望 LangSmith 团队协助调试，请与团队共享此 zip 文件。',
        '#### Docker': '#### Docker',
        'If running on Docker, you can check the logs your deployment by running the following command:': '如果在 Docker 上运行，您可以通过运行以下命令来检查部署的日志：',
        '#### Browser errors': '#### 浏览器错误',
        'If you are experiencing an issue that surfaces as a browser error, it may also be helpful to inspect a HAR file which may include key information. To get the HAR file, you can follow [this guide](https://support.langchain.com/articles/9042697994-how-to-generate-a-har-file-for-troubleshooting) which explains the short process for various browsers.': '如果您遇到的问题表现为浏览器错误，检查可能包含关键信息的 HAR 文件也可能有帮助。要获取 HAR 文件，您可以按照[本指南](https://support.langchain.com/articles/9042697994-how-to-generate-a-har-file-for-troubleshooting)进行操作，该指南说明了各种浏览器的简短过程。',
        'You can then use [Google\'s HAR analyzer](https://toolbox.googleapps.com/apps/har_analyzer/) to investigate. You can also send your HAR file to the LangSmith team to help with debugging.': '然后，您可以使用 [Google 的 HAR 分析器](https://toolbox.googleapps.com/apps/har_analyzer/)进行调查。您也可以将您的 HAR 文件发送给 LangSmith 团队以帮助调试。',
        '## Common issues': '## 常见问题',
        '### *DB::Exception: Cannot reserve 1.00 MiB, not enough space: While executing WaitForAsyncInsert. (NOT\\_ENOUGH\\_SPACE)*': '### *DB::Exception: Cannot reserve 1.00 MiB, not enough space: While executing WaitForAsyncInsert. (NOT\\_ENOUGH\\_SPACE)*',
        'This error occurs when ClickHouse runs out of disk space. You will need to increase the disk space available to ClickHouse.': '当 ClickHouse 磁盘空间不足时会发生此错误。您需要增加 ClickHouse 可用的磁盘空间。',
        '#### Kubernetes': '#### Kubernetes',
        'In Kubernetes, you will need to increase the size of the ClickHouse PVC. To achieve this, you can perform the following steps:': '在 Kubernetes 中，您需要增加 ClickHouse PVC 的大小。为此，您可以执行以下步骤：',
        '1. Get the storage class of the PVC: `kubectl get pvc data-langsmith-clickhouse-0 -n <namespace> -o jsonpath=\'{.spec.storageClassName}\'`': '1. 获取 PVC 的存储类：`kubectl get pvc data-langsmith-clickhouse-0 -n <namespace> -o jsonpath=\'{.spec.storageClassName}\'`',
        '2. Ensure the storage class has AllowVolumeExpansion: true: `kubectl get sc <storage-class-name> -o jsonpath=\'{.allowVolumeExpansion}\'`': '2. 确保存储类允许卷扩展：`kubectl get sc <storage-class-name> -o jsonpath=\'{.allowVolumeExpansion}\'`',
        '3. Edit your pvc to have the new size: `kubectl edit pvc data-langsmith-clickhouse-0 -n <namespace>` or `kubectl patch pvc data-langsmith-clickhouse-0 \'{"spec":{"resources":{"requests":{"storage":"100Gi"}}}}\' -n <namespace>`': '3. 编辑您的 pvc 以使用新大小：`kubectl edit pvc data-langsmith-clickhouse-0 -n <namespace>` 或 `kubectl patch pvc data-langsmith-clickhouse-0 \'{"spec":{"resources":{"requests":{"storage":"100Gi"}}}}\' -n <namespace>`',
        '4. Update your helm chart `langsmith_config.yaml` to new size(e.g `100 Gi`)': '4. 将您的 helm chart `langsmith_config.yaml` 更新为新大小（例如 `100 Gi`）',
        '5. Delete the clickhouse statefulset `kubectl delete statefulset langsmith-clickhouse --cascade=orphan -n <namespace>`': '5. 删除 clickhouse statefulset `kubectl delete statefulset langsmith-clickhouse --cascade=orphan -n <namespace>`',
        '6. Apply helm chart with updated size (You can follow the [upgrade guide](/langsmith/self-host-upgrades))': '6. 应用更新大小后的 helm chart（您可以按照[升级指南](/langsmith/self-host-upgrades)进行操作）',
        '7. Your pvc should now have the new size. Verify by running `kubectl get pvc` and `kubectl exec langsmith-clickhouse-0 -- bash -c "df"`': '7. 您的 pvc 现在应该具有新大小。通过运行 `kubectl get pvc` 和 `kubectl exec langsmith-clickhouse-0 -- bash -c "df"` 进行验证',
        '#### Docker': '#### Docker',
        'In Docker, you will need to increase the size of the ClickHouse volume. To achieve this, you can perform the following steps:': '在 Docker 中，您需要增加 ClickHouse 卷的大小。为此，您可以执行以下步骤：',
        '1. Stop your instance of LangSmith. `docker compose down`': '1. 停止您的 LangSmith 实例。`docker compose down`',
        '2. If using bind mount, you will need to increase the size of the mount point.': '2. 如果使用绑定挂载，您需要增加挂载点的大小。',
        '3. If using a docker `volume`, you will need to allocate more space to the volume/docker.': '3. 如果使用 docker `volume`，您需要为 volume/docker 分配更多空间。',
        '### *error: Dirty database version \'version\'. fix and force version*': '### *error: Dirty database version \'version\'. fix and force version*',
        'This error occurs when the ClickHouse database is in an inconsistent state with our migrations. You will need to reset to an earlier database version and then rerun your upgrade/migrations.': '当 ClickHouse 数据库与我们的迁移处于不一致状态时，会发生此错误。您需要重置到较早的数据库版本，然后重新运行升级/迁移。',
        '#### Kubernetes': '#### Kubernetes',
        '1. Force migration to an earlier version, where version = dirty version - 1.': '1. 强制迁移到较早版本，其中 version = dirty version - 1。',
        '1. Rerun your upgrade/migrations.': '1. 重新运行您的升级/迁移。',
        '#### Docker': '#### Docker',
        '### *413 - request entity too large*': '### *413 - request entity too large*',
        'This error occurs when the request size exceeds the maximum allowed size. You will need to increase the maximum request size in your Nginx configuration.': '当请求大小超过允许的最大大小时，会发生此错误。您需要在 Nginx 配置中增加最大请求大小。',
        '#### Kubernetes': '#### Kubernetes',
        '1. Edit your `langsmith_config.yaml` and increase the `frontend.maxBodySize` [value](https://github.com/langchain-ai/helm/blob/main/charts/langsmith/values.yaml#L519). This might look something like this:': '1. 编辑您的 `langsmith_config.yaml` 并增加 `frontend.maxBodySize` [值](https://github.com/langchain-ai/helm/blob/main/charts/langsmith/values.yaml#L519)。这可能类似于这样：',
        '2. Apply your changes to the cluster.': '2. 将您的更改应用到集群。',
        '### *Details: code: 497, message: default: Not enough privileges. to execute this query, it\'s necessary to have the grant CREATE ROW POLICY ON default.feedbacks\\_rmt*': '### *Details: code: 497, message: default: Not enough privileges. to execute this query, it\'s necessary to have the grant CREATE ROW POLICY ON default.feedbacks\\_rmt*',
        'This error occurs when your user does not have the necessary permissions to create row policies in Clickhouse. When deploying the Docker deployment, you need to copy the `users.xml` file from the github repo as well. This adds the `<access_management>` tag to the `users.xml` file, which allows the user to create row policies. Below is the default `users.xml` file that we expect to be used.': '当您的用户没有在 Clickhouse 中创建行策略的必要权限时，会发生此错误。部署 Docker 部署时，您还需要从 github repo 复制 `users.xml` 文件。这会将 `<access_management>` 标签添加到 `users.xml` 文件中，允许用户创建行策略。以下是我们期望使用的默认 `users.xml` 文件。',
        'In some environments, your mount point may not be writable by the container. In these cases we suggest building a custom image with the `users.xml` file included.': '在某些环境中，您的挂载点可能无法被容器写入。在这些情况下，我们建议使用包含 `users.xml` 文件的自定义镜像进行构建。',
        'Example `Dockerfile`:': '示例 `Dockerfile`：',
        'Then take the following steps:': '然后采取以下步骤：',
        '1. Build your custom image.': '1. 构建您的自定义镜像。',
        '2. Update your `docker-compose.yaml` to use the custom image. Make sure to remove the users.xml mount point.': '2. 更新您的 `docker-compose.yaml` 以使用自定义镜像。确保删除 users.xml 挂载点。',
        '3. Restart your instance of LangSmith.': '3. 重启您的 LangSmith 实例。',
        '### *ClickHouse fails to start up when running a cluster with AquaSec*': '### *运行带有 AquaSec 的集群时 ClickHouse 启动失败*',
        'In some environments, AquaSec may prevent ClickHouse from starting up correctly. This may manifest as the ClickHouse pod not emitting any logs and failing to get marked as ready.': '在某些环境中，AquaSec 可能会阻止 ClickHouse 正确启动。这可能表现为 ClickHouse pod 不发出任何日志并且无法标记为就绪。',
        'Generally this is due to `LD_PRELOAD` being set by AquaSec, which interferes with ClickHouse. To resolve this, you can add the following environment variable to your ClickHouse deployment:': '通常这是由于 AquaSec 设置了 `LD_PRELOAD`，这会干扰 ClickHouse。要解决此问题，您可以将以下环境变量添加到 ClickHouse 部署中：',
        '#### Kubernetes': '#### Kubernetes',
        'Edit your `langsmith_config.yaml` (or corresponding config file) and set the `AQUA_SKIP_LD_PRELOAD` environment variable:': '编辑您的 `langsmith_config.yaml`（或相应的配置文件）并设置 `AQUA_SKIP_LD_PRELOAD` 环境变量：',
        '#### Docker': '#### Docker',
        'Edit your `docker-compose.yaml` and set the `AQUA_SKIP_LD_PRELOAD` environment variable:': '编辑您的 `docker-compose.yaml` 并设置 `AQUA_SKIP_LD_PRELOAD` 环境变量：',
    },
    'upload-existing-experiments': {
        'How to upload experiments run outside of LangSmith with the REST API': '如何使用 REST API 上传在 LangSmith 外部运行的实验',
        'Some users prefer to manage their datasets and run their experiments outside of LangSmith, but want to use the LangSmith UI to view the results. This is supported via our endpoint.': '一些用户更喜欢在 LangSmith 外部管理他们的数据集和运行实验，但想使用 LangSmith UI 来查看结果。我们通过端点支持此功能。',
        'This guide will show you how to upload evals using the REST API, using the `requests` library in Python as an example. However, the same principles apply to any language.': '本指南将向您展示如何使用 REST API 上传评估，以 Python 中的 `requests` 库为例。但是，相同的原则适用于任何语言。',
        '## Request body schema': '## 请求体模式',
        'Uploading an experiment requires specifying the relevant high-level information for your experiment and dataset, along with the individual data for your examples and runs within the experiment. Each object in the `results` represents a "row" in the experiment - a single dataset example, along with an associated run. Note that `dataset_id` and `dataset_name` refer to your dataset identifier in your external system and will be used to group external experiments together in a single dataset. They should not refer to an existing dataset in LangSmith (unless that dataset was created via this endpoint).': '上传实验需要指定实验和数据集的相关高级信息，以及实验中示例和运行的个人数据。`results` 中的每个对象代表实验中的一"行"——一个单独的数据集示例以及相关的运行。请注意，`dataset_id` 和 `dataset_name` 指的是您外部系统中的数据集标识符，用于将外部实验分组到单个数据集中。它们不应引用 LangSmith 中的现有数据集（除非该数据集是通过此端点创建的）。',
        'You may use the following schema to upload experiments to the `/datasets/upload-experiment` endpoint:': '您可以使用以下模式将实验上传到 `/datasets/upload-experiment` 端点：',
        'The response JSON will be a dict with keys `experiment` and `dataset`, each of which is an object that contains relevant information about the experiment and dataset that was created.': '响应 JSON 将是一个带有键 `experiment` 和 `dataset` 的字典，每个都是一个对象，包含关于创建的实验和数据集的相关信息。',
        '## Considerations': '## 注意事项',
        'You may upload multiple experiments to the same dataset by providing the same dataset\\_id or dataset\\_name between multiple calls. Your experiments will be grouped together under a single dataset, and you will be able to [use the comparison view to compare results between experiments](/langsmith/compare-experiment-results).': '您可以通过在多次调用之间提供相同的 dataset\\_id 或 dataset\\_name 将多个实验上传到同一数据集。您的实验将分组在单个数据集下，您将能够[使用比较视图比较实验结果](/langsmith/compare-experiment-results)。',
        'Ensure that the start and end times of your individual rows are all between the start and end time of your experiment.': '确保您各行的开始和结束时间都在实验的开始和结束时间之间。',
        'You must provide either a dataset\\_id or a dataset\\_name. If you only provide an ID and the dataset does not yet exist, we will generate a name for you, and vice versa if you only provide a name.': '您必须提供 dataset\\_id 或 dataset\\_name 之一。如果您只提供 ID 且数据集尚不存在，我们将为您生成一个名称，反之亦然，如果您只提供名称。',
        'You may not upload experiments to a dataset that was not created via this endpoint. Uploading experiments is only supported for externally-managed datasets.': '您不能上传实验到不是通过此端点创建的数据集。上传实验仅支持外部管理的数据集。',
        '## Example request': '## 示例请求',
        'Below is an example of a simple call to the `/datasets/upload-experiment`. This is a basic example that just uses the most important fields as an illustration.': '以下是到 `/datasets/upload-experiment` 的简单调用示例。这是一个基本示例，仅使用最重要的字段作为说明。',
        'Below is the response received:': '以下是收到的响应：',
        'Note that the latency and feedback stats in the experiment results are null because the runs haven\'t had a chance to be persisted yet, which may take a few seconds. If you save the experiment id and query again in a few seconds, you will see all the stats (although tokens/cost will still be null, because we don\'t ask for this information in the request body).': '请注意，实验结果中的延迟和反馈统计为 null，因为运行还没有机会被持久化，这可能需要几秒钟。如果您保存实验 ID 并在几秒钟后再次查询，您将看到所有统计信息（尽管令牌/成本仍将为 null，因为我们不在请求体中询问此信息）。',
        '## View the experiment in the UI': '## 在 UI 中查看实验',
        'Now, login to the UI and click on your newly-created dataset! You should see a single experiment: ![Uploaded experiments table](/langsmith/images/uploaded-dataset.png)': '现在，登录 UI 并点击您新创建的数据集！您应该看到一个实验：![上传的实验表](/langsmith/images/uploaded-dataset.png)',
        'Your examples will have been uploaded: ![Uploaded examples](/langsmith/images/uploaded-dataset-examples.png)': '您的示例已被上传：![上传的示例](/langsmith/images/uploaded-dataset-examples.png)',
        'Clicking on your experiment will bring you to the comparison view: ![Uploaded experiment comparison view](/langsmith/images/uploaded-experiment.png)': '点击您的实验将带您进入比较视图：![上传的实验比较视图](/langsmith/images/uploaded-experiment.png)',
        'As you upload more experiments to your dataset, you will be able to compare the results and easily identify regressions in the comparison view.': '随着您将更多实验上传到数据集，您将能够比较结果并在比较视图中轻松识别回归。',
    },
}

files_to_translate_batch4 = [
    ('src/langsmith/test-react-agent-pytest.mdx', 'docs_zh/langsmith/test-react-agent-pytest.mdx', 'test-react-agent-pytest'),
    ('src/langsmith/trace-with-strands-agents.mdx', 'docs_zh/langsmith/trace-with-strands-agents.mdx', 'trace-with-strands-agents'),
    ('src/langsmith/trace-with-temporal.mdx', 'docs_zh/langsmith/trace-with-temporal.mdx', 'trace-with-temporal'),
    ('src/langsmith/trace-with-vercel-ai-sdk.mdx', 'docs_zh/langsmith/trace-with-vercel-ai-sdk.mdx', 'trace-with-vercel-ai-sdk'),
    ('src/langsmith/trace-without-env-vars.mdx', 'docs_zh/langsmith/trace-without-env-vars.mdx', 'trace-without-env-vars'),
    ('src/langsmith/trajectory-evals.mdx', 'docs_zh/langsmith/trajectory-evals.mdx', 'trajectory-evals'),
    ('src/langsmith/troubleshooting-studio.mdx', 'docs_zh/langsmith/troubleshooting-studio.mdx', 'troubleshooting-studio'),
    ('src/langsmith/troubleshooting-variable-caching.mdx', 'docs_zh/langsmith/troubleshooting-variable-caching.mdx', 'troubleshooting-variable-caching'),
    ('src/langsmith/troubleshooting.mdx', 'docs_zh/langsmith/troubleshooting.mdx', 'troubleshooting'),
    ('src/langsmith/upload-existing-experiments.mdx', 'docs_zh/langsmith/upload-existing-experiments.mdx', 'upload-existing-experiments'),
]

if __name__ == '__main__':
    count = 0
    for src, dst, key in files_to_translate_batch4:
        if os.path.exists(dst):
            print(f'Skipping existing: {dst}')
            continue
        if key in translations_batch4:
            translate_file(src, dst, translations_batch4[key])
            count += 1
    print(f'Translated {count} files')