#!/usr/bin/env python
import os
import sys

def translate_file(src_path, dst_path, translations):
    with open(src_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for eng, chn in translations.items():
        content = content.replace(eng, chn)

    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Translated: {src_path} -> {dst_path}')

# Translation mappings for batch 3
translations_batch3 = {
    'trace-with-n8n': {
        'Trace n8n workflows': '追踪 n8n 工作流',
        '[n8n](https://n8n.io/) is a workflow automation platform that includes advanced AI capabilities built on LangChain. You can connect your n8n instance to LangSmith to record and monitor AI workflow runs.': '[n8n](https://n8n.io/) 是一个工作流自动化平台，包含基于 LangChain 构建的高级 AI 功能。您可以将您的 n8n 实例连接到 LangSmith 以记录和监控 AI 工作流运行。',
        'LangSmith tracing is available for **self-hosted n8n instances** only.': 'LangSmith 追踪仅适用于**自托管 n8n 实例**。',
        '## Prerequisites': '## 前置条件',
        '- A [LangSmith account](https://smith.langchain.com/) and [API key](/langsmith/create-account-api-key)': '- 一个 [LangSmith 账户](https://smith.langchain.com/)和 [API 密钥](/langsmith/create-account-api-key)',
        '- A self-hosted n8n instance': '- 一个自托管的 n8n 实例',
        '## Set up tracing': '## 设置追踪',
        '1. Set the following environment variables in the environment where you host your n8n instance, in the same way as the rest of your [n8n configuration](https://docs.n8n.io/hosting/configuration/configuration-methods/).': '1. 在托管 n8n 实例的环境中设置以下环境变量，方式与您的 [n8n 配置](https://docs.n8n.io/hosting/configuration/configuration-methods/)相同。',
        'Required environment variables:': '必需的环境变量：',
        '- `LANGCHAIN_TRACING_V2` — Set to `true` to enable tracing.': '- `LANGCHAIN_TRACING_V2` — 设置为 `true` 以启用追踪。',
        '- `LANGCHAIN_API_KEY` — Your LangSmith API key.': '- `LANGCHAIN_API_KEY` — 您的 LangSmith API 密钥。',
        'Optional environment variables:': '可选的环境变量：',
        '- `LANGCHAIN_ENDPOINT` — LangSmith API endpoint. Defaults to `https://api.smith.langchain.com`. Set this if using self-hosted LangSmith, the EU region (`https://eu.api.smith.langchain.com`), or AWS-hosted US SaaS (`https://aws.api.smith.langchain.com`).': '- `LANGCHAIN_ENDPOINT` — LangSmith API 端点。默认为 `https://api.smith.langchain.com`。如果使用自托管 LangSmith、欧盟区域（`https://eu.api.smith.langchain.com`）或 AWS 托管的美国 SaaS（`https://aws.api.smith.langchain.com`），请设置此项。',
        '- `LANGCHAIN_PROJECT` — Project name for traces. Defaults to `"default"`.': '- `LANGCHAIN_PROJECT` — 追踪的项目名称。默认为 `"default"`。',
        '- `LANGCHAIN_CALLBACKS_BACKGROUND` — Set to `true` for asynchronous trace upload (default), or `false` for synchronous uploads. (default: `true`)': '- `LANGCHAIN_CALLBACKS_BACKGROUND` — 设置为 `true` 以进行异步追踪上传（默认），或 `false` 进行同步上传。（默认：`true`）',
        '1. Restart your n8n instance for the environment variables to take effect.': '1. 重启 n8n 实例以使环境变量生效。',
        '## View traces in LangSmith': '## 在 LangSmith 中查看追踪',
        'After running an AI workflow:': '运行 AI 工作流后：',
        '1. Open [LangSmith](https://smith.langchain.com/).': '1. 打开 [LangSmith](https://smith.langchain.com/)。',
        '1. Select your project. If you just created your account, the `"default"` project appears after the first trace is sent.': '1. 选择您的项目。如果您刚刚创建了账户，则在发送第一个追踪后会出现 `"default"` 项目。',
        '1. Locate the trace corresponding to your workflow execution.': '1. 找到与您的工作流执行对应的追踪。',
        '## Additional resources': '## 其他资源',
        '- [n8n LangSmith integration guide](https://docs.n8n.io/advanced-ai/langchain/langsmith/)': '- [n8n LangSmith 集成指南](https://docs.n8n.io/advanced-ai/langchain/langsmith/)',
        '- [n8n Advanced AI documentation](https://docs.n8n.io/advanced-ai/)': '- [n8n 高级 AI 文档](https://docs.n8n.io/advanced-ai/)',
    },
    'trace-with-openai-agents-sdk': {
        'Trace OpenAI Agents SDK applications': '追踪 OpenAI Agents SDK 应用程序',
        'The OpenAI Agents SDK lets you build agentic applications powered by OpenAI models.': 'OpenAI Agents SDK 让您构建由 OpenAI 模型驱动的智能体应用程序。',
        'Use LangSmith to trace OpenAI Agents SDK runs, including agent steps, model calls, tool calls, and handoffs.': '使用 LangSmith 追踪 OpenAI Agents SDK 运行，包括智能体步骤、模型调用、工具调用和移交。',
    },
    'trace-with-opentelemetry': {
        'Trace with OpenTelemetry': '使用 OpenTelemetry 追踪',
        'LangSmith supports OpenTelemetry-based tracing, allowing you to send traces from any OpenTelemetry-compatible application. This guide covers both automatic instrumentation for LangChain applications and manual instrumentation for other frameworks.': 'LangSmith 支持基于 OpenTelemetry 的追踪，允许您从任何 OpenTelemetry 兼容应用程序发送追踪。本指南涵盖 LangChain 应用程序的自动检测和其他框架的手动检测。',
        'Learn how to trace your LLM applications using OpenTelemetry with LangSmith.': '了解如何使用 OpenTelemetry 和 LangSmith 追踪您的大型语言模型应用程序。',
        'Update the LangSmith URL appropriately for self-hosted installations or regional SaaS in the requests below: EU (GCP) uses `eu.api.smith.langchain.com`; AWS-hosted US SaaS uses `aws.api.smith.langchain.com`.': '在下面的请求中为自托管安装或区域 SaaS 适当更新 LangSmith URL：欧盟（GCP）使用 `eu.api.smith.langchain.com`；AWS 托管的美国 SaaS 使用 `aws.api.smith.langchain.com`。',
        '## Trace a LangChain application': '## 追踪 LangChain 应用程序',
        'If you\'re using LangChain or LangGraph, use the built-in integration to trace your application:': '如果您使用 LangChain 或 LangGraph，请使用内置集成来追踪您的应用程序：',
        '1. Install the LangSmith package with OpenTelemetry support:': '1. 安装带有 OpenTelemetry 支持的 LangSmith 包：',
        'Requires Python SDK version `langsmith>=0.3.18`. We recommend `langsmith>=0.4.25` to benefit from important OpenTelemetry fixes.': '需要 Python SDK 版本 `langsmith>=0.3.18`。我们建议使用 `langsmith>=0.4.25` 以从重要的 OpenTelemetry 修复中受益。',
        '2. In your LangChain/LangGraph App, enable the OpenTelemetry integration by setting the `LANGSMITH_OTEL_ENABLED` environment variable:': '2. 在您的 LangChain/LangGraph 应用程序中，通过设置 `LANGSMITH_OTEL_ENABLED` 环境变量来启用 OpenTelemetry 集成：',
        '3. Create a LangChain application with tracing. For example:': '3. 创建一个带有追踪的 LangChain 应用程序。例如：',
        '4. View the traces in your LangSmith dashboard ([example](https://smith.langchain.com/public/a762af6c-b67d-4f22-90a0-728df16baeba/r)) once your application runs.': '4. 应用程序运行后，在您的 LangSmith 仪表板中查看追踪（[示例](https://smith.langchain.com/public/a762af6c-b67d-4f22-90a0-728df16baeba/r)）。',
        '## Trace a non-LangChain application': '## 追踪非 LangChain 应用程序',
        'For non-LangChain applications or custom instrumentation, you can trace your application in LangSmith with a standard OpenTelemetry client. (We recommend **langsmith ≥ 0.4.25**.)': '对于非 LangChain 应用程序或自定义检测，您可以使用标准 OpenTelemetry 客户端在 LangSmith 中追踪您的应用程序。（我们建议 **langsmith ≥ 0.4.25**。）',
        '1. Install the OpenTelemetry SDK, OpenTelemetry exporter packages, as well as the OpenAI package:': '1. 安装 OpenTelemetry SDK、OpenTelemetry 导出器包以及 OpenAI 包：',
        '2. Setup environment variables for the endpoint, substitute your specific values:': '2. 设置端点的环境变量，替换您的特定值：',
        'Depending on how your otel exporter is configured, you may need to append `/v1/traces` to the endpoint if you are only sending traces.': '根据您的 otel 导出器的配置，如果您只发送追踪，可能需要在端点附加 `/v1/traces`。',
        'If you\'re self-hosting LangSmith, replace the base endpoint with your LangSmith api endpoint and append `/api/v1`. For example: `OTEL_EXPORTER_OTLP_ENDPOINT=https://ai-company.com/api/v1/otel`': '如果您自托管 LangSmith，请将基本端点替换为您的 LangSmith api 端点并附加 `/api/v1`。例如：`OTEL_EXPORTER_OTLP_ENDPOINT=https://ai-company.com/api/v1/otel`',
        'Optional: Specify a custom project name other than "default":': '可选：指定除"default"以外的自定义项目名称：',
        '3. Log a trace.': '3. 记录追踪。',
        'This code sets up an OTEL tracer and exporter that will send traces to LangSmith. It then calls OpenAI and sends the required OpenTelemetry attributes.': '此代码设置一个 OTEL 追踪器和导出器，它将向 LangSmith 发送追踪。然后调用 OpenAI 并发送所需的 OpenTelemetry 属性。',
        '4. View the trace in your LangSmith dashboard ([example](https://smith.langchain.com/public/4f2890b1-f105-44aa-a6cf-c777dcc27a37/r)).': '4. 在您的 LangSmith 仪表板中查看追踪（[示例](https://smith.langchain.com/public/4f2890b1-f105-44aa-a6cf-c777dcc27a37/r)）。',
        '## Send traces to an alternate provider': '## 向备用提供商发送追踪',
        'While LangSmith is the default destination for OpenTelemetry traces, you can also configure OpenTelemetry to send traces to other observability platforms.': '虽然 LangSmith 是 OpenTelemetry 追踪的默认目标，但您也可以将 OpenTelemetry 配置为向其他可观测性平台发送追踪。',
        'Available in LangSmith Python SDK **≥ 0.4.1**. We recommend **≥ 0.4.25** for fixes that improve OTEL export and hybrid fan-out stability.': '适用于 LangSmith Python SDK **≥ 0.4.1**。我们建议使用 **≥ 0.4.25** 以获取改进 OTEL 导出和混合扇出稳定性的修复。',
        '### Use environment variables for global configuration': '### 使用环境变量进行全局配置',
        'By default, the LangSmith OpenTelemetry exporter will send data to the LangSmith API OTEL endpoint, but this can be customized by setting standard OTEL environment variables:': '默认情况下，LangSmith OpenTelemetry 导出器会将数据发送到 LangSmith API OTEL 端点，但这可以通过设置标准 OTEL 环境变量进行自定义：',
        'LangSmith uses the HTTP trace exporter by default. If you\'d like to use your own tracing provider, you can either:': 'LangSmith 默认使用 HTTP 追踪导出器。如果您想使用自己的追踪提供商，可以：',
        '1. Set the OTEL environment variables as shown above, or': '1. 如上所示设置 OTEL 环境变量，或',
        '2. Set a global trace provider before initializing LangChain components, which LangSmith will detect and use instead of creating its own.': '2. 在初始化 LangChain 组件之前设置全局追踪提供商，LangSmith 将检测并使用它，而不是创建自己的。',
        '### Configure alternate OTLP endpoints': '### 配置备用 OTLP 端点',
        'To send traces to a different provider, configure the OTLP exporter with your provider\'s endpoint:': '要向不同的提供商发送追踪，请使用您的提供商的端点配置 OTLP 导出器：',
        'Hybrid tracing is available in version **≥ 0.4.1**. To send traces **only** to your OTEL endpoint, set:': '混合追踪在版本 **≥ 0.4.1** 中可用。要**仅**向您的 OTEL 端点发送追踪，请设置：',
        '## Supported OpenTelemetry attribute and event mapping': '## 支持的 OpenTelemetry 属性和事件映射',
        'When sending traces to LangSmith via OpenTelemetry, the following attributes are mapped to LangSmith fields:': '通过 OpenTelemetry 将追踪发送到 LangSmith 时，以下属性映射到 LangSmith 字段：',
        '### Core LangSmith attributes': '### 核心 LangSmith 属性',
        '### GenAI standard attributes': '### GenAI 标准属性',
        '### GenAI request parameters': '### GenAI 请求参数',
        '### GenAI usage metrics': '### GenAI 使用指标',
        '### TraceLoop attributes': '### TraceLoop 属性',
        '### OpenInference attributes': '### OpenInference 属性',
        '### LLM attributes': '### 大型语言模型属性',
        '### Prompt template attributes': '### 提示词模板属性',
        '### Retriever attributes': '### 检索器属性',
        '### Tool attributes': '### 工具属性',
        '### Logfire attributes': '### Logfire 属性',
        '### OpenTelemetry event mapping': '### OpenTelemetry 事件映射',
        '## Implementation examples': '## 实现示例',
        '### Trace using the LangSmith SDK': '### 使用 LangSmith SDK 追踪',
        'Use the LangSmith SDK\'s OpenTelemetry helper to configure export. The following example [traces a Google ADK agent](/langsmith/trace-with-google-adk):': '使用 LangSmith SDK 的 OpenTelemetry 辅助工具配置导出。以下示例[追踪 Google ADK 智能体](/langsmith/trace-with-google-adk)：',
        'You do not need to set OTEL environment variables or exporters. `configure()` wires them for LangSmith automatically; instrumentors (like `GoogleADKInstrumentor`) create the spans.': '您不需要设置 OTEL 环境变量或导出器。`configure()` 自动为 LangSmith 连接它们；检测器（如 `GoogleADKInstrumentor`）创建跨度。',
        'Here is an [example](https://smith.langchain.com/public/d6d47eeb-511e-4fda-ad17-2caa7bd7150b/r) of what the resulting trace looks like in LangSmith.': '这是[示例](https://smith.langchain.com/public/d6d47eeb-511e-4fda-ad17-2caa7bd7150b/r)，展示在 LangSmith 中 resulting 追踪的样子。',
        '### Add an attachment to a trace': '### 向追踪添加附件',
        'LangSmith supports [attaching files to traces](/langsmith/upload-files-with-traces). This is useful when building an agent with multimodal inputs or outputs. Attachments are also supported when tracing with OpenTelemetry.': 'LangSmith 支持[向追踪附加文件](/langsmith/upload-files-with-traces)。这在构建具有多模态输入或输出的智能体时很有用。使用 OpenTelemetry 追踪时也支持附件。',
        '## Advanced configuration': '## 高级配置',
        '### Use OpenTelemetry collector for fan-out': '### 使用 OpenTelemetry 收集器进行扇出',
        'Use `LANGSMITH_OTEL_ENABLED=true` when you need OTEL fanout. Configure your application to emit OTEL spans once, then use an OpenTelemetry Collector to route them to LangSmith and any additional observability backends.': '当您需要 OTEL 扇出时，使用 `LANGSMITH_OTEL_ENABLED=true`。将您的应用程序配置为发出一次 OTEL 跨度，然后使用 OpenTelemetry Collector 将其路由到 LangSmith 和任何其他可观测性后端。',
        'Use this approach when you are tracing applications and want multi-destination routing. If you are operating LangSmith platform infrastructure telemetry (logs, metrics, traces from self-hosted LangSmith services on Kubernetes), use the [Configure your collector for LangSmith telemetry](/langsmith/langsmith-collector) guide instead.': '当您追踪应用程序并想要多目标路由时，使用此方法。如果您操作 LangSmith 平台基础设施遥测（来自 Kubernetes 上自托管 LangSmith 服务的日志、指标、追踪），请改用[为 LangSmith 遥测配置您的收集器](/langsmith/langsmith-collector)指南。',
        'For more advanced scenarios, you can use the OpenTelemetry Collector to fan out your telemetry data to multiple destinations. This is a more scalable approach than configuring multiple exporters in your application code.': '对于更高级的场景，您可以使用 OpenTelemetry Collector 将您的遥测数据扇出到多个目标。这比在应用程序代码中配置多个导出器更具可扩展性。',
        '1. [Install the OpenTelemetry Collector](https://opentelemetry.io/docs/collector/getting-started/) for your environment.': '1. 为您的环境[安装 OpenTelemetry Collector](https://opentelemetry.io/docs/collector/getting-started/)。',
        '2. Create a configuration file (e.g., `otel-collector-config.yaml`) that exports to multiple destinations:': '2. 创建一个配置（例如 `otel-collector-config.yaml`），导出到多个目标：',
        '3. Configure your application to send to the collector:': '3. 将您的应用程序配置为发送到收集器：',
        'This approach offers several advantages:': '此方法提供多项优势：',
        'This approach offers several advantages:': '此方法提供多项优势：',
        '* Centralized configuration for all your telemetry destinations': '* 集中配置所有遥测目标',
        '* Reduced overhead in your application code': '* 减少应用程序代码中的开销',
        '* Better scalability and resilience': '* 更好的可扩展性和弹性',
        '* Ability to add or remove destinations without changing application code': '* 能够在不更改应用程序代码的情况下添加或删除目标',
        '### Distributed tracing with LangChain and OpenTelemetry': '### 使用 LangChain 和 OpenTelemetry 进行分布式追踪',
        'Distributed tracing is essential when your LLM application spans multiple services or processes. OpenTelemetry\'s context propagation capabilities ensure that traces remain connected across service boundaries.': '当您的大型语言模型应用程序跨多个服务或进程时，分布式追踪至关重要。OpenTelemetry 的上下文传播功能确保追踪在服务边界之间保持连接。',
        '#### Context propagation in distributed tracing': '#### 分布式追踪中的上下文传播',
        'In distributed systems, context propagation passes trace metadata between services so that related spans are linked to the same trace:': '在分布式系统中，上下文传播在服务之间传递追踪元数据，以便相关跨度链接到同一追踪：',
        '#### Set up distributed tracing with LangChain': '#### 使用 LangChain 设置分布式追踪',
        'To enable distributed tracing across multiple services:': '要跨多个服务启用分布式追踪：',
    },
    'trace-with-pipecat': {
        'Trace Pipecat applications': '追踪 Pipecat 应用程序',
        'LangSmith can capture traces generated by [Pipecat](https://pipecat.ai/) using OpenTelemetry instrumentation. This guide shows you how to automatically capture traces from your Pipecat voice AI pipelines and send them to LangSmith for monitoring and analysis.': 'LangSmith 可以使用 OpenTelemetry 检测来捕获由 [Pipecat](https://pipecat.ai/) 生成的追踪。本指南向您展示如何自动捕获 Pipecat 语音 AI 管道中的追踪，并将其发送到 LangSmith 进行监控和分析。',
        'For a complete implementation, see the [demo repository](https://github.com/langchain-ai/voice-agents-tracing).': '有关完整实现，请参阅[演示仓库](https://github.com/langchain-ai/voice-agents-tracing)。',
        '## Installation': '## 安装',
        'Install the required packages:': '安装所需的包：',
        'If you plan to use the advanced audio recording features, also install: `pip install scipy numpy`': '如果您计划使用高级音频录制功能，还请安装：`pip install scipy numpy`',
        '## Quickstart tutorial': '## 快速入门教程',
        'Follow this step-by-step tutorial to create a voice AI agent with Pipecat and LangSmith tracing. You\'ll build a complete working example by copying and pasting code snippets.': '按照此分步教程创建具有 Pipecat 和 LangSmith 追踪的语音 AI 智能体。您将通过复制和粘贴代码片段来构建完整的工作示例。',
        '### Step 1: Set up your environment': '### 步骤 1：设置您的环境',
        'Create a `.env` file in your project directory:': '在您的项目目录中创建一个 `.env` 文件：',
        '### Step 2: Download the span processor': '### 步骤 2：下载跨度处理器',
        'Add the [custom span processor file](https://github.com/langchain-ai/voice-agents-tracing/blob/main/pipecat/langsmith_processor.py) that enables LangSmith tracing. Save it as `langsmith_processor.py` in your project directory.': '添加启用 LangSmith 追踪的[自定义跨度处理器文件](https://github.com/langchain-ai/voice-agents-tracing/blob/main/pipecat/langsmith_processor.py)。将其保存为 `langsmith_processor.py` 在您的项目目录中。',
        'The span processor enriches Pipecat\'s OpenTelemetry spans with LangSmith-compatible attributes so your traces display properly in LangSmith.': '跨度处理器使用 LangSmith 兼容属性丰富 Pipecat 的 OpenTelemetry 跨度，以便您的追踪在 LangSmith 中正确显示。',
        '**Key functions:**': '**关键功能：**',
        '- Converts Pipecat span types (stt, llm, tts, turn, conversation) to LangSmith format.': '- 将 Pipecat 跨度类型（stt、llm、tts、turn、conversation）转换为 LangSmith 格式。',
        '- Adds `gen_ai.prompt.*` and `gen_ai.completion.*` attributes for message visualization.': '- 添加 `gen_ai.prompt.*` 和 `gen_ai.completion.*` 属性以进行消息可视化。',
        '- Tracks and aggregates conversation messages across turns.': '- 跨轮次追踪和聚合对话消息。',
        '- Handles audio file attachments (for advanced usage).': '- 处理音频文件附件（用于高级用法）。',
        'The processor automatically activates when you import it in your code.': '当您在代码中导入它时，处理器会自动激活。',
        '### Step 3: Create your voice agent file': '### 步骤 3：创建您的语音智能体文件',
        'Create a new file called `agent.py` and add the following code. We\'ll build it section by section so you can copy and paste each part.': '创建一个名为 `agent.py` 的新文件并添加以下代码。我们将逐节构建它，以便您可以复制和粘贴每个部分。',
        '#### Part 1: Import dependencies': '#### 第 1 部分：导入依赖项',
        '#### Part 2: Define the main function': '#### 第 2 部分：定义主函数',
        '#### Part 3: Add the entry point': '#### 第 3 部分：添加入口点',
        '### Step 4: Run your agent': '### 步骤 4：运行您的智能体',
        'Run your voice agent:': '运行您的语音智能体：',
        'Speak to the agent through your microphone. All traces will automatically appear in LangSmith. Here is an example of a trace in LangSmith: [LangSmith trace with Pipecat](https://smith.langchain.com/public/07721f41-cd27-413e-bc79-90bd23b6807d/r).': '通过麦克风对智能体讲话。所有追踪将自动出现在 LangSmith 中。这是 LangSmith 中追踪的示例：[带有 Pipecat 的 LangSmith 追踪](https://smith.langchain.com/public/07721f41-cd27-413e-bc79-90bd23b6807d/r)。',
        'View the complete [agent.py code](https://github.com/langchain-ai/voice-agents-tracing/blob/main/pipecat/agent.py).': '查看完整的 [agent.py 代码](https://github.com/langchain-ai/voice-agents-tracing/blob/main/pipecat/agent.py)。',
        '## Advanced usage': '## 高级用法',
        '### Custom metadata and tags': '### 自定义元数据和标签',
        'You can add custom metadata to your traces using span attributes:': '您可以使用跨度属性向追踪添加自定义元数据：',
        '### Recording and attaching audio to traces': '### 录制并附加音频到追踪',
        'You can capture audio from your voice conversations and attach it to traces in LangSmith. This allows you to listen to the actual audio alongside the transcriptions and AI responses.': '您可以从语音对话中捕获音频并将其附加到 LangSmith 中的追踪。这允许您在转录和 AI 响应的同时收听实际音频。',
        '#### Full conversation recording': '#### 完整对话录制',
        'See the [AudioRecorder implementation](https://github.com/langchain-ai/voice-agents-tracing/blob/main/pipecat/audio_recorder.py) which handles sample rate mismatches between input (microphone) and output (TTS) audio.': '请参阅 [AudioRecorder 实现](https://github.com/langchain-ai/voice-agents-tracing/blob/main/pipecat/audio_recorder.py)，它处理输入（麦克风）和输出（TTS）音频之间的采样率不匹配。',
        'Capture all audio from start to finish and attach it to the conversation span:': '从头到尾捕获所有音频并将其附加到对话跨度：',
        '#### Per-turn recording': '#### 每轮录制',
        'See the [TurnAudioRecorder implementation](https://github.com/langchain-ai/voice-agents-tracing/blob/main/pipecat/turn_audio_recorder.py) which captures user speech and AI responses separately for each turn.': '请参阅 [TurnAudioRecorder 实现](https://github.com/langchain-ai/voice-agents-tracing/blob/main/pipecat/turn_audio_recorder.py)，它为每轮单独捕获用户语音和 AI 响应。',
        'Capture separate audio snippets for each conversational turn, with user speech and AI responses saved as individual files:': '为每个对话轮次捕获单独的音频片段，用户语音和 AI 响应保存为单独的文件：',
        '## Troubleshooting': '## 故障排除',
        '### Spans not appearing in LangSmith': '### 追踪未出现在 LangSmith 中',
        'If traces aren\'t showing up in LangSmith:': '如果追踪未显示在 LangSmith 中：',
        '1. **Verify environment variables**: Ensure `OTEL_EXPORTER_OTLP_ENDPOINT` and `OTEL_EXPORTER_OTLP_HEADERS` are set correctly in your `.env` file.': '1. **验证环境变量**：确保在您的 `.env` 文件中正确设置了 `OTEL_EXPORTER_OTLP_ENDPOINT` 和 `OTEL_EXPORTER_OTLP_HEADERS`。',
        '2. **Check API key**: Confirm your LangSmith API key has write permissions.': '2. **检查 API 密钥**：确认您的 LangSmith API 密钥具有写权限。',
        '3. **Verify import**: Make sure you\'re importing `span_processor` from `langsmith_processor.py`.': '3. **验证导入**：确保您从 `langsmith_processor.py` 导入 `span_processor`。',
        '4. **Check .env loading**: Ensure `load_dotenv()` is called before importing Pipecat components.': '4. **检查 .env 加载**：确保在导入 Pipecat 组件之前调用 `load_dotenv()`。',
        '### Messages not showing correctly': '### 消息未正确显示',
        'If conversation messages aren\'t displaying properly:': '如果对话消息未正确显示：',
        '1. **Check span processor**: Verify `langsmith_processor.py` is in your project directory and imported correctly.': '1. **检查跨度处理器**：验证 `langsmith_processor.py` 在您的项目目录中并正确导入。',
        '2. **Verify conversation ID**: Ensure you\'re setting a unique `conversation_id` in `PipelineTask`.': '2. **验证对话 ID**：确保您在 `PipelineTask` 中设置唯一的 `conversation_id`。',
        '3. **Enable turn tracking**: Make sure `enable_turn_tracking=True` is set in `PipelineTask`.': '3. **启用轮次追踪**：确保在 `PipelineTask` 中设置 `enable_turn_tracking=True`。',
        '### Audio not working': '### 音频不工作',
        'If your microphone or speakers aren\'t working:': '如果您的麦克风或扬声器不工作：',
        '1. **Check permissions**: Ensure your terminal/IDE has microphone access.': '1. **检查权限**：确保您的终端/IDE 有麦克风访问权限。',
        '2. **Test audio devices**: Verify your microphone and speakers work in other applications.': '2. **测试音频设备**：验证您的麦克风和扬声器在其他应用程序中工作。',
        '3. **VAD settings**: Try adjusting `SileroVADAnalyzer()` settings if speech isn\'t being detected.': '3. **VAD 设置**：如果未检测到语音，请尝试调整 `SileroVADAnalyzer()` 设置。',
        '4. **Check services**: Ensure OpenAI API key is valid and has access to Whisper and TTS.': '4. **检查服务**：确保 OpenAI API 密钥有效并可访问 Whisper 和 TTS。',
        '### Import errors': '### 导入错误',
        'If you\'re getting import errors:': '如果您遇到导入错误：',
        '1. **Install dependencies**: Run `pip install langsmith "pipecat-ai[whisper,openai,local]" opentelemetry-exporter-otlp python-dotenv`.': '1. **安装依赖**：运行 `pip install langsmith "pipecat-ai[whisper,openai,local]" opentelemetry-exporter-otlp python-dotenv`。',
        '2. **Check Python version**: Ensure you\'re using Python 3.9 or higher.': '2. **检查 Python 版本**：确保您使用的是 Python 3.9 或更高版本。',
        '3. **Verify langsmith_processor**: Make sure `langsmith_processor.py` is downloaded and in the same directory as your `agent.py`.': '3. **验证 langsmith_processor**：确保 `langsmith_processor.py` 已下载并在与您的 `agent.py` 相同的目录中。',
        '### Performance issues': '### 性能问题',
        'If responses are slow:': '如果响应缓慢：',
        '1. **Use faster models**: Switch to `gpt-5.4-mini` for the LLM (already in the tutorial).': '1. **使用更快的模型**：为大型语言模型切换到 `gpt-5.4-mini`（已经在教程中）。',
        '2. **Check network**: Ensure stable internet connection for API calls.': '2. **检查网络**：确保 API 调用的稳定互联网连接。',
        '3. **Local STT**: Consider using local Whisper instead of API-based services.': '3. **本地 STT**：考虑使用本地 Whisper 而不是基于 API 的服务。',
        '### Advanced: Audio recording troubleshooting': '### 高级：音频录制故障排除',
        'For issues with the advanced audio recording features, see the [complete demo documentation](https://github.com/langchain-ai/voice-agents-tracing).': '有关高级音频录制功能的问题，请参阅[完整演示文档](https://github.com/langchain-ai/voice-agents-tracing)。',
    },
    'trace-with-pydantic-ai': {
        'Trace PydanticAI applications': '追踪 PydanticAI 应用程序',
        'LangSmith can capture traces generated by PydanticAI using its built-in OpenTelemetry instrumentation. This guide shows you how to automatically capture traces from your PydanticAI agents and send them to LangSmith for monitoring and analysis.': 'LangSmith 可以使用其内置的 OpenTelemetry 检测来捕获 PydanticAI 生成的追踪。本指南向您展示如何自动捕获 PydanticAI 智能体中的追踪，并将其发送到 LangSmith 进行监控和分析。',
        '## Installation': '## 安装',
        'Install the required packages:': '安装所需的包：',
        'Requires LangSmith Python SDK version `langsmith>=0.4.26` for optimal OpenTelemetry support.': '需要 LangSmith Python SDK 版本 `langsmith>=0.4.26` 以获得最佳 OpenTelemetry 支持。',
        '## Setup': '## 设置',
        '### 1. Configure environment variables': '### 1. 配置环境变量',
        'Set your [API keys](/langsmith/create-account-api-key) and project name:': '设置您的 [API 密钥](/langsmith/create-account-api-key) 和项目名称：',
        '### 2. Configure OpenTelemetry integration': '### 2. 配置 OpenTelemetry 集成',
        'In your PydanticAI application, configure the LangSmith OpenTelemetry integration:': '在您的 PydanticAI 应用程序中，配置 LangSmith OpenTelemetry 集成：',
        'You do not need to set any OpenTelemetry environment variables or configure exporters manually—`configure()` handles everything automatically.': '您不需要设置任何 OpenTelemetry 环境变量或手动配置导出器——`configure()` 自动处理一切。',
        '### 3. Create and run your PydanticAI agent': '### 3. 创建并运行您的 PydanticAI 智能体',
        'Once configured, your PydanticAI agents will automatically send traces to LangSmith:': '配置完成后，您的 PydanticAI 智能体将自动向 LangSmith 发送追踪：',
        '## Advanced usage': '## 高级用法',
        '### Custom metadata and tags': '### 自定义元数据和标签',
        'You can add custom metadata to your traces using OpenTelemetry span attributes:': '您可以使用 OpenTelemetry 跨度属性向追踪添加自定义元数据：',
    },
    'trace-with-semantic-kernel': {
        'Trace Semantic Kernel applications': '追踪 Semantic Kernel 应用程序',
        'LangSmith can capture traces generated by [Semantic Kernel](https://learn.microsoft.com/en-us/semantic-kernel/overview/) using its built-in OpenTelemetry support. This guide shows you how to automatically capture traces from your Semantic Kernel applications and send them to LangSmith for monitoring and analysis.': 'LangSmith 可以使用其内置的 OpenTelemetry 支持来捕获由 [Semantic Kernel](https://learn.microsoft.com/en-us/semantic-kernel/overview/) 生成的追踪。本指南向您展示如何自动捕获 Semantic Kernel 应用程序中的追踪，并将其发送到 LangSmith 进行监控和分析。',
        '## Installation': '## 安装',
        'Install the required packages using your preferred package manager:': '使用您喜欢的包管理器安装所需的包：',
        '## Setup': '## 设置',
        '### 1. Configure environment variables': '### 1. 配置环境变量',
        'Set your [API keys](/langsmith/create-account-api-key) and project name:': '设置您的 [API 密钥](/langsmith/create-account-api-key) 和项目名称：',
        '### 2. Configure OpenTelemetry integration': '### 2. 配置 OpenTelemetry 集成',
        'In your Semantic Kernel application, configure the LangSmith OpenTelemetry integration along with the OpenAI instrumentor:': '在您的 Semantic Kernel 应用程序中，配置 LangSmith OpenTelemetry 集成以及 OpenAI 检测器：',
        'You do not need to set any OpenTelemetry environment variables or configure exporters manually—`configure()` handles everything automatically.': '您不需要设置任何 OpenTelemetry 环境变量或手动配置导出器——`configure()` 自动处理一切。',
        '### 3. Create and run your Semantic Kernel application': '### 3. 创建并运行您的 Semantic Kernel 应用程序',
        'Once configured, your Semantic Kernel application will automatically send traces to LangSmith:': '配置完成后，您的 Semantic Kernel 应用程序将自动向 LangSmith 发送追踪：',
        '## Advanced usage': '## 高级用法',
        '### Custom metadata and tags': '### 自定义元数据和标签',
        'You can add custom metadata to your traces by setting span attributes:': '您可以通过设置跨度属性来向追踪添加自定义元数据：',
        '### Combining with other instrumentors': '### 与其他检测器结合',
        'You can combine Semantic Kernel tracing with other OpenTelemetry instrumentors:': '您可以将 Semantic Kernel 追踪与其他 OpenTelemetry 检测器结合使用：',
        '## Resources': '## 资源',
        '- [Semantic Kernel documentation](https://learn.microsoft.com/en-us/semantic-kernel/overview/)': '- [Semantic Kernel 文档](https://learn.microsoft.com/en-us/semantic-kernel/overview/)',
        '- [Semantic Kernel observability guide](https://learn.microsoft.com/en-us/semantic-kernel/concepts/enterprise-readiness/observability/)': '- [Semantic Kernel 可观测性指南](https://learn.microsoft.com/en-us/semantic-kernel/concepts/enterprise-readiness/observability/)',
        '- [LangSmith OpenTelemetry guide](/langsmith/trace-with-opentelemetry)': '- [LangSmith OpenTelemetry 指南](/langsmith/trace-with-opentelemetry)',
    },
}

files_to_translate_batch3 = [
    ('src/langsmith/trace-with-n8n.mdx', 'docs_zh/langsmith/trace-with-n8n.mdx', 'trace-with-n8n'),
    ('src/langsmith/trace-with-openai-agents-sdk.mdx', 'docs_zh/langsmith/trace-with-openai-agents-sdk.mdx', 'trace-with-openai-agents-sdk'),
    ('src/langsmith/trace-with-opentelemetry.mdx', 'docs_zh/langsmith/trace-with-opentelemetry.mdx', 'trace-with-opentelemetry'),
    ('src/langsmith/trace-with-pipecat.mdx', 'docs_zh/langsmith/trace-with-pipecat.mdx', 'trace-with-pipecat'),
    ('src/langsmith/trace-with-pydantic-ai.mdx', 'docs_zh/langsmith/trace-with-pydantic-ai.mdx', 'trace-with-pydantic-ai'),
    ('src/langsmith/trace-with-semantic-kernel.mdx', 'docs_zh/langsmith/trace-with-semantic-kernel.mdx', 'trace-with-semantic-kernel'),
]

if __name__ == '__main__':
    count = 0
    for src, dst, key in files_to_translate_batch3:
        if os.path.exists(dst):
            print(f'Skipping existing: {dst}')
            continue
        if key in translations_batch3:
            translate_file(src, dst, translations_batch3[key])
            count += 1
    print(f'Translated {count} files')