#!/usr/bin/env python
import os
import sys

def translate_file(src_path, dst_path, translations):
    with open(src_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for eng, chn in translations.items():
        content = content.replace(eng, chn)

    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Translated: {src_path} -> {dst_path}')

# Translation mappings for batch6
translations_batch6 = {
    'view-usage': {
        'View usage': '查看使用情况',
        'LangSmith provides several views into your [organization\'s](/langsmith/administration-overview) usage, depending on your [plan](/langsmith/pricing-plans) and [deployment type](/langsmith/platform-setup). This page explains what data is available, what each metric means, and what limitations apply to [self-hosted](/langsmith/self-hosted) deployments.': 'LangSmith 根据您的[计划](/langsmith/pricing-plans)和[部署类型](/langsmith/platform-setup)提供多种视图来查看您的[组织](/langsmith/administration-overview)使用情况。本页解释了哪些数据可用、每个指标的含义，以及[自托管](/langsmith/self-hosted)部署有哪些限制。',
        '## Usage views': '## 使用情况视图',
        '| View | Where to find it | Who can see it | Plan availability |': '| 视图 | 在哪里找到 | 谁可以查看 | 计划可用性 |',
        '|------|-----------------|----------------|-------------------|': '|------|-----------------|----------------|-------------------|',
        '| [Usage graph](#usage-graph) |**Enterprise**: Settings > Usage > Usage graph<br></br>**Self-serve**: Settings > Billing > Usage graph | All org members | All plans |': '| [使用情况图](#usage-graph) |**Enterprise**: 设置 > 使用情况 > 使用情况图<br></br>**Self-serve**: 设置 > 计费 > 使用情况图 | 所有组织成员 | 所有计划 |',
        '| [Granular usage](#granular-usage) | **Enterprise**: Settings > Usage > Granular usage<br></br>**Self-serve**: Settings > Billing > Granular usage | All org members | All plans |': '| [详细使用情况](#granular-usage) | **Enterprise**: 设置 > 使用情况 > 详细使用情况<br></br>**Self-serve**: 设置 > 计费 > 详细使用情况 | 所有组织成员 | 所有计划 |',
        '| [Contract burndown](#contract-burndown) | **Enterprise**: Settings > Usage > Contract usage<br></br>**Self-serve**: Settings > Billing > Contract usage | Org admins only (`organization:manage`) | Enterprise only |': '| [合同消耗](#contract-burndown) | **Enterprise**: 设置 > 使用情况 > 合同使用情况<br></br>**Self-serve**: 设置 > 计费 > 合同使用情况 | 仅组织管理员（`organization:manage`） | 仅 Enterprise |',
        '| [Invoices](#invoices) | Settings > Billing > Invoices | All org members | Self-serve cloud only |': '| [发票](#invoices) | 设置 > 计费 > 发票 | 所有组织成员 | 仅 Self-serve 云 |',
        '## Usage graph': '## 使用情况图',
        'The usage graph shows aggregate trace consumption for your organization, broken down by workspace. It covers the current billing period and does not show spend—for spend, refer to the invoice.': '使用情况图显示您组织的聚合追踪消耗，按工作区细分。它涵盖当前计费周期，不显示支出——要查看支出，请参阅发票。',
        'Navigate to **Settings** → **Billing and Usage** → **Usage Graph**.': '导航到 **设置** → **计费和使用情况** → **使用情况图**。',
        '### Billable metrics': '### 计费指标',
        '| Metric | What it counts |': '| 指标 | 它计算什么 |',
        '|--------|----------------|': '|--------|----------------|',
        '| **LangSmith Traces (Base Charge)** | Every trace sent to LangSmith during the billing period, regardless of data retention tier. |': '| **LangSmith 追踪（基础费用）** | 计费期间发送到 LangSmith 的每条追踪，无论数据保留层如何。 |',
        '| **LangSmith Traces (Extended Data Retention Upgrades)** | Traces upgraded to extended retention (400 days by default, [customizable for Enterprise customers](/langsmith/data-purging-compliance#customize-extended-retention-policy)). These are charged in addition to the base charge. |': '| **LangSmith 追踪（扩展数据保留升级）** | 升级到扩展保留的追踪（默认 400 天，[可为企业客户自定义](/langsmith/data-purging-compliance#customize-extended-retention-policy)）。这些费用在基础费用之外收取。 |',
        '| **LangSmith Deployment Runs** | End-to-end invocations of deployed LangGraph agents. See [LangSmith Deployment billing](/langsmith/billing#langsmith-deployment-billing) for pricing details. |': '| **LangSmith 部署运行** | 部署的 LangGraph 智能体的端到端调用。请参阅[LangSmith 部署计费](/langsmith/billing#langsmith-deployment-billing)了解定价详情。 |',
        '| **LangSmith Fleet Runs** | End-to-end invocations of [Fleet](/langsmith/fleet) agents. Tracked separately for cloud-hosted and self-hosted deployments. |': '| **LangSmith Fleet 运行** | [Fleet](/langsmith/fleet) 智能体的端到端调用。云托管和自托管部署分开追踪。 |',
        '| **LangSmith Deployment Nodes Executed** | Individual LangGraph node executions across deployed agents. Each step in a deployed agent\'s graph counts as one node execution. Tracked separately for cloud-hosted and self-hosted deployments. |': '| **LangSmith 部署节点执行** | 跨部署智能体的各个 LangGraph 节点执行。部署智能体图中的每个步骤算作一个节点执行。云托管和自托管部署分开追踪。 |',
        'For more details on trace retention tiers, refer to [Data retention](/langsmith/administration-overview#data-retention).': '有关追踪保留层的更多详细信息，请参阅[数据保留](/langsmith/administration-overview#data-retention)。',
        '<Note>': '<Note>',
        'The usage graph uses the term `tenant_id` interchangeably with workspace ID.': '使用情况图使用 `tenant_id` 和工作区 ID 作为同义词。',
        '## Contract burndown': '## 合同消耗',
        'Enterprise customers with prepaid commitments can view how much of their contract has been consumed.': '带有预付承诺的企业客户可以查看其合同已被消耗了多少。',
        'Navigate to **Settings** → **Usage Configuration** → **Contract Usage**.': '导航到 **设置** → **使用情况配置** → **合同使用情况**。',
        'This view shows:': '此视图显示：',
        '- **Usage summary**: Total usage, total credits, and any overages. Overages occur when usage exceeds your total prepaid commitment.': '- **使用情况摘要**：总使用量、总积分和任何超额使用量。当使用量超过您的总预付承诺时，会产生超额使用量。',
        '- **Commitment progress bars**: Visual indicators for each commitment showing percentage consumed and dollar amounts for used vs. remaining. Contracts can have multiple commitments that apply to different time periods (e.g., year 1 and year 2 of a multi-year contract) or different products.': '- **承诺进度条**：每个承诺的视觉指示器，显示已消耗的百分比以及已使用与剩余的美元金额。合同可以有多个承诺，适用于不同的时间段（例如，多年合同的第 1 年和第 2 年）或不同的产品。',
        '- **Monthly usage chart**: Bar chart showing usage amounts for each month within your contract period.': '- **月度使用量图表**：条形图，显示合同期内每个月的使用量。',
        '- **Product rates**: Table of your entitled products and their pricing.': '- **产品费率**：您有权获得的产品及其价格的表格。',
        '<Note>': '<Note>',
        'Contract burndown requires the [`organization:manage` permission](/langsmith/organization-workspace-operations) and is only available to Enterprise customers with prepaid commitments.': '合同消耗需要 [`organization:manage` 权限](/langsmith/organization-workspace-operations)，仅适用于带有预付承诺的企业客户。',
        '## Invoices': '## 发票',
        'Invoices are available on **self-serve cloud plans only**. Enterprise cloud organizations have a separate usage view for tracking spend.': '发票仅适用于**自选云计划**。企业云组织有单独的使用情况视图来跟踪支出。',
        'Navigate to **Settings** → **Billing and Usage** → **Invoices** to see how your usage translates to spend. The first invoice shown is a draft of your current month\'s invoice, reflecting your running spend to date.': '导航到 **设置** → **计费和使用情况** → **发票** 以查看您的使用情况如何转化为支出。显示的第一张发票是您当前月份的发票草稿，反映您目前的累计支出。',
        '## Granular usage': '## 详细使用情况',
        'Granular usage gives you trace counts broken down by a dimension you choose (workspace, project, user, or API key) over a time range you select. This is useful for internal chargebacks, identifying high-usage teams, or auditing trace activity.': '详细使用情况为您提供按您选择的维度（工作区、项目、用户或 API 密钥）和您选择的时间范围细分的追踪计数。这对于内部成本回收、识别高使用量团队或审计追踪活动很有用。',
        'Navigate to **Settings** → **Billing and Usage** → **Granular Usage**, or use the [granular usage API](/langsmith/granular-usage).': '导航到 **设置** → **计费和使用情况** → **详细使用情况**，或使用[详细使用情况 API](/langsmith/granular-usage)。',
        '### What "traces" means here': '### 这里"追踪"的含义',
        'The granular usage view counts **traces**: root-level runs and all their child spans counted as a single unit. This is the same unit used for [billing](/langsmith/billing). It does not count individual spans, tokens, or model calls separately.': '详细使用情况视图计算**追踪**：根级运行及其所有子跨度计为一个单元。这与[计费](/langsmith/billing)使用的单位相同。它不单独计算各个跨度、令牌或模型调用。',
        '### When usage is recorded': '### 记录使用情况的时间',
        'Granular usage records traces by **insertion time** (when the trace was received and stored by LangSmith), not by when it ran in your application. In practice this difference is usually negligible, but traces sent with significant delay (e.g., buffered SDK uploads) may appear in a later time bucket than expected.': '详细使用情况按**插入时间**（追踪被 LangSmith 接收和存储的时间）记录追踪，而不是按它在应用程序中运行的时间。在实践中，这种差异通常可以忽略不计，但具有明显延迟发送的追踪（例如，缓冲的 SDK 上传）可能会出现在比预期更晚的时间桶中。',
        'For grouping options, time bucket sizes, and API reference, refer to [Granular billable usage](/langsmith/granular-usage).': '有关分组选项、时间桶大小和 API 参考，请参阅[详细计费使用情况](/langsmith/granular-usage)。',
        '## Self-hosted limitations': '## 自托管限制',
        '[Self-hosted](/langsmith/self-hosted) LangSmith [deployments](/langsmith/deployment) have a different set of usage views available compared to [Cloud](/langsmith/cloud), due to differences in billing infrastructure.': '由于计费基础设施的差异，[自托管](/langsmith/self-hosted) LangSmith [部署](/langsmith/deployment)与[云](/langsmith/cloud)相比有一组不同的可用使用情况视图。',
        '| **Feature** | **Self-hosted availability** |': '| **功能** | **自托管可用性** |',
        '|---------|--------------------------|': '|---------|--------------------------|',
        '| Granular usage (trace attribution) | Available with feature flags or version ≥ 0.13.12 |': '| 详细使用情况（追踪归属） | 通过功能标志或版本 ≥ 0.13.12 可用 |',
        '| Usage graph (aggregate traces) | Available on Helm chart 0.9.5 and later |': '| 使用情况图（聚合追踪） | 在 Helm chart 0.9.5 及更高版本上可用 |',
        '| Contract burndown | Available when Beacon phone-home is enabled |': '| 合同消耗 | 当 Beacon phone-home 启用时可用 |',
        '| Invoices and payment management | Not available (billing is handled outside LangSmith) |': '| 发票和支付管理 | 不可用（计费在 LangSmith 外部处理） |',
        '### Granular usage on self-hosted': '### 自托管上的详细使用情况',
        'Granular usage is available on self-hosted deployments but requires explicit opt-in:': '自托管部署可以使用详细使用情况，但需要明确选择加入：',
        '- On **LangSmith 0.13.12 and later**, granular usage collection is enabled by default.': '- 在 **LangSmith 0.13.12 及更高版本**上，详细使用情况收集默认启用。',
        '- On **earlier versions**, enable it by setting both of the following environment variables:': '- 在**早期版本**上，通过设置以下两个环境变量来启用它：',
        '<Warning>': '<Warning>',
        'Data collection begins from the moment the feature is enabled. There is no backfill of historical usage data prior to enabling it. Plan accordingly when choosing when to enable this feature.': '数据收集从启用该功能的那一刻开始。启用之前没有历史使用数据的回填。在选择何时启用此功能时，请相应地进行规划。',
        '### Aggregate usage on self-hosted': '### 自托管上的聚合使用情况',
        'The usage graph is available on self-hosted deployments running Helm chart 0.9.5 or later. LangSmith automatically generates and syncs organization usage charts, available under **Settings** → **Usage and billing** → **Usage graph**:': '使用情况图在运行 Helm chart 0.9.5 或更高版本的自托管部署上可用。LangSmith 自动生成并同步组织使用情况图表，可在 **设置** → **使用情况和计费** → **使用情况图** 下找到：',
        '- **Usage by Workspace**: trace counts (root runs) per workspace': '- **按工作区的使用情况**：每个工作区的追踪计数（根运行）',
        '- **Organization Usage**: total trace counts across the organization': '- **组织使用情况**：整个组织的总追踪计数',
        'Charts refresh every 5 minutes to include new workspaces and are not editable.': '图表每 5 分钟刷新一次以包含新工作区，不可编辑。',
        'For programmatic access to trace counts, see [View trace counts across your organization](/langsmith/self-host-organization-charts).': '有关以编程方式访问追踪计数，请参阅[查看整个组织的追踪计数](/langsmith/self-host-organization-charts)。',
        '## Related resources': '## 相关资源',
        '- [Granular billable usage API reference](/langsmith/granular-usage)': '- [详细计费使用情况 API 参考](/langsmith/granular-usage)',
        '- [Manage billing](/langsmith/billing)': '- [管理计费](/langsmith/billing)',
        '- [Data retention and usage limits](/langsmith/administration-overview#data-retention)': '- [数据保留和使用限制](/langsmith/administration-overview#data-retention)',
        '- [Organization and workspace operations](/langsmith/organization-workspace-operations)': '- [组织和工作区操作](/langsmith/organization-workspace-operations)',
    },
    'vitest-jest': {
        'How to run evaluations with Vitest/Jest': '如何使用 Vitest/Jest 运行评估',
        'LangSmith provides integrations with [Vitest](https://vitest.dev/) and [Jest](https://jestjs.io/) that allow JavaScript and TypeScript developers to define their [datasets](/langsmith/evaluation-concepts#datasets) and evaluate using familiar syntax.': 'LangSmith 提供了与 [Vitest](https://vitest.dev/) 和 [Jest](https://jestjs.io/) 的集成，允许 JavaScript 和 TypeScript 开发者使用熟悉的语法定义他们的[数据集](/langsmith/evaluation-concepts#datasets)并进行评估。',
        'Compared to the @[`evaluate()`][Client.evaluate] evaluation flow, the Vitest or Jest testing frameworks are useful when:': '与 @[`evaluate()`][Client.evaluate] 评估流程相比，Vitest 或 Jest 测试框架在以下情况下很有用：',
        '* **Each example requires different evaluation logic**: Standard evaluation flows assume consistent application and evaluator execution across all dataset examples. For more complex systems or comprehensive evaluations, specific system subsets may require evaluation with particular input types and metrics. These heterogeneous evaluations are simpler to write as distinct test case suites that track together.': '* **每个示例需要不同的评估逻辑**：标准评估流程假设在所有数据集示例中应用和评估器执行一致。对于更复杂的系统或全面评估，特定系统子集可能需要使用特定输入类型和指标进行评估。这些异构评估更容易作为独立的测试用例套件编写，并一起追踪。',
        '* **You want to assert binary expectations**: Track assertions in LangSmith and raise assertion errors locally (e.g. in CI pipelines). Testing tools help when both evaluating system outputs and asserting basic properties about them.': '* **您想要断言二元期望**：在 LangSmith 中追踪断言并在本地引发断言错误（例如在 CI 流水线中）。测试工具在评估系统输出和断言其基本属性时都有帮助。',
        '* **You want to take advantage of mocks, watch mode, local results, or other features of the Vitest/Jest ecosystems**.': '* **您想利用 Vitest/Jest 生态系统的模拟、监视模式、本地结果或其他功能**。',
        '<Info>': '<Info>',
        'Requires JS/TS SDK version `langsmith>=0.3.1`.': '需要 JS/TS SDK 版本 `langsmith>=0.3.1`。',
        '<Info>': '<Info>',
        'The Python SDK has an analogous [pytest integration](/langsmith/pytest).': 'Python SDK 有类似的 [pytest 集成](/langsmith/pytest)。',
        '## Setup': '## 设置',
        'Set up the integrations as follows. Note that while you can add LangSmith evals alongside your other unit tests (as standard `*.test.ts` files) using your existing test config files, the below examples will also set up a separate test config file and command to run your evals. It will assume you end your test files with `.eval.ts`.': '设置集成如下。请注意，虽然您可以使用现有的测试配置文件将 LangSmith 评估与您的其他单元测试一起添加（作为标准的 `*.test.ts` 文件），但以下示例还将设置一个单独的测试配置文件和命令来运行您的评估。它将假定您的测试文件以 `.eval.ts` 结尾。',
        'This ensures that the custom test reporter and other LangSmith touchpoints do not modify your existing test outputs.': '这确保自定义测试报告器和其他 LangSmith 接触点不会修改您现有的测试输出。',
        '### Vitest': '### Vitest',
        'Install the required development dependencies if you have not already:': '如果尚未安装，请安装所需的开发依赖项：',
        'The following examples also require `openai` (and `langsmith`) as a dependency:': '以下示例还需要 `openai`（和 `langsmith`）作为依赖项：',
        'Then, create a separate `ls.vitest.config.ts` file with the following base config:': '然后，创建一个带有以下基本配置的单独 `ls.vitest.config.ts` 文件：',
        '* `include` ensures that only files ending with some variation of `eval.ts` in your project are run': '* `include` 确保只运行项目中以某种变体 `eval.ts` 结尾的文件',
        '* `reporters` is responsible for nicely formatting your output as shown above': '* `reporters` 负责如上图所示很好地格式化您的输出',
        '* `setupFiles` runs `dotenv` to load environment variables before running your evals': '* `setupFiles` 运行 `dotenv` 以在运行评估之前加载环境变量',
        '* `testTimeout` sets a global default timeout for each test. Because LLM calls can be slow, we increase this from the Vitest default': '* `testTimeout` 为每个测试设置全局默认超时。因为大型语言模型调用可能很慢，我们从 Vitest 默认值增加了这个值',
        '<Warning>': '<Warning>',
        'JSDom environments are not supported at this time. You should either omit the `"environment"` field from your config or set it to `"node"`.': '目前不支持 JSDom 环境。您应该从配置中省略 `"environment"` 字段或将其设置为 `"node"`。',
        'Finally, add the following to the `scripts` field in your `package.json` to run Vitest with the config you just created:': '最后，将以下内容添加到您的 `package.json` 中的 `scripts` 字段，以使用您刚刚创建的配置运行 Vitest：',
        'Note that this script disables Vitest\'s default watch mode for running evals since many evaluators may include longer running LLM calls.': '请注意，此脚本禁用了 Vitest 默认的监视模式来运行评估，因为许多评估器可能包括运行时间较长的大型语言模型调用。',
        '### Jest': '### Jest',
        '<Info>': '<Info>',
        'The following setup instructions are for basic JS files and CJS. To add support for TypeScript and ESM, see Jest\'s official docs or use [Vitest](#vitest).': '以下设置说明适用于基本 JS 文件和 CJS。要添加对 TypeScript 和 ESM 的支持，请参阅 Jest 的官方文档或使用 [Vitest](#vitest)。',
        'Then, create a separate config file named `ls.jest.config.cjs`:': '然后，创建一个名为 `ls.jest.config.cjs` 的单独配置文件：',
        '* `testMatch` ensures that only files ending with some variation of `eval.js` in your project are run': '* `testMatch` 确保只运行项目中以某种变体 `eval.js` 结尾的文件',
        '## Define and run evals': '## 定义和运行评估',
        'You can now define evals as tests using familiar Vitest/Jest syntax, with a few caveats:': '您现在可以使用熟悉的 Vitest/Jest 语法将评估定义为测试，但有一些注意事项：',
        '* You should import `describe` and `test` from the @[`langsmith/jest`][langsmith/jest] or @[`langsmith/vitest`][langsmith/vitest] entrypoint.': '* 您应该从 @[`langsmith/jest`][langsmith/jest] 或 @[`langsmith/vitest`][langsmith/vitest] 入口点导入 `describe` 和 `test`。',
        '* You must wrap your test cases in a `describe` block.': '* 您必须将测试用例包装在 `describe` 块中。',
        '* When declaring tests, the signature is slightly different—there is an extra argument containing example inputs and expected outputs.': '* 声明测试时，签名略有不同——有一个包含示例输入和预期输出的额外参数。',
        'You can think of each @[ls.test][ls.test] case as corresponding to a dataset example, and @[`ls.describe()`][ls.describe] as defining a LangSmith dataset.': '您可以将每个 @[ls.test][ls.test] 用例视为对应于一个数据集示例，并将 @[`ls.describe()`][ls.describe] 视为定义一个 LangSmith 数据集。',
        'Create a `.env` file with your `OPENAI_API_KEY` and LangSmith credentials if you don\'t already have one:': '如果还没有包含您的 `OPENAI_API_KEY` 和 LangSmith 凭据的 `.env` 文件，请创建一个：',
        'Now use the `eval` script we set up in the previous step to run the test:': '现在使用我们在上一步设置的 `eval` 脚本来运行测试：',
        'And your declared test should run!': '您声明的测试应该运行了！',
        'Once it finishes, if you\'ve set your LangSmith environment variables, you should see a link directing you to an experiment created in LangSmith alongside the test results.': '一旦完成，如果您已经设置了 LangSmith 环境变量，您应该会看到一个链接，指向在测试结果旁边在 LangSmith 中创建的实验。',
        '## Trace feedback': '## 追踪反馈',
        'By default LangSmith collects the pass/fail rate under the `pass` feedback key for each test case. You can add additional feedback with either @[`ls.logFeedback()`][ls.logFeedback] or @[`ls.wrapEvaluator()`][ls.wrapEvaluator].': '默认情况下，LangSmith 在每个测试用例的 `pass` 反馈键下收集通过/失败率。您可以使用 @[`ls.logFeedback()`][ls.logFeedback] 或 @[`ls.wrapEvaluator()`][ls.wrapEvaluator] 添加额外反馈。',
        'Note the use of @[`ls.wrapEvaluator()`][ls.wrapEvaluator] around the `myEvaluator` function. This makes it so that the LLM-as-judge call is traced separately from the rest of the test case to avoid clutter, and conveniently creates feedback if the return value from the wrapped function matches `{ key: string; score: number | boolean }`.': '注意在 `myEvaluator` 函数周围使用 @[`ls.wrapEvaluator()`][ls.wrapEvaluator]。这使得大型语言模型作为评判者的调用与测试用例的其余部分分开追踪以避免混乱，如果包装函数的返回值匹配 `{ key: string; score: number | boolean }`，它会方便地创建反馈。',
        'You can see the evaluator runs in LangSmith by clicking their corresponding feedback chips in the UI.': '您可以通过在 UI 中点击相应的反馈芯片来查看 LangSmith 中的评估器运行。',
        '## Running multiple examples against a test case': '## 针对测试用例运行多个示例',
        'You can run the same test case over multiple examples and parameterize your tests using @[`ls.test.each()`][ls.test.each]. This is useful when you want to evaluate your app the same way against different inputs:': '您可以使用 @[`ls.test.each()`][ls.test.each] 对多个示例运行相同的测试用例并参数化您的测试。当您想以相同的方式针对不同的输入评估您的应用时，这很有用：',
        'If you have tracking enabled, each example in the local dataset will be synced to the one created in LangSmith.': '如果您启用了追踪，本地数据集中的每个示例都将同步到 LangSmith 中创建的那个。',
        '## Use an existing dataset (Vitest only)': '## 使用现有数据集（仅限 Vitest）',
        'Instead of defining [examples](/langsmith/evaluation-concepts#examples) inline, you can run tests against an existing dataset in LangSmith:': '您可以针对 LangSmith 中的现有数据集运行测试，而不是内联定义[示例](/langsmith/evaluation-concepts#examples)：',
        '- Use @[`client.listExamples()`][Client.listExamples] to fetch examples from a dataset that already exists in LangSmith.': '- 使用 @[`client.listExamples()`][Client.listExamples] 从已经存在于 LangSmith 中的数据集中获取示例。',
        '- Collect the examples into an array (e.g., `testExamples`) by iterating through the async generator.': '- 通过迭代异步生成器将示例收集到一个数组中（例如 `testExamples`）。',
        '- Pass the array to @[`ls.test.each()`][ls.test.each] to run your test logic against each example from the dataset.': '- 将数组传递给 @[`ls.test.each()`][ls.test.each] 以针对数据集中的每个示例运行您的测试逻辑。',
        '## Log outputs': '## 记录输出',
        'Every time we run a test we\'re syncing it to a dataset example and tracing it as a run. To trace final outputs for the run, you can use @[`ls.logOutputs()`][ls.logOutputs] like this:': '每次运行测试时，我们都会将其同步到数据集示例并将其作为运行进行追踪。要追踪运行的最终输出，您可以使用 @[`ls.logOutputs()`][ls.logOutputs]，如下所示：',
        'The logged outputs will appear in your reporter summary and in LangSmith.': '记录的输出将出现在您的报告摘要和 LangSmith 中。',
        'You can also directly return a value from your test function:': '您也可以直接从测试函数返回值：',
        'However keep in mind if you do this that if your test fails to complete due to a failed assertion or other error, your output will not appear.': '但是请记住，如果您这样做，如果您的测试由于断言失败或其他错误而无法完成，您的输出将不会显示。',
        '## Trace intermediate calls': '## 追踪中间调用',
        'LangSmith will automatically trace any traceable intermediate calls that happen in the course of test case execution.': 'LangSmith 会自动追踪在测试用例执行过程中发生的任何可追踪的中间调用。',
        '## Focusing or skipping tests': '## 聚焦或跳过测试',
        'You can chain the Vitest/Jest `.skip` and `.only` methods on `ls.test()` and `ls.describe()`:': '您可以在 `ls.test()` 和 `ls.describe()` 上链接 Vitest/Jest 的 `.skip` 和 `.only` 方法：',
        '## Configuring test suites': '## 配置测试套件',
        'You can configure test suites with values like metadata or a custom client by passing an extra argument to `ls.describe()` for the full suite or by passing a `config` field into `ls.test()` for individual tests:': '您可以通过将额外参数传递给 `ls.describe()` 来为整个套件配置元数据或自定义客户端等值的测试套件，或者通过将 `config` 字段传递到 `ls.test()` 来配置单个测试：',
        'The test suite will also automatically extract environment variables from `process.env.ENVIRONMENT`, `process.env.NODE_ENV` and `process.env.LANGSMITH_ENVIRONMENT` and set them as metadata on created experiments. You can then filter experiments by metadata in LangSmith\'s UI.': '测试套件还将自动从 `process.env.ENVIRONMENT`、`process.env.NODE_ENV` 和 `process.env.LANGSMITH_ENVIRONMENT` 中提取环境变量，并将它们设置为创建实验的元数据。然后，您可以在 LangSmith 的 UI 中按元数据过滤实验。',
        'See [the API refs](https://docs.smith.langchain.com/reference/js/functions/vitest.describe) for a full list of configuration options.': '有关配置选项的完整列表，请参阅 [API 参考](https://docs.smith.langchain.com/reference/js/functions/vitest.describe)。',
        '## Dry-run mode': '## 试运行模式',
        'If you want to run the tests without syncing the results to LangSmith, you can set omit your LangSmith tracing environment variables or set `LANGSMITH_TEST_TRACKING=false` in your environment.': '如果您想在不将结果同步到 LangSmith 的情况下运行测试，您可以省略 LangSmith 追踪环境变量或在您的环境中设置 `LANGSMITH_TEST_TRACKING=false`。',
        'The tests will run as normal, but the experiment logs will not be sent to LangSmith.': '测试将正常运行，但实验日志不会发送到 LangSmith。',
    },
    'workload-isolation': {
        'Workload isolation': '工作负载隔离',
        'LangSmith uses a hierarchical structure to organize your work: [_organizations_](/langsmith/administration-overview#organizations), [_workspaces_](/langsmith/administration-overview#workspaces), [_applications_](/langsmith/administration-overview#applications), and [_resources_](/langsmith/administration-overview#resources). This structure lets you balance collaboration with access control, allowing you to choose the right level of isolation for your team\'s needs.': 'LangSmith 使用分层结构来组织您的工作：[_组织_](/langsmith/administration-overview#organizations)、[_工作区_](/langsmith/administration-overview#workspaces)、[_应用程序_](/langsmith/administration-overview#applications)和[_资源_](/langsmith/administration-overview#resources)。这个结构让您能够平衡协作与访问控制，允许您为团队的需求选择合适的隔离级别。',
        'The LangSmith permission system builds on this hierarchy. With [role-based access control (RBAC)](/langsmith/rbac), user [permissions](/langsmith/organization-workspace-operations) are scoped to one or more workspaces, enforcing isolation between workspaces. With more fine-grained [attribute-based access control](/langsmith/organization-workspace-operations#access-policies) (ABAC), access can be further restricted or granted based on attributes such as tags or applications within a workspace (for example, allowing users to access only development resources or only resources associated with a specific application).': 'LangSmith 权限系统建立在这个层次结构之上。通过[基于角色的访问控制 (RBAC)](/langsmith/rbac)，用户[权限](/langsmith/organization-workspace-operations)的作用域是一个或多个工作区，在工作区之间强制执行隔离。通过更细粒度的[基于属性的访问控制](/langsmith/organization-workspace-operations#access-policies) (ABAC)，可以基于工作区内的标签或应用程序等属性进一步限制或授予访问权限（例如，允许用户仅访问开发资源或仅访问与特定应用程序关联的资源）。',
        'This page explains three common approaches to organizing workspaces based on your team\'s isolation requirements:': '本页面解释了基于团队隔离需求组织工作区的三种常见方法：',
        '- [Team-centric workspaces](#team-centric-workspaces): Single workspace per team (recommended for most customers)': '- [以团队为中心的工作区](#team-centric-workspaces)：每个团队一个工作区（推荐给大多数客户）',
        '- [Collaborative workspaces](#collaborative-workspaces): Multiple teams per workspace': '- [协作工作区](#collaborative-workspaces)：每个工作区多个团队',
        '- [Project-isolated workspaces](#project-isolated-workspaces): Multiple workspaces per team (for strict isolation requirements)': '- [项目隔离工作区](#project-isolated-workspaces)：每个团队多个工作区（用于严格隔离要求）',
        '<Tip>': '<Tip>',
        'For details on setting up organizations and workspaces, refer to [Set up hierarchy](/langsmith/set-up-hierarchy).': '有关设置组织和工作区的详细信息，请参阅[设置层次结构](/langsmith/set-up-hierarchy)。',
        '## Team-centric workspaces': '## 以团队为中心的工作区',
        '<Warning>': '<Warning>',
        'This is the default model and recommended choice for most customers.': '这是默认模型，是大多数客户的推荐选择。',
        'This model (single workspace per team) uses a single organization as the top-level boundary. Within the organization, multiple workspaces are used to isolate different teams or business units. Each workspace represents a logical boundary for a specific team and governs which data and resources that team can access. Within a workspace, teams use multiple applications to group together resources that support the same agent. An application may also contain distinct resources, such as separate tracing projects, for development and production environments.': '此模型（每个团队一个工作区）使用单个组织作为顶级边界。在组织内，多个工作区用于隔离不同的团队或业务单元。每个工作区代表特定团队的逻辑边界，并管理该团队可以访问的数据和资源。在工作区内，团队使用多个应用程序将支持同一智能体的资源组合在一起。应用程序还可以包含不同的资源，例如用于开发和生产环境的单独追踪项目。',
        '- **Pros:** A single workspace allows all team resources to be shared, making collaboration and iteration within a team straightforward. It also simplifies promotion from development to production. For example, the same [prompt](/langsmith/prompt-engineering) can be versioned and promoted to production using tags, without copying or duplication.': '- **优点：** 单一工作区允许共享所有团队资源，使团队内的协作和迭代变得简单。它还简化了从开发到生产的推广。例如，相同的[提示词](/langsmith/prompt-engineering)可以使用标签进行版本控制和推广到生产，而无需复制或重复。',
        '- **Cons:** The primary trade-off is limited isolation between environments of the same team. Development, test, and production resources coexist within the same application, so teams must rely on tagging and conventions to avoid accidental impact on production. [RBAC](/langsmith/rbac) is scoped at the workspace level. [ABAC](/langsmith/organization-workspace-operations#access-policies) provides more granular permissions within a workspace by restricting access based on resource attributes, such as allowing a user to access only development resources.': '- **缺点：** 主要权衡是同一团队环境之间的隔离有限。开发、测试和生产资源在同一应用程序中共存，因此团队必须依赖标签和约定来避免对生产造成意外影响。[RBAC](/langsmith/rbac) 的作用域在工作区级别。[ABAC](/langsmith/organization-workspace-operations#access-policies) 通过基于资源属性限制访问来在工作区内提供更细粒度的权限，例如允许用户仅访问开发资源。',
        '## Collaborative workspaces': '## 协作工作区',
        'In this model (multiple teams per workspace), multiple teams share a single workspace within an organization and use applications and [ABAC](/langsmith/organization-workspace-operations#access-policies) to separate resources and govern access. As a result, shared resources such as [prompts](/langsmith/prompt-engineering) and [deployments](/langsmith/deployment) can be reused across teams, while access to sensitive resources like [traces](/langsmith/observability-concepts#traces) and [datasets](/langsmith/evaluation-concepts#datasets) is limited to the owning team.': '在此模型（每个工作区多个团队）中，多个团队在组织内共享一个工作区，并使用应用程序和 [ABAC](/langsmith/organization-workspace-operations#access-policies) 来分离资源和管理访问。因此，[提示词](/langsmith/prompt-engineering)和[部署](/langsmith/deployment)等共享资源可以在团队之间重用，而[追踪](/langsmith/observability-concepts#traces)和[数据集](/langsmith/evaluation-concepts#datasets)等敏感资源的访问仅限于拥有团队。',
        '- **Pros:** Common resources such as prompts and deployments can be shared and reused across teams, increasing collaboration and reducing duplicated work. Unlike the team-centric workspace model, collaboration is not limited to a single team and can span all teams within the workspace.': '- **优点：** 提示词和部署等常见资源可以在团队之间共享和重用，增加协作并减少重复工作。与以团队为中心的工作区模型不同，协作不限于单个团队，可以跨越工作区内的所有团队。',
        '- **Cons:** Isolation between teams and environments is weaker than in multi-workspace models and depends on correct use of ABAC. Misconfigured tags or policies can expose sensitive [traces](/langsmith/observability-concepts#traces) or [datasets](/langsmith/evaluation-concepts#datasets) across teams, and managing permissions across multiple teams adds operational complexity.': '- **缺点：** 团队和环境之间的隔离比多工作区模型弱，取决于正确使用 ABAC。配置错误的标签或策略可能会在团队之间暴露敏感[追踪](/langsmith/observability-concepts#traces)或[数据集](/langsmith/evaluation-concepts#datasets)，并且跨多个团队管理权限增加了运营复杂性。',
        '## Project-isolated workspaces': '## 项目隔离工作区',
        '<Callout icon="check" iconType="solid" color="#C7D2FE">': '<Callout icon="check" iconType="solid" color="#C7D2FE">',
        'This approach should be used only when strict isolation is required.': '此方法仅在需要严格隔离时使用。',
        '</Callout>': '</Callout>',
        'In this model (multiple workspaces per team), isolation is increased by creating multiple workspaces for a single team. Workspaces may be organized by project or by environment, such as separate development and production workspaces. Each workspace is fully isolated, with its own users, data, and resources, and access is strictly scoped to that workspace.': '在此模型（每个团队多个工作区）中，通过为单个团队创建多个工作区来增加隔离。工作区可以按项目或按环境组织，例如分开的开发和生产工作区。每个工作区完全隔离，有自己的用户、数据和资源，访问权限严格限于该工作区。',
        '- **Pros:** Strong isolation between teams, projects, and environments. Users with only access to the development workspace cannot view or access production data or any production resources, reducing the risk of accidental changes or cross-environment misuse.': '- **优点：** 团队、项目和环境之间的强隔离。只有开发工作区访问权限的用户无法查看或访问生产数据或任何生产资源，降低了意外更改或跨环境误用的风险。',
        '- **Cons:** Resources cannot be shared across workspaces. Reusing [prompts](/langsmith/prompt-engineering), [datasets](/langsmith/evaluation-concepts#datasets), or [experiments](/langsmith/evaluation-concepts#experiment), even when promoting an agent from development to production, requires manual copying between workspaces, which introduces friction and duplication.': '- **缺点：** 资源无法在工作区之间共享。重用[提示词](/langsmith/prompt-engineering)、[数据集](/langsmith/evaluation-concepts#datasets)或[实验](/langsmith/evaluation-concepts#experiment)，即使是将智能体从开发推广到生产，也需要在工作区之间手动复制，这增加了摩擦和重复。',
    },
    'write-prompt-with-ai': {
        'Write your prompt with AI': '使用 AI 编写您的提示词',
        'The prompt canvas makes it easy to edit a prompt with the help of an LLM. This allows you to iterate faster on long prompts and also makes it easier to make overarching stylisting or tonal changes to your prompt. You can enter the promp canvas by clicking the glowing wand over any message in your prompt:': '提示词画布让在大型语言模型的帮助下编辑提示词变得容易。这允许您在长提示词上更快地迭代，也更容易对提示词进行整体风格或语调更改。您可以通过点击提示词中任何消息上发光的魔杖来进入提示词画布：',
        '## Chat sidebar': '## 聊天侧边栏',
        'You can use the chat sidebar to ask questions about your prompt, or to give instructions in natural language to the LLM for how to rewrite your prompt.': '您可以使用聊天侧边栏来询问有关提示词的问题，或以自然语言向大型语言模型给出有关如何重写提示词的指示。',
        '<Note>': '<Note>',
        'You can also edit the prompt directly - you don\'t **need** to use the LLM. This is useful if you know what edits you want to make and just want to make them directly': '您也可以直接编辑提示词——您**不需要**使用大型语言模型。如果您知道想要进行什么编辑，这很有用，只需直接进行编辑即可',
        '## Quick actions': '## 快捷操作',
        'There are quick actions to change the reading level or length of the prompt with a single mouse click:': '有快捷操作可以只需单击一次鼠标即可更改提示词的阅读级别或长度：',
        '## Custom quick actions': '## 自定义快捷操作',
        'You can also save your own custom quick actions, for ease of use across all the prompts you are working on in LangSmith:': '您还可以保存自己的自定义快捷操作，以便在 LangSmith 中处理的所有提示词中轻松使用：',
        '## Diffing': '## 差异对比',
        'You can also see the specific differences between each version of your prompt by selecting the diff slider in the top right of the canvas:': '您还可以通过选择画布右上角的差异滑块来查看提示词每个版本之间的具体差异：',
        '## Saving and using prompts': '## 保存和使用提示词',
        'Lastly, you can save the prompt you have created in the canvas by clicking the "Use this Version" button in the bottom right:': '最后，您可以通过点击右下角的"使用此版本"按钮来保存您在画布中创建的提示词：',
    },
}

files_to_translate_batch6 = [
    ('src/langsmith/view-usage.mdx', 'docs_zh/langsmith/view-usage.mdx', 'view-usage'),
    ('src/langsmith/vitest-jest.mdx', 'docs_zh/langsmith/vitest-jest.mdx', 'vitest-jest'),
    ('src/langsmith/workload-isolation.mdx', 'docs_zh/langsmith/workload-isolation.mdx', 'workload-isolation'),
    ('src/langsmith/write-prompt-with-ai.mdx', 'docs_zh/langsmith/write-prompt-with-ai.mdx', 'write-prompt-with-ai'),
]

if __name__ == '__main__':
    count = 0
    for src, dst, key in files_to_translate_batch6:
        if os.path.exists(dst):
            print(f'Skipping existing: {dst}')
            continue
        if key in translations_batch6:
            translate_file(src, dst, translations_batch6[key])
            count += 1
    print(f'Translated {count} files')