#!/usr/bin/env python
import os
import sys

def translate_file(src_path, dst_path, translations):
    with open(src_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for eng, chn in translations.items():
        content = content.replace(eng, chn)

    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Translated: {src_path} -> {dst_path}')

# Translation mappings for mastra, microsoft, mistral
translations_batch2 = {
    'trace-with-mastra': {
        'Trace Mastra applications': '追踪 Mastra 应用程序',
        '[Mastra](https://mastra.ai/docs) is a TypeScript framework for building AI-powered applications and agents. Using Mastra\'s [LangSmith exporter](https://mastra.ai/docs/observability/ai-tracing/exporters/langsmith), you can send traces from your Mastra agents and workflows to LangSmith for debugging, evaluation, and observability.': '[Mastra](https://mastra.ai/docs) 是一个用于构建 AI 驱动应用程序和智能体的 TypeScript 框架。使用 Mastra 的 [LangSmith 导出器](https://mastra.ai/docs/observability/ai-tracing/exporters/langsmith)，您可以将 Mastra 智能体和工作流的追踪发送到 LangSmith 进行调试、评估和可观测性。',
        'This guide shows you how to integrate Mastra with LangSmith using Mastra\'s AI tracing system.': '本指南向您展示如何使用 Mastra 的 AI 追踪系统将 Mastra 与 LangSmith 集成。',
        '## Installation': '## 安装',
        'Install Mastra and the LangSmith exporter:': '安装 Mastra 和 LangSmith 导出器：',
        '## Setup': '## 设置',
        '1. Set your LangSmith API key and (optionally) a LangSmith project name:': '1. 设置您的 LangSmith API 密钥和（可选）LangSmith 项目名称：',
        'If [`LANGCHAIN_PROJECT`](/langsmith/log-traces-to-project) is not set, traces will be sent to the default project.': '如果未设置 [`LANGCHAIN_PROJECT`](/langsmith/log-traces-to-project)，追踪将被发送到默认项目。',
        '1. If you plan to use OpenAI models, also ensure you have an OpenAI API key available at runtime:': '1. 如果您计划使用 OpenAI 模型，还请确保在运行时有 OpenAI API 密钥可用：',
        '1. In your project directory, create the following project structure and files:': '1. 在您的项目目录中，创建以下项目结构和文件：',
        '## Configure Mastra with the LangSmith exporter': '## 使用 LangSmith 导出器配置 Mastra',
        'Mastra tracing is configured directly on the `Mastra` constructor. Add the following to a `mastra.ts` file:': 'Mastra 追踪直接在 `Mastra` 构造函数上配置。将以下内容添加到 `mastra.ts` 文件中：',
        '- [Storage is required for tracing](https://mastra.ai/docs/observability/ai-tracing/overview#basic-config) (even when exporting traces externally).': '- [存储是追踪所需的](https://mastra.ai/docs/observability/ai-tracing/overview#basic-config)（即使外部导出追踪）。',
        '- The LangSmith exporter reads credentials from environment variables.': '- LangSmith 导出器从环境变量读取凭据。',
        '- The [deprecated telemetry system](https://mastra.ai/docs/observability/overview#otel-tracing-deprecated) is disabled to avoid warnings.': '- [已弃用的遥测系统](https://mastra.ai/docs/observability/overview#otel-tracing-deprecated)被禁用以避免警告。',
        '- No separate instrumentation file is required when running Mastra outside of the Mastra server.': '- 在 Mastra 服务器外部运行 Mastra 时，不需要单独的检测文件。',
        'For more details, refer to the [Mastra docs](https://mastra.ai/docs/observability/ai-tracing/overview).': '有关更多详细信息，请参阅 [Mastra 文档](https://mastra.ai/docs/observability/ai-tracing/overview)。',
        '### Define an agent': '### 定义智能体',
        'For compatibility, use [string-based model identifiers](https://mastra.ai/models#basic-usage). Add the following code to an `agent.ts` file:': '为保持兼容性，请使用[基于字符串的模型标识符](https://mastra.ai/models#basic-usage)。将以下代码添加到 `agent.ts` 文件中：',
        'Mastra will automatically route the model call using your configured API keys and capture traces for each invocation.': 'Mastra 将自动使用您配置的 API 密钥路由模型调用，并捕获每次调用的追踪。',
        '### Run the agent': '### 运行智能体',
        '1. Add the following to an `index.ts` file:': '1. 将以下内容添加到 `index.ts` 文件中：',
        '1. Run your application:': '1. 运行您的应用程序：',
        '## View traces in LangSmith': '## 在 LangSmith 中查看追踪',
        'After running the agent:': '运行智能体后：',
        '1. Open the [LangSmith UI](https://smith.langchain.com).': '1. 打开 [LangSmith UI](https://smith.langchain.com)。',
        '1. Select your project. For example, the value of `LANGCHAIN_PROJECT`.': '1. 选择您的项目。例如，`LANGCHAIN_PROJECT` 的值。',
        '1. Locate the trace corresponding to `echoAgent.generate`.': '1. 找到与 `echoAgent.generate` 对应的追踪。',
        'You\'ll be able to inspect:': '您将能够检查：',
        '- Model inputs and outputs': '- 模型输入和输出',
        '- Agent execution steps': '- 智能体执行步骤',
        '- Timing and error information': '- 时间和错误信息',
    },
    'trace-with-microsoft-agent-framework': {
        'Trace Microsoft Agent Framework applications': '追踪 Microsoft Agent Framework 应用程序',
        'LangSmith can capture traces generated by [Microsoft Agent Framework](https://learn.microsoft.com/en-us/agent-framework/overview/agent-framework-overview) using its built-in OpenTelemetry instrumentation. This guide shows you how to automatically capture traces from your Microsoft Agent Framework agents and send them to LangSmith for monitoring and analysis.': 'LangSmith 可以使用其内置的 OpenTelemetry 检测来捕获由 [Microsoft Agent Framework](https://learn.microsoft.com/en-us/agent-framework/overview/agent-framework-overview) 生成的追踪。本指南向您展示如何自动捕获 Microsoft Agent Framework 智能体中的追踪，并将其发送到 LangSmith 进行监控和分析。',
        '## Installation': '## 安装',
        'Install the required packages:': '安装所需的包：',
        '## Setup': '## 设置',
        '### 1. Configure environment variables': '### 1. 配置环境变量',
        'Enable OpenTelemetry instrumentation of the agent and set the OpenTelemetry environment variables to point to the LangSmith OTEL endpoint:': '启用智能体的 OpenTelemetry 检测，并设置 OpenTelemetry 环境变量以指向 LangSmith OTEL 端点：',
        '### 2. Enable OpenTelemetry in your application': '### 2. 在您的应用程序中启用 OpenTelemetry',
        'In your Microsoft Agent Framework application, enable OpenTelemetry tracing using the built-in `configure_otel_providers` function:': '在您的 Microsoft Agent Framework 应用程序中，使用内置的 `configure_otel_providers` 函数启用 OpenTelemetry 追踪：',
        'Setting `enable_sensitive_data=True` allows capturing input and output content in traces. Set to `False` if you want to exclude sensitive data from traces.': '设置 `enable_sensitive_data=True` 允许在追踪中捕获输入和输出内容。如果要排除追踪中的敏感数据，请设置为 `False`。',
        '### 3. Create and run your agent': '### 3. 创建并运行您的智能体',
        'Once configured, your Microsoft Agent Framework agents will automatically send traces to LangSmith:': '配置完成后，您的 Microsoft Agent Framework 智能体将自动向 LangSmith 发送追踪：',
    },
    'trace-with-mistral': {
        'Trace Mistral applications': '追踪 Mistral 应用程序',
        '[Mistral](https://mistral.ai/) provides hosted access to open-weight language models via a simple API.': '[Mistral](https://mistral.ai/) 通过简单的 API 提供对开放权重语言模型的托管访问。',
        'This guide shows you how to trace Mistral API calls with LangSmith, allowing you to record prompts, responses, and metadata for debugging and observability. Traces are sent directly to LangSmith using the @[LangSmith SDK][langsmith] and standard span instrumentation.': '本指南向您展示如何使用 LangSmith 追踪 Mistral API 调用，允许您记录提示词、响应和元数据以进行调试和可观测性。追踪使用 @[LangSmith SDK][langsmith] 和标准跨度检测直接发送到 LangSmith。',
        '## Installation': '## 安装',
        'Install Mistral\'s official library and LangSmith:': '安装 Mistral 的官方库和 LangSmith：',
        '`mistralai` provides a Mistral client for interacting with Mistral\'s API.': '`mistralai` 提供了一个用于与 Mistral API 交互的 Mistral 客户端。',
        '## Setup': '## 设置',
        'Set your [API keys](/langsmith/create-account-api-key) and project name:': '设置您的 [API 密钥](/langsmith/create-account-api-key) 和项目名称：',
        '- Ensure you have a Mistral API key from your [Mistral AI account](https://v2.auth.mistral.ai/login) (set this as `MISTRAL_API_KEY`).': '- 确保您有来自您的 [Mistral AI 账户](https://v2.auth.mistral.ai/login) 的 Mistral API 密钥（将其设置为 `MISTRAL_API_KEY`）。',
        '- Set `LANGSMITH_TRACING=true` and provide your LangSmith API key (`LANGSMITH_API_KEY`) activates automatic logging of traces.': '- 设置 `LANGSMITH_TRACING=true` 并提供您的 LangSmith API 密钥（`LANGSMITH_API_KEY`）可激活追踪的自动记录。',
        '- Specify a [`LANGSMITH_PROJECT`](/langsmith/log-traces-to-project) name to organize traces by project; if not set, traces go to the default project (named "default").': '- 指定 [`LANGSMITH_PROJECT`](/langsmith/log-traces-to-project) 名称以按项目组织追踪；如果未设置，追踪将进入默认项目（名为"default"）。',
        '- The `LANGSMITH_TRACING` flag must be true for any traces to be recorded.': '- `LANGSMITH_TRACING` 标志必须为真才能记录任何追踪。',
        '## Configure tracing': '## 配置追踪',
        '1. Instrument the Mistral API call with LangSmith. In your script, create a Mistral client and wrap a call in a traced function:': '1. 使用 LangSmith 检测 Mistral API 调用。在您的脚本中，创建一个 Mistral 客户端并在追踪函数中包装调用：',
        'In this example, you use the [Mistral SDK](https://docs.mistral.ai/getting-started/clients) to send a chat completion request (with a user prompt) and retrieve the model\'s answer.': '在此示例中，您使用 [Mistral SDK](https://docs.mistral.ai/getting-started/clients) 发送聊天完成请求（带有用户提示词）并检索模型的答案。',
        'The @[`@traceable`][traceable] decorator (from the @[LangSmith Python SDK][langsmith-python]) wraps the `query_mistral` function so that each invocation is logged as a trace run of type `"llm"`. The `metadata={"ls_provider": "mistral", "ls_model_name": "mistral-medium-latest"}` tags the trace with the provider (Mistral) and model name.': '@[`@traceable`][traceable] 装饰器（来自 @[LangSmith Python SDK][langsmith-python]）包装了 `query_mistral` 函数，以便每次调用都作为类型为 `"llm"` 的追踪运行记录。`metadata={"ls_provider": "mistral", "ls_model_name": "mistral-medium-latest"}` 使用提供商（Mistral）和模型名称标记追踪。',
        'You can also refer to the @[LangSmith JavaScript SDK][langsmith-js].': '您也可以参阅 @[LangSmith JavaScript SDK][langsmith-js]。',
        '1. Execute your script to generate a trace. For example:': '1. 执行您的脚本以生成追踪。例如：',
        'The `query_mistral("Hello, how are you?")` call will reach out to the Mistral API, and because of the `@traceable`/`traceable` wrapper, LangSmith will log this call\'s inputs and outputs as a new trace. You\'ll find the model\'s response printed to the console, and a corresponding run appear in [LangSmith](https://smith.langchain.com).': '`query_mistral("Hello, how are you?")` 调用将访问 Mistral API，由于 `@traceable`/`traceable` 包装器，LangSmith 将此调用的输入和输出记录为新的追踪。您会在控制台中看到模型的响应打印出来，相应的运行会出现在 [LangSmith](https://smith.langchain.com) 中。',
        '## View traces in LangSmith': '## 在 LangSmith 中查看追踪',
        'After running the example, you can inspect the recorded traces in the [LangSmith UI](https://smith.langchain.com):': '运行示例后，您可以在 [LangSmith UI](https://smith.langchain.com) 中检查记录的追踪：',
        '1. Open the LangSmith UI and log in to your account.': '1. 打开 LangSmith UI 并登录您的账户。',
        '1. Select the project you used for this integration (for example, the name set in `LANGSMITH_PROJECT`, or default if you didn\'t set one).': '1. 选择您用于此集成的项目（例如，在 `LANGSMITH_PROJECT` 中设置的名称，或者如果您没有设置，则为 default）。',
        '1. Find the trace corresponding to your Mistral API call. It will be identified by the function name (`query_mistral`) or a custom name if provided.': '1. 找到与您的 Mistral API 调用对应的追踪。它将由函数名（`query_mistral`）或自定义名称（如果提供）标识。',
        '1. Click on the trace to open it. You\'ll be able to inspect the model input and output, including the prompt messages you sent and the response from Mistral, as well as timing information (latency) and any error details if the call failed.': '1. 点击追踪将其打开。您将能够检查模型输入和输出，包括您发送的提示词消息和来自 Mistral 的响应，以及时间信息（延迟）和调用失败时的任何错误详情。',
        'With LangSmith\'s tracing, you have full visibility into your Mistral calls—allowing you to debug the behavior of Mistral\'s models, monitor performance (e.g., response time and token usage), and compare runs with different parameters using the metadata tags.': '使用 LangSmith 的追踪，您可以完全了解您的 Mistral 调用——使您能够调试 Mistral 模型的行为、监控性能（例如响应时间和令牌使用情况），并使用元数据标签比较具有不同参数的运行。',
        '## Cost tracking': '## 成本追踪',
        'Although Mistral models are open-weight, using the hosted Mistral API may incur usage-based costs depending on your plan.': '虽然 Mistral 模型是开放权重的，但使用托管的 Mistral API 可能会根据您的计划产生基于使用量的成本。',
        'LangSmith can automatically associate costs with traced LLM calls by estimating token usage and applying model-specific pricing. When tracing Mistral API calls, LangSmith uses the recorded prompt and response messages to calculate token counts and attach cost information to each run.': 'LangSmith 可以通过估算令牌使用量并应用特定于模型的定价来自动将成本与追踪的大型语言模型调用关联。在追踪 Mistral API 调用时，LangSmith 使用记录的提示词和响应消息来计算令牌计数并将成本信息附加到每次运行。',
        'To enable automatic cost tracking for LLM calls, refer to [Automatically track costs based on token counts](/langsmith/cost-tracking#llm-calls:-automatically-track-costs-based-on-token-counts).': '要启用大型语言模型调用的自动成本追踪，请参阅[根据令牌计数自动追踪成本](/langsmith/cost-tracking#llm-calls:-automatically-track-costs-based-on-token-counts)。',
        'Once enabled, costs appear directly in the LangSmith UI alongside each traced Mistral run, so that you can monitor usage and compare experiments over time.': '启用后，成本直接显示在 LangSmith UI 中以及每个追踪的 Mistral 运行旁边，以便您可以监控使用情况并随时间比较实验。',
    },
}

files_to_translate_batch2 = [
    ('src/langsmith/trace-with-mastra.mdx', 'docs_zh/langsmith/trace-with-mastra.mdx', 'trace-with-mastra'),
    ('src/langsmith/trace-with-microsoft-agent-framework.mdx', 'docs_zh/langsmith/trace-with-microsoft-agent-framework.mdx', 'trace-with-microsoft-agent-framework'),
    ('src/langsmith/trace-with-mistral.mdx', 'docs_zh/langsmith/trace-with-mistral.mdx', 'trace-with-mistral'),
]

if __name__ == '__main__':
    count = 0
    for src, dst, key in files_to_translate_batch2:
        if os.path.exists(dst):
            print(f'Skipping existing: {dst}')
            continue
        if key in translations_batch2:
            translate_file(src, dst, translations_batch2[key])
            count += 1
    print(f'Translated {count} files')