#!/usr/bin/env python
import os
import sys

def translate_file(src_path, dst_path, translations):
    with open(src_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for eng, chn in translations.items():
        content = content.replace(eng, chn)

    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Translated: {src_path} -> {dst_path}')

# Translation mappings for batch5
translations_batch5 = {
    'upload-files-with-traces': {
        'Upload files with traces': '通过追踪上传文件',
        'When you trace with the [`@traceable` decorator or `traceable` wrapper](/langsmith/annotate-code#use-%40traceable-%2F-traceable), LangSmith supports uploading binary files (such as images, audio, videos, PDFs, and CSVs) alongside your traces. This is particularly useful when working with LLM pipelines using multimodal inputs or outputs.': '当您使用 [`@traceable` 装饰器或 `traceable` 包装器](/langsmith/annotate-code#use-%40traceable-%2F-traceable) 进行追踪时，LangSmith 支持与追踪一起上传二进制文件（如图像、音频、视频、PDF 和 CSV）。这在使用具有多模态输入或输出的大型语言模型流水线时特别有用。',
        'In both the [Python](#python) and [TypeScript](#typescript) SDKs, you can add attachments to your traces by specifying the MIME type and binary content of each file. This page explains how to define and trace attachments using the `Attachment` type in Python and `Uint8Array` / `ArrayBuffer` in TypeScript.': '在 [Python](#python) 和 [TypeScript](#typescript) SDK 中，您可以通过指定每个文件的 MIME 类型和二进制内容来向追踪添加附件。本页说明如何使用 Python 中的 `Attachment` 类型和 TypeScript 中的 `Uint8Array` / `ArrayBuffer` 来定义和追踪附件。',
        '## Python': '## Python',
        'In the [Python SDK](/langsmith/smith-python-sdk), you can use the `Attachment` type to add files to your traces. Each `Attachment` requires:': '在 [Python SDK](/langsmith/smith-python-sdk) 中，您可以使用 `Attachment` 类型向追踪添加文件。每个 `Attachment` 需要：',
        '- `mime_type` (str): The MIME type of the file (e.g., `"image/png"`).': '- `mime_type` (str)：文件的 MIME 类型（例如 `"image/png"`）。',
        '- `data` (bytes | Path): The binary content of the file, or the file path.': '- `data` (bytes | Path)：文件的二进制内容，或文件路径。',
        'You can also define an attachment with a tuple of the form `(mime_type, data)` for convenience.': '您也可以使用形式为 `(mime_type, data)` 的元组来定义附件以方便使用。',
        'There are two ways to provide file data:': '提供文件数据有两种方法：',
        '- Load the bytes yourself and pass them directly (works in all environments), or': '- 自己加载字节并直接传递（适用于所有环境），或',
        '- Pass a `Path` object and let the SDK read the file by setting `dangerously_allow_filesystem=True` on your `@traceable` decorator.': '- 传递一个 `Path` 对象，并通过在您的 `@traceable` 装饰器上设置 `dangerously_allow_filesystem=True` 让 SDK 读取文件。',
        '<Note>': '<Note>',
        'The `dangerously_allow_filesystem` flag exists as a safeguard for server and multi-tenant environments, where user-controlled input could influence a file path. In a trusted environment (a local script or a controlled pipeline where you own the file paths), it is safe to enable.': '`dangerously_allow_filesystem` 标志是作为服务器和多租户环境的保护措施而存在的，在这些环境中，用户控制的输入可能会影响文件路径。在受信任的环境中（本地脚本或您拥有文件路径的受控流水线），启用它是安全的。',
        'Decorate a function with `@traceable` and include your `Attachment` instances as arguments. The following example demonstrates both approaches: loading file bytes manually into an `Attachment`, and passing a `Path` object with `dangerously_allow_filesystem=True`:': '使用 `@traceable` 装饰函数，并将您的 `Attachment` 实例作为参数包含。以下示例演示了两种方法：手动将文件字节加载到 `Attachment` 中，以及传递带有 `dangerously_allow_filesystem=True` 的 `Path` 对象：',
        '## TypeScript': '## TypeScript',
        'In the [TypeScript SDK](/langsmith/smith-js-ts-sdk), you can add attachments to traces by using `Uint8Array` or `ArrayBuffer` as data types. Each attachment\'s MIME type is specified within `extractAttachments`:': '在 [TypeScript SDK](/langsmith/smith-js-ts-sdk) 中，您可以使用 `Uint8Array` 或 `ArrayBuffer` 作为数据类型向追踪添加附件。每个附件的 MIME 类型在 `extractAttachments` 中指定：',
        '- `Uint8Array`: Useful for handling binary data directly.': '- `Uint8Array`：用于直接处理二进制数据。',
        '- `ArrayBuffer`: Represents fixed-length binary data, which you can convert to `Uint8Array` as needed.': '- `ArrayBuffer`：表示固定长度的二进制数据，您可以根据需要将其转换为 `Uint8Array`。',
        '<Note>': '<Note>',
        'You cannot directly pass in a file path in the TypeScript SDK, because accessing local files is not supported in all runtime environments.': '您不能在 TypeScript SDK 中直接传入文件路径，因为在所有运行时环境中都不支持访问本地文件。',
        'Wrap your function with `traceable` and include your attachments within the `extractAttachments` option.': '使用 `traceable` 包装您的函数，并在 `extractAttachments` 选项中包含您的附件。',
        '## Related': '## 相关内容',
        '- [Manage datasets](/langsmith/manage-datasets)': '- [管理数据集](/langsmith/manage-datasets)',
        '- [Set up LLM-as-a-judge online evaluators](/langsmith/online-evaluations-llm-as-judge)': '- [设置大型语言模型作为评判者在线评估器](/langsmith/online-evaluations-llm-as-judge)',
    },
    'use-remote-graph': {
        'How to interact with a deployment using RemoteGraph': '如何使用 RemoteGraph 与部署交互',
        '@[`RemoteGraph`] is a client-side interface that allows you to interact with your [deployment](/langsmith/deployment) as if it were a local graph. It provides API parity with [`CompiledGraph`](/oss/langgraph/graph-api#compiling-your-graph), which means that you can use the same methods (`invoke()`, `stream()`, `get_state()`, etc.) in your development and production environments. This page describes how to initialize a `RemoteGraph` and interact with it.': '@[`RemoteGraph`] 是一个客户端接口，允许您像本地图一样与您的[部署](/langsmith/deployment)进行交互。它与 [`CompiledGraph`](/oss/langgraph/graph-api#compiling-your-graph) 提供 API 对等性，这意味着您可以在开发和生产环境中使用相同的方法（`invoke()`、`stream()`、`get_state()` 等）。本页面描述如何初始化 `RemoteGraph` 并与之交互。',
        '`RemoteGraph` is useful for the following:': '`RemoteGraph` 用于以下场景：',
        '- Separation of development and deployment: Build and test a graph locally with `CompiledGraph`, deploy it to LangSmith, and then [use `RemoteGraph`](#initialize-the-graph) to call it in production while working with the same API interface.': '- 开发和部署分离：使用 `CompiledGraph` 在本地构建和测试图，将其部署到 LangSmith，然后[使用 `RemoteGraph`](#initialize-the-graph) 在生产环境中调用它，同时使用相同的 API 接口。',
        '- Thread-level persistence: [Persist and fetch the state](#persist-state-at-the-thread-level) of a conversation across calls with a thread ID.': '- 线程级持久化：跨调用[持久化和获取](#persist-state-at-the-thread-level)对话状态，并带有线程 ID。',
        '- Subgraph embedding: Compose modular graphs for a multi-agent workflow by embedding a `RemoteGraph` as a [subgraph](#use-as-a-subgraph) within another graph.': '- 子图嵌入：通过将 `RemoteGraph` 作为[子图](#use-as-a-subgraph)嵌入到另一个图中，为多智能体工作流组合模块化图。',
        '- Reusable workflows: Use deployed graphs as nodes or @[tools][RemoteGraph.as_tool], so that you can reuse and expose complex logic.': '- 可重用工作流：将部署的图用作节点或 @[工具][RemoteGraph.as_tool]，以便您可以重用和公开复杂逻辑。',
        '<Warning>': '<Warning>',
        '**Important: Avoid calling the same deployment**': '**重要：避免调用同一部署**',
        '`RemoteGraph` is designed to call graphs on other deployments. Do not use `RemoteGraph` to call itself or another graph on the same deployment, as this can lead to deadlocks and resource exhaustion. Instead, use local graph composition or [subgraphs](/oss/langgraph/use-subgraphs) for graphs within the same deployment.': '`RemoteGraph` 旨在调用其他部署上的图。不要使用 `RemoteGraph` 调用自身或同一部署上的另一个图，因为这可能导致死锁和资源耗尽。请改用本地图组合或[子图](/oss/langgraph/use-subgraphs)来处理同一部署内的图。',
        '## Prerequisites': '## 前置条件',
        'Before getting started with `RemoteGraph`, make sure you have:': '在开始使用 `RemoteGraph` 之前，请确保您拥有：',
        '- Access to [LangSmith](/langsmith/home), where your graphs are developed and managed.': '- 访问 [LangSmith](/langsmith/home)，您的图在此开发和管理。',
        '- A running [Agent Server](/langsmith/agent-server), which hosts your deployed graphs for remote interaction.': '- 一个正在运行的 [Agent Server](/langsmith/agent-server)，它托管您的部署图以供远程交互。',
        '## Initialize the graph': '## 初始化图',
        'When initializing a `RemoteGraph`, you must always specify:': '初始化 `RemoteGraph` 时，您必须始终指定：',
        '- `name`: The name of the graph you want to interact with **or** an assistant ID. If you specify a graph name, the default assistant will be used. If you specify an assistant ID, that specific assistant will be used. The graph name is the same name you use in the `langgraph.json` configuration file for your deployment.': '- `name`：您想要交互的图的名称 **或** 助手 ID。如果您指定图名称，将使用默认助手。如果您指定助手 ID，将使用该特定助手。图名称是您在部署的 `langgraph.json` 配置文件中使用的相同名称。',
        '- `api_key`: A valid [LangSmith API key](/langsmith/create-account-api-key). You can set as an environment variable (`LANGSMITH_API_KEY`) or pass directly in the `api_key` argument. You can also provide the API key in the `client` / `sync_client` arguments, if `LangGraphClient` / `SyncLangGraphClient` was initialized with the `api_key` argument.': '- `api_key`：一个有效的 [LangSmith API 密钥](/langsmith/create-account-api-key)。您可以将其设置为环境变量（`LANGSMITH_API_KEY`）或直接在 `api_key` 参数中传递。如果 `LangGraphClient` / `SyncLangGraphClient` 是用 `api_key` 参数初始化的，您也可以在 `client` / `sync_client` 参数中提供 API 密钥。',
        'Additionally, you have to provide one of the following:': '此外，您必须提供以下之一：',
        '- [`url`](#use-a-url): The URL of the deployment you want to interact with. If you pass the `url` argument, both sync and async clients will be created using the provided URL, headers (if provided), and default configuration values (e.g., timeout).': '- [`url`](#use-a-url)：您想要交互的部署的 URL。如果您传递 `url` 参数，将使用提供的 URL、头（如果提供）和默认配置值（如超时）创建同步和异步客户端。',
        '- [`client`](#use-a-client): A `LangGraphClient` instance for interacting with the deployment asynchronously (e.g., using `.astream()`, `.ainvoke()`, `.aget_state()`, `.aupdate_state()`).': '- [`client`](#use-a-client)：一个 `LangGraphClient` 实例，用于与部署进行异步交互（例如使用 `.astream()`、`.ainvoke()`、`.aget_state()`、`.aupdate_state()`）。',
        '- `sync_client`: A `SyncLangGraphClient` instance for interacting with the deployment synchronously (e.g., using `.stream()`, `.invoke()`, `.get_state()`, `.update_state()`).': '- `sync_client`：一个 `SyncLangGraphClient` 实例，用于与部署进行同步交互（例如使用 `.stream()`、`.invoke()`、`.get_state()`、`.update_state()`）。',
        '<Note>': '<Note>',
        'If you pass both `client` or `sync_client` as well as the `url` argument, they will take precedence over the `url` argument. If none of the `client` / `sync_client` / `url` arguments are provided, `RemoteGraph` will raise a `ValueError` at runtime.': '如果您同时传递 `client` 或 `sync_client` 以及 `url` 参数，它们将优先于 `url` 参数。如果未提供 `client` / `sync_client` / `url` 参数，`RemoteGraph` 将在运行时引发 `ValueError`。',
        '### Use a URL': '### 使用 URL',
        '### Use a client': '### 使用客户端',
        '## Invoke the graph': '## 调用图',
        '`RemoteGraph` implements the same Runnable interface as `CompiledGraph`, so you can use it in the same way as a compiled graph. It supports the full set of standard methods, including `.invoke()`, `.stream()`, `.get_state()`, and `.update_state()`, as well as their asynchronous variants.': '`RemoteGraph` 实现与 `CompiledGraph` 相同的 Runnable 接口，因此您可以以与编译图相同的方式使用它。它支持全套标准方法，包括 `.invoke()`、`.stream()`、`.get_state()` 和 `.update_state()` 及其异步变体。',
        '### Asynchronously': '### 异步',
        '<Note>': '<Note>',
        'To use the graph asynchronously, you must provide either the `url` or `client` when initializing the `RemoteGraph`.': '要异步使用图，您必须在初始化 `RemoteGraph` 时提供 `url` 或 `client`。',
        '### Synchronously': '### 同步',
        '<Note>': '<Note>',
        'To use the graph synchronously, you must provide either the `url` or `sync_client` when initializing the `RemoteGraph`.': '要同步使用图，您必须在初始化 `RemoteGraph` 时提供 `url` 或 `sync_client`。',
        '## Persist state at the thread level': '## 在线程级别持久化状态',
        'By default, graph runs (for example, calls made with `.invoke()` or `.stream()`) are stateless, which means that intermediate checkpoints and the final state are not persisted after a run.': '默认情况下，图运行（例如使用 `.invoke()` 或 `.stream()` 进行的调用）是无状态的，这意味着运行后不会持久化中间检查点和最终状态。',
        'If you want to preserve the outputs of a run—for example, to support human-in-the-loop workflows—you can create a thread and pass its ID through the `config` argument. This works the same way as with a regular compiled graph:': '如果您想保留运行的输出（例如，支持人机交互工作流），您可以创建一个线程并通过 `config` 参数传递其 ID。这与常规编译图的工作方式相同：',
        '## Use as a subgraph': '## 用作子图',
        '<Note>': '<Note>',
        'If you need to use a `checkpointer` with a graph that has a `RemoteGraph` subgraph node, make sure to use UUIDs as thread IDs.': '如果您需要将 `checkpointer` 与具有 `RemoteGraph` 子图节点的图一起使用，请确保使用 UUID 作为线程 ID。',
        'A graph can also call out to multiple `RemoteGraph` instances as [_subgraph_](/oss/langgraph/use-subgraphs) nodes. This allows for modular, scalable workflows where different responsibilities are split across separate graphs.': '图也可以调用多个 `RemoteGraph` 实例作为[_子图_](/oss/langgraph/use-subgraphs)节点。这允许模块化、可扩展的工作流，其中不同的职责被拆分到不同的图中。',
        '`RemoteGraph` exposes the same interface as a regular `CompiledGraph`, so you can use it directly as a subgraph inside another graph. For example:': '`RemoteGraph` 公开与常规 `CompiledGraph` 相同的接口，因此您可以直接将其用作另一个图中的子图。例如：',
    },
    'use-threads': {
        'Use threads': '使用线程',
        'This guide shows you how to create, view, and inspect _threads_. Threads work with [assistants](/langsmith/assistants) to enable [stateful](/oss/langgraph/persistence) execution of your [deployed graphs](/langsmith/deployment).': '本指南向您展示如何创建、查看和检查_线程_。线程与[助手](/langsmith/assistants)协同工作，以实现[部署图](/langsmith/deployment)的[有状态](/oss/langgraph/persistence)执行。',
        '## Understand threads': '## 了解线程',
        'A thread is a persistent conversation container that maintains state across multiple runs. Each time you execute a run on a thread, the graph processes the input with the thread\'s current state and updates that state with new information.': '线程是一个持久的对话容器，在多次运行中维护状态。每次在线程上执行运行时，图会使用线程的当前状态处理输入，并用新信息更新该状态。',
        'Threads enable stateful interactions by preserving conversation history and context between runs. Without threads, each run would be stateless, with no memory of previous interactions. Threads are particularly useful for:': '线程通过在运行之间保留对话历史和上下文来实现有状态的交互。没有线程，每次运行都是无状态的，没有对先前交互的记忆。线程特别适用于：',
        '- Multi-turn conversations where the assistant needs to remember what was discussed.': '- 需要助手记住所讨论内容的多轮对话。',
        '- Long-running tasks that require maintaining context across multiple steps.': '- 需要在多个步骤中维护上下文的长时间运行的任务。',
        '- User-specific state management where each user has their own conversation history.': '- 每个用户都有自己的对话历史的用户特定状态管理。',
        'The diagram illustrates how a thread maintains state across two runs. The second run has access to the messages from the first run, allowing the assistant to understand that the context of "What about tomorrow?" refers to the weather query from the first run:': '该图说明线程如何在两次运行中维护状态。第二次运行可以访问第一次运行的消息，使助手能够理解"明天怎么样？"的上下文指的是第一次运行的天气查询：',
        '- A thread maintains a persistent conversation with a unique thread ID.': '- 线程维护一个具有唯一线程 ID 的持久对话。',
        '- Each run applies the assistant\'s configuration to the graph execution.': '- 每次运行将助手的配置应用于图执行。',
        '- State is updated after each run and persists for subsequent runs.': '- 状态在每次运行后更新，并为后续运行保留。',
        '- Later runs have access to the full conversation history.': '- 后续运行可以访问完整的对话历史。',
        '<Note>': '<Note>',
        '- **[Assistants](/langsmith/assistants)** define the configuration (model, prompts, tools) for how your graph executes. When creating a run, you can specify either a **graph ID** (e.g., `"agent"`) to use the default assistant, or an **assistant ID** (UUID) to use a specific configuration.': '- **[助手](/langsmith/assistants)** 定义图执行的配置（模型、提示词、工具）。创建运行时，您可以指定**图 ID**（例如 `"agent"`）以使用默认助手，或指定**助手 ID**（UUID）以使用特定配置。',
        '- **Threads** maintain the state and conversation history.': '- **线程**维护状态和对话历史。',
        '- **Runs** combine an assistant and thread to execute your graph with a specific configuration and state.': '- **运行**将助手和线程组合起来，以特定配置和状态执行您的图。',
        '<Tip>': '<Tip>',
        'Best practice: When tracing runs in a thread (conversation), ensure that `thread_id` is set on all runs—both parent and child runs. This is required for thread filtering, token counting, and thread-level evaluations to work correctly.': '最佳实践：当在线程（对话）中追踪运行时，确保在所有运行（父运行和子运行）上设置 `thread_id`。这是线程过滤、令牌计数和线程级评估正常工作的必要条件。',
        '## Create a thread': '## 创建线程',
        'To run your graph with state persistence, you must first create a thread:': '要使用状态持久化运行您的图，您必须首先创建一个线程：',
        '### Empty thread': '### 空线程',
        'To create a new thread, use one of:': '要创建新线程，请使用以下方法之一：',
        'For more information, refer to the @[Python][ThreadsClient.create] and @[JS][ThreadsClient.create] SDK docs, or the [REST API](/langsmith/agent-server-api/threads/create-thread) reference.': '有关更多信息，请参阅 @[Python][ThreadsClient.create] 和 @[JS][ThreadsClient.create] SDK 文档，或 [REST API](/langsmith/agent-server-api/threads/create-thread) 参考。',
        '### Copy thread': '### 复制线程',
        'Alternatively, if you already have a thread in your application whose state you wish to copy, you can use the `copy` method. This will create an independent thread whose history is identical to the original thread at the time of the operation:': '或者，如果您已经有了一个要复制其状态的线程，您可以使用 `copy` 方法。这将创建一个独立线程，其历史与操作时原始线程的历史相同：',
        'For more information, refer to the @[Python][ThreadsClient.copy] and @[JS][ThreadsClient.copy] SDK docs, or the [REST API](/langsmith/agent-server-api/threads/copy-thread) reference.': '有关更多信息，请参阅 @[Python][ThreadsClient.copy] 和 @[JS][ThreadsClient.copy] SDK 文档，或 [REST API](/langsmith/agent-server-api/threads/copy-thread) 参考。',
        '### Prepopulated state': '### 预填充状态',
        'You can create a thread with an arbitrary pre-defined state by providing a list of `supersteps` into the `create` method. The `supersteps` describe a sequence of state updates that establish the initial state of the thread. This is useful when you want to:': '您可以通过在 `create` 方法中提供 `supersteps` 列表来创建具有任意预定义状态的线程。`supersteps` 描述了建立线程初始状态的状态更新序列。当您想要以下操作时，这很有用：',
        '- Create a thread with existing conversation history.': '- 使用现有对话历史创建线程。',
        '- Migrate conversations from another system.': '- 从另一个系统迁移对话。',
        '- Set up test scenarios with specific initial states.': '- 使用特定初始状态设置测试场景。',
        '- Resume conversations from a previous session.': '- 从上一个会话恢复对话。',
        'For more information on checkpoints and state management, refer to the [LangGraph persistence documentation](/oss/langgraph/persistence).': '有关检查点和状态管理的更多信息，请参阅 [LangGraph 持久化文档](/oss/langgraph/persistence)。',
        '## List threads': '## 列出线程',
        'To list threads, use the `search` method. This will list the threads in the application that match the provided filters:': '要列出线程，请使用 `search` 方法。这将列出应用程序中与提供的过滤器匹配的线程：',
        '### Filter by thread status': '### 按线程状态过滤',
        'Use the `status` field to filter threads based on their status. Supported values are `idle`, `busy`, `interrupted`, and `error`. For example, to view `idle` threads:': '使用 `status` 字段根据线程状态进行过滤。支持的值有 `idle`、`busy`、`interrupted` 和 `error`。例如，要查看 `idle` 线程：',
        'For more information, refer to the @[Python][ThreadsClient.search] and @[JS][ThreadsClient.search] SDK docs, or the [REST API](/langsmith/agent-server-api/threads/search-threads) reference.': '有关更多信息，请参阅 @[Python][ThreadsClient.search] 和 @[JS][ThreadsClient.search] SDK 文档，或 [REST API](/langsmith/agent-server-api/threads/search-threads) 参考。',
        '### Filter by metadata': '### 按元数据过滤',
        'The `search` method allows you to filter on metadata. This is useful for finding threads associated with specific graphs, users, or custom metadata you\'ve added to threads.': '`search` 方法允许您按元数据进行过滤。这对于查找与特定图、用户或您添加到线程的自定义元数据关联的线程很有用。',
        'Common metadata fields you can filter on include:': '您可以过滤的常见元数据字段包括：',
        '| Metadata key | Description |': '| 元数据键 | 描述 |',
        '|---|---|': '|---|---',
        '| `graph_id` | The graph (deployment) the thread belongs to. |': '| `graph_id` | 线程所属的图（部署）。 |',
        '| `assistant_id` | The [assistant](/langsmith/assistants) used to create runs on the thread. |': '| `assistant_id` | 用于在线程上创建运行的[助手](/langsmith/assistants)。 |',
        '| `langgraph_auth_user_id` | The authenticated user who owns the thread (set automatically when using [custom auth](/langsmith/custom-auth)). |': '| `langgraph_auth_user_id` | 拥有线程的已认证用户（使用[自定义认证](/langsmith/custom-auth)时自动设置）。 |',
        '| `cron_id` | The [cron job](/langsmith/cron-jobs) that created runs on the thread. |': '| `cron_id` | 在线程上创建运行的[cron 作业](/langsmith/cron-jobs)。 |',
        'You can also filter on any custom metadata you attach when creating or updating threads.': '您还可以过滤在创建或更新线程时附加的任何自定义元数据。',
        '#### Filter by graph': '#### 按图过滤',
        '#### Filter by assistant': '#### 按助手过滤',
        '#### Filter by cron job': '#### 按 cron 作业过滤',
        '### Sorting': '### 排序',
        'The SDK also supports sorting threads by `thread_id`, `status`, `created_at`, and `updated_at` using the `sort_by` and `sort_order` parameters.': 'SDK 还支持使用 `sort_by` 和 `sort_order` 参数按 `thread_id`、`status`、`created_at` 和 `updated_at` 对线程进行排序。',
        '## Inspect threads': '## 检查线程',
        '### Get thread': '### 获取线程',
        'To view a specific thread given its `thread_id`, use the @[`get`][ThreadsClient.get] method:': '要查看给定其 `thread_id` 的特定线程，请使用 @[`get`][ThreadsClient.get] 方法：',
        'For more information, refer to the @[Python][ThreadsClient.get] and @[JS][ThreadsClient.get] SDK docs, or the [REST API](/langsmith/agent-server-api/threads/get-thread) reference.': '有关更多信息，请参阅 @[Python][ThreadsClient.get] 和 @[JS][ThreadsClient.get] SDK 文档，或 [REST API](/langsmith/agent-server-api/threads/get-thread) 参考。',
        '### Inspect thread state': '### 检查线程状态',
        'To view the current state of a given thread, use the @[`get_state`][ThreadsClient.get_state] method. This returns the current values, next nodes to execute, and checkpoint information:': '要查看给定线程的当前状态，请使用 @[`get_state`][ThreadsClient.get_state] 方法。这会返回当前值、要执行的下一个节点和检查点信息：',
        'For more information, refer to the @[Python][ThreadsClient.get_state] and @[JS][ThreadsClient.get_state] SDK docs, or the [REST API](/langsmith/agent-server-api/threads/get-thread-state) reference.': '有关更多信息，请参阅 @[Python][ThreadsClient.get_state] 和 @[JS][ThreadsClient.get_state] SDK 文档，或 [REST API](/langsmith/agent-server-api/threads/get-thread-state) 参考。',
        'Optionally, to view the state of a thread at a given checkpoint, pass in the checkpoint ID. This is useful for inspecting the thread state at a specific point in its execution history.': '或者，要查看线程在给定检查点的状态，请传入检查点 ID。这对于在执行历史的特定点检查线程状态很有用。',
        'First, get the checkpoint ID from the thread\'s history:': '首先，从线程的历史记录中获取检查点 ID：',
        'Then use the checkpoint ID to get the state at that specific point:': '然后使用检查点 ID 获取该特定点的状态：',
        '### Inspect full thread history': '### 检查完整线程历史',
        'To view a thread\'s history, use the @[`get_history`][ThreadsClient.get_history] method. This returns a list of every state the thread experienced, allowing you to trace the full execution path:': '要查看线程的历史记录，请使用 @[`get_history`][ThreadsClient.get_history] 方法。这会返回线程经历的每个状态的列表，允许您追踪完整的执行路径：',
        'This method is particularly useful for:': '此方法特别适用于：',
        '- Debugging execution flow by seeing how state evolved.': '- 通过查看状态如何演变来调试执行流。',
        '- Understanding decision points in your graph\'s execution.': '- 理解图中执行的决策点。',
        '- Auditing conversation history and state changes.': '- 审计对话历史和状态更改。',
        '- Replaying or analyzing past interactions.': '- 重放或分析过去的交互。',
        'For more information, refer to the @[Python][ThreadsClient.get_history] and @[JS][ThreadsClient.get_history] SDK docs, or the [REST API](/langsmith/agent-server-api/threads/get-thread-history) reference.': '有关更多信息，请参阅 @[Python][ThreadsClient.get_history] 和 @[JS][ThreadsClient.get_history] SDK 文档，或 [REST API](/langsmith/agent-server-api/threads/get-thread-history) 参考。',
    },
    'use-tools': {
        'Use tools in a prompt': '在提示词中使用工具',
        'Tools allow language models to interact with external systems and perform actions beyond just generating text. In the Playground, you can use two types of tools:': '工具允许语言模型与外部系统交互并执行超越生成文本的操作。在 Playground 中，您可以使用两种类型的工具：',
        '1. [**Built-in tools**](#built-in-tools): Pre-configured tools provided by model providers (like OpenAI and Anthropic) that are ready to use. Use built-in tools when you need common capabilities like web search or code interpretation.': '1. [**内置工具**](#built-in-tools)：由模型提供商（如 OpenAI 和 Anthropic）提供的预配置工具，可立即使用。当您需要网络搜索或代码解释等常见功能时，请使用内置工具。',
        '2. [**Custom tools**](#create-a-custom-tool): Functions you define to perform specific tasks. These are useful when you need to integrate with your own systems or create specialized functionality. When you define custom tools within the Playground, you can verify that the model correctly identifies and calls these tools with the correct arguments.': '2. [**自定义工具**](#create-a-custom-tool)：您定义的用于执行特定任务的函数。当您需要与自己的系统集成或创建专门功能时，这些工具很有用。当您在 Playground 中定义自定义工具时，您可以验证模型是否正确识别并使用正确的参数调用这些工具。',
        'LangSmith automatically saves tools you create to a workspace-wide [tool registry](#manage-tools-with-the-registry), which makes them available for reuse across all your prompts and sessions.': 'LangSmith 自动将您创建的工具保存到工作区范围的[工具注册表](#manage-tools-with-the-registry)中，使它们可以在所有提示词和会话中重用。',
        '## Built-in tools': '## 内置工具',
        'The Playground has native support for a variety of tools from OpenAI and Anthropic. If you want to use a tool that isn\'t explicitly listed in the Playground, you can still add it by manually specifying its `type` and any required arguments.': 'Playground 原生支持来自 OpenAI 和 Anthropic 的各种工具。如果您想使用未在 Playground 中明确列出的工具，您仍然可以通过手动指定其 `type` 和任何必需参数来添加它。',
        '### OpenAI tools': '### OpenAI 工具',
        '- **Web search**: [Search the web for real-time information](https://platform.openai.com/docs/guides/tools-web-search?api-mode=responses).': '- **网络搜索**：[搜索网络以获取实时信息](https://platform.openai.com/docs/guides/tools-web-search?api-mode=responses)。',
        '- **Image generation**: [Generate images based on a text prompt](https://platform.openai.com/docs/guides/tools-image-generation).': '- **图像生成**：[基于文本提示词生成图像](https://platform.openai.com/docs/guides/tools-image-generation)。',
        '- **MCP**: [Gives the model access to tools hosted on a remote MCP server](https://platform.openai.com/docs/guides/tools-remote-mcp).': '- **MCP**：使模型可以访问托管在远程 MCP 服务器上的工具](https://platform.openai.com/docs/guides/tools-remote-mcp)。',
        '- [View all OpenAI tools](https://platform.openai.com/docs/guides/tools?api-mode=responses).': '- [查看所有 OpenAI 工具](https://platform.openai.com/docs/guides/tools?api-mode=responses)。',
        '### Anthropic tools': '### Anthropic 工具',
        '- **Web search**: [Search the web for up-to-date information](https://platform.claude.com/docs/en/agents-and-tools/tool-use/web-search-tool).': '- **网络搜索**：[搜索网络以获取最新信息](https://platform.claude.com/docs/en/agents-and-tools/tool-use/web-search-tool)。',
        '- [View all Anthropic tools](https://platform.claude.com/docs/en/agents-and-tools/tool-use/overview).': '- [查看所有 Anthropic 工具](https://platform.claude.com/docs/en/agents-and-tools/tool-use/overview)。',
        '## Add and use tools': '## 添加和使用工具',
        'The Playground lets you quickly [add tools](#add-a-tool) to any prompt with a single click. You can choose from built-in tools provided by model providers like OpenAI and Anthropic, or define your own [custom tools](#create-a-custom-tool) tailored to your specific needs. Once you create a custom tool, it\'s automatically added to a workspace-wide [tool registry](#manage-tools-with-the-registry) where you can enable, disable, or edit it across different prompts without recreating it.': 'Playground 允许您只需单击一次即可快速[添加工具](#add-a-tool)到任何提示词。您可以从 OpenAI 和 Anthropic 等模型提供商提供的内置工具中进行选择，也可以根据您的特定需求定义自己的[自定义工具](#create-a-custom-tool)。创建自定义工具后，它会自动添加到工作区范围的[工具注册表](#manage-tools-with-the-registry)中，您可以在不同的提示词中启用、禁用或编辑它，而无需重新创建。',
        '### Add a tool': '### 添加工具',
        'To add a tool to your prompt, click the **+ Tool** button at the bottom of the prompt editor.': '要向提示词添加工具，请点击提示词编辑器底部的 **+ Tool** 按钮。',
        '### Use a built-in tool': '### 使用内置工具',
        '1. In the tool section, select the built-in tool you want to use. You\'ll only see the tools that are compatible with the provider and model you\'ve chosen.': '1. 在工具部分，选择您想要使用的内置工具。您只会看到与您选择的提供商和模型兼容的工具。',
        '2. When the model calls the tool, the Playground will display the response.': '2. 当模型调用工具时，Playground 将显示响应。',
        '### Create a custom tool': '### 创建自定义工具',
        'To create a custom tool, you\'ll need to provide:': '要创建自定义工具，您需要提供：',
        '- **Name**: A descriptive name for your tool.': '- **名称**：工具的描述性名称。',
        '- **Description**: Clear explanation of what the tool does.': '- **描述**：工具功能的清晰说明。',
        '- **Arguments**: The inputs your tool requires.': '- **参数**：工具所需的输入。',
        'When running a custom tool in the Playground, the model will respond with a JSON object containing the tool name and the tool call.': '在 Playground 中运行自定义工具时，模型将响应一个包含工具名称和工具调用的 JSON 对象。',
        '### Manage tools with the registry': '### 使用注册表管理工具',
        'The Playground includes a [workspace](/langsmith/administration-overview#workspaces)-scoped **tool registry** that persists both custom and built-in tools across prompts and sessions. When you create a custom tool or add a built-in tool, it\'s automatically saved to your workspace registry and becomes available for reuse in any prompt. You can enable or disable tools per prompt to control which tools are active for each specific prompt, and when editing a shared tool, you can choose to update the registry version or save as a new tool.': 'Playground 包含一个[工作区](/langsmith/administration-overview#workspaces)范围的**工具注册表**，它在提示词和会话之间保留自定义工具和内置工具。当您创建自定义工具或添加内置工具时，它会自动保存到您的工作区注册表中，并可在任何提示词中重用。您可以按提示词启用或禁用工具，以控制每个特定提示词有哪些工具处于活动状态，在编辑共享工具时，您可以选择更新注册表版本或另存为新工具。',
        'Click the **+ Tool** button in the Playground to open **Manage tools**. You can do the following:': '点击 Playground 中的 **+ Tool** 按钮打开 **Manage tools**。您可以执行以下操作：',
        '- Select and view existing tools in the **Available Tools** tab.': '- 在 **Available Tools** 选项卡中选择和查看现有工具。',
        '- Toggle individual tools on/off using the **Enabled** switch.': '- 使用 **Enabled** 开关切换各个工具的开启/关闭状态。',
        '- Edit existing tools by clicking on them in the list.': '- 通过点击列表中的工具来编辑现有工具。',
        '- Delete tools using the **Delete** at the bottom of **Manage tools**.': '- 使用 **Manage tools** 底部的 **Delete** 删除工具。',
        'Tools are stored with their complete configuration including name, description, parameters, and metadata. The registry supports both custom function tools and built-in tool configurations.': '工具以其完整配置存储，包括名称、描述、参数和元数据。注册表支持自定义函数工具和内置工具配置。',
        '## Tool choice settings': '## 工具选择设置',
        'Some models provide control over which tools are called. To configure this:': '某些模型提供对调用哪些工具的控制。要配置此功能：',
        '1. Select **+ Tool** under the prompt editor.': '1. 在提示词编辑器下方选择 **+ Tool**。',
        '2. Navigate to the **Tool Choice Setting** tab.': '2. 导航到 **Tool Choice Setting** 选项卡。',
        '3. Select your tool choice.': '3. 选择您的工具选择。',
        'To understand the available tool choice options, check the documentation for your specific provider. For example, [OpenAI\'s documentation on tool choice](https://platform.openai.com/docs/guides/function-calling/function-calling-behavior?api-mode=responses#tool-choice).': '要了解可用的工具选择选项，请查看特定提供商的文档。例如，[OpenAI 关于工具选择的文档](https://platform.openai.com/docs/guides/function-calling/function-calling-behavior?api-mode=responses#tool-choice)。',
    },
    'use-webhooks': {
        'Use webhooks': '使用 Webhook',
        'Webhooks enable event-driven communication from your LangSmith application to external services. For example, you may want to issue an update to a separate service once an API call to LangSmith has finished running.': 'Webhook 支持从您的 LangSmith 应用程序到外部服务的事件驱动通信。例如，您可能希望在向 LangSmith 的 API 调用完成运行后向单独的服务发出更新。',
        'Many LangSmith endpoints accept a `webhook` parameter. If this parameter is specified by an endpoint that can accept POST requests, LangSmith will send a request at the completion of a run.': '许多 LangSmith 端点接受 `webhook` 参数。如果某个端点可以接受 POST 请求并且该参数被指定，LangSmith 将在运行完成时发送请求。',
        'When working with LangSmith, you may want to use webhooks to receive updates after an API call completes. Webhooks are useful for triggering actions in your service once a run has finished processing. To implement this, you need to expose an endpoint that can accept `POST` requests and pass this endpoint as a `webhook` parameter in your API request.': '在使用 LangSmith 时，您可能希望使用 webhook 在 API 调用完成后接收更新。一旦运行完成处理，Webhook 对于触发服务中的操作很有用。要实现此功能，您需要公开一个可以接受 `POST` 请求的端点，并在 API 请求中将此端点作为 `webhook` 参数传递。',
        'Currently, the SDK does not provide built-in support for defining webhook endpoints, but you can specify them manually using API requests.': '目前，SDK 不提供用于定义 webhook 端点的内置支持，但您可以使用 API 请求手动指定它们。',
        '## Supported endpoints': '## 支持的端点',
        'The following API endpoints accept a `webhook` parameter:': '以下 API 端点接受 `webhook` 参数：',
        '| Operation            | HTTP Method | Endpoint                          |': '| 操作            | HTTP 方法 | 端点                          |',
        '|----------------------|-------------|-----------------------------------|': '|----------------------|-------------|-----------------------------------|',
        '| Create Run           | `POST`      | `/thread/{thread_id}/runs`        |': '| 创建运行           | `POST`      | `/thread/{thread_id}/runs`        |',
        '| Create Thread Cron   | `POST`      | `/thread/{thread_id}/runs/crons`  |': '| 创建线程 Cron   | `POST`      | `/thread/{thread_id}/runs/crons`  |',
        '| Stream Run           | `POST`      | `/thread/{thread_id}/runs/stream` |': '| 流式运行           | `POST`      | `/thread/{thread_id}/runs/stream` |',
        '| Wait Run             | `POST`      | `/thread/{thread_id}/runs/wait`   |': '| 等待运行             | `POST`      | `/thread/{thread_id}/runs/wait`   |',
        '| Create Cron          | `POST`      | `/runs/crons`                     |': '| 创建 Cron          | `POST`      | `/runs/crons`                     |',
        '| Stream Run Stateless | `POST`      | `/runs/stream`                    |': '| 流式无状态运行 | `POST`      | `/runs/stream`                    |',
        '| Wait Run Stateless   | `POST`      | `/runs/wait`                      |': '| 等待无状态运行   | `POST`      | `/runs/wait`                      |',
        'In this guide, we\'ll show how to trigger a webhook after streaming a run.': '在本指南中，我们将展示如何在流式运行后触发 webhook。',
        '## Set up your assistant and thread': '## 设置您的助手和线程',
        'Before making API calls, set up your assistant and thread.': '在发出 API 调用之前，设置您的助手和线程。',
        '## Use a webhook with a graph run': '## 在图运行中使用 webhook',
        'To use a webhook, specify the `webhook` parameter in your API request. When the run completes, LangSmith sends a `POST` request to the specified webhook URL.': '要使用 webhook，请在 API 请求中指定 `webhook` 参数。当运行完成时，LangSmith 向指定的 webhook URL 发送 `POST` 请求。',
        'For example, if your server listens for webhook events at `https://my-server.app/my-webhook-endpoint`, include this in your request:': '例如，如果您的服务器监听 `https://my-server.app/my-webhook-endpoint` 处的 webhook 事件，请将此包含在您的请求中：',
        '## Webhook payload': '## Webhook 负载',
        'LangSmith sends webhook notifications in the format of a [Run](/langsmith/runs). The request payload includes run input, configuration, and other metadata in the `kwargs` field. In addition to the standard run fields, the webhook payload also includes `values`, `webhook_sent_at`, and `error` fields.': 'LangSmith 以 [Run](/langsmith/runs) 的格式发送 webhook 通知。请求负载在 `kwargs` 字段中包含运行输入、配置和其他元数据。除了标准运行字段外，webhook 负载还包括 `values`、`webhook_sent_at` 和 `error` 字段。',
        'The full webhook payload contains the following fields:': '完整的 webhook 负载包含以下字段：',
        '| Field | Type | Description |': '| 字段 | 类型 | 描述 |',
        '|-------|------|-------------|': '|-------|------|-------------|',
        '| `run_id` | `string` (UUID) | Unique identifier for the run. |': '| `run_id` | `string` (UUID) | 运行的唯一标识符。 |',
        '| `thread_id` | `string` (UUID) | Identifier for the thread the run belongs to. |': '| `thread_id` | `string` (UUID) | 运行所属线程的标识符。 |',
        '| `assistant_id` | `string` | Identifier for the assistant that executed the run. |': '| `assistant_id` | `string` | 执行运行的助手的标识符。 |',
        '| `status` | `string` | Final status of the run (e.g., `"success"`, `"error"`). |': '| `status` | `string` | 运行的最终状态（例如 `"success"`、`"error"`）。 |',
        '| `created_at` | `string` (datetime) | Timestamp when the run was created. |': '| `created_at` | `string` (datetime) | 运行创建时的时间戳。 |',
        '| `updated_at` | `string` (datetime) | Timestamp when the run was last updated. |': '| `updated_at` | `string` (datetime) | 运行上次更新时的时间戳。 |',
        '| `run_started_at` | `string` (datetime) | Timestamp when the run began executing. |': '| `run_started_at` | `string` (datetime) | 运行开始执行时的时间戳。 |',
        '| `run_ended_at` | `string` (datetime) | Timestamp when the run finished. Omitted if the run has not ended. |': '| `run_ended_at` | `string` (datetime) | 运行结束的时间戳。如果运行尚未结束，则省略。 |',
        '| `webhook_sent_at` | `string` (datetime) | Timestamp when the webhook request was sent. |': '| `webhook_sent_at` | `string` (datetime) | 发送 webhook 请求时的时间戳。 |',
        '| `metadata` | `JSON object` | Custom metadata associated with the run. |': '| `metadata` | `JSON object` | 与运行关联的自定义元数据。 |',
        '| `kwargs` | `JSON object` | Run input, configuration, and other invocation parameters. |': '| `kwargs` | `JSON object` | 运行输入、配置和其他调用参数。 |',
        '| `values` | `JSON object` | The state values from the latest checkpoint of the thread. Only present for stateful runs. |': '| `values` | `JSON object` | 来自线程最新检查点的状态值。仅适用于有状态运行。 |',
        '| `multitask_strategy` | `string` | The multitask strategy used for the run. |': '| `multitask_strategy` | `string` | 用于运行的多任务策略。 |',
        '| `error` | `JSON object \\| null` | Present only if the run failed. Contains `error` (error type) and `message` (detail) fields. |': '| `error` | `JSON object \\| null` | 仅在运行失败时存在。包含 `error`（错误类型）和 `message`（详情）字段。 |',
        'When a run fails, the `error` field contains details about the failure:': '当运行失败时，`error` 字段包含有关失败的详细信息：',
        '## Secure webhooks': '## 保护 Webhook 安全',
        'To ensure only authorized requests hit your webhook endpoint, consider adding a security token as a query parameter:': '为确保只有授权请求访问您的 webhook 端点，请考虑添加安全令牌作为查询参数：',
        'Your server should extract and validate this token before processing requests.': '您的服务器应在处理请求之前提取并验证此令牌。',
        '## Add headers to webhook requests': '## 向 webhook 请求添加头',
        '<Note>': '<Note>',
        'Available in `langgraph-api>=0.5.36`.': '在 `langgraph-api>=0.5.36` 中可用。',
        'You can configure static headers to include with all outbound webhook requests. This is useful for authentication, routing, or passing metadata to your webhook endpoint.': '您可以配置静态头以包含在所有出站 webhook 请求中。这对于向您的 webhook 端点进行身份验证、路由或传递元数据很有用。',
        '### Use environment variables in headers': '### 在头中使用环境变量',
        'To include secrets or environment-specific values without checking them into your configuration file, use the `${{ env.VAR }}` template syntax:': '要包含秘密或特定于环境的值而不将它们放入配置文件中，请使用 `${{ env.VAR }}` 模板语法：',
        'For security, only environment variables starting with `LG_WEBHOOK_` can be referenced by default. This prevents accidentally leaking unrelated environment variables. You can customize this prefix using `env_prefix`:': '出于安全考虑，默认情况下只能引用以 `LG_WEBHOOK_` 开头的环境变量。这可以防止意外泄露不相关的环境变量。您可以使用 `env_prefix` 自定义此前缀：',
        '<Note>': '<Note>',
        'Missing required environment variables will block server startup, ensuring you don\'t deploy with incomplete configuration.': '缺少必需的环境变量将阻止服务器启动，确保您不会使用不完整的配置进行部署。',
        '## Restrict webhook destinations': '## 限制 webhook 目的地',
        '<Note>': '<Note>',
        'Available in `langgraph-api>=0.5.36`.': '在 `langgraph-api>=0.5.36` 中可用。',
        'For security or compliance purposes, you can restrict which URLs are valid webhook destinations using the `webhooks.url` configuration:': '出于安全或合规目的，您可以使用 `webhooks.url` 配置限制哪些 URL 是有效的 webhook 目的地：',
        'Available options:': '可用选项：',
        '| Option | Description |': '| 选项 | 描述 |',
        '|--------|-------------|': '|--------|-------------|',
        '| `allowed_domains` | Hostname allowlist. Supports wildcards for subdomains (e.g., `*.mycompany.com`). |': '| `allowed_domains` | 主机名白名单。支持子域通配符（例如 `*.mycompany.com`）。 |',
        '| `require_https` | Reject `http://` URLs when `true`. |': '| `require_https` | 当为 `true` 时拒绝 `http://` URL。 |',
        '| `allowed_ports` | Explicit port allowlist. Defaults to 443 (https) and 80 (http). |': '| `allowed_ports` | 明确的端口白名单。默认为 443 (https) 和 80 (http)。 |',
        '| `disable_loopback` | Disallow relative URLs (internal loopback calls) when `true`. |': '| `disable_loopback` | 当为 `true` 时禁止相对 URL（内部回环调用）。 |',
        '| `max_url_length` | Maximum permitted URL length in characters. |': '| `max_url_length` | 最大允许的 URL 长度（字符）。 |',
        '## Disable webhooks': '## 禁用 Webhook',
        'As of `langgraph-api>=0.2.78`, developers can disable webhooks in the `langgraph.json` file:': '从 `langgraph-api>=0.2.78` 开始，开发人员可以在 `langgraph.json` 文件中禁用 webhook：',
        'This feature is primarily intended for self-hosted deployments, where platform administrators or developers may prefer to disable webhooks to simplify their security posture—especially if they are not configuring firewall rules or other network controls. Disabling webhooks helps prevent untrusted payloads from being sent to internal endpoints.': '此功能主要适用于自托管部署，平台管理员或开发者可能希望禁用 webhook 以简化其安全态势——特别是如果他们没有配置防火墙规则或其他网络控制。禁用 webhook 有助于防止将不受信任的负载发送到内部端点。',
        'For full configuration details, refer to the [configuration file reference](/langsmith/cli?h=disable_webhooks#configuration-file).': '有关完整的配置详细信息，请参阅[配置文件参考](/langsmith/cli?h=disable_webhooks#configuration-file)。',
        '## Test webhooks': '## 测试 Webhook',
        'You can test your webhook using online services like:': '您可以使用以下在线服务测试您的 webhook：',
        '* **[Beeceptor](https://beeceptor.com/)** – Quickly create a test endpoint and inspect incoming webhook payloads.': '* **[Beeceptor](https://beeceptor.com/)** – 快速创建测试端点并检查传入的 webhook 负载。',
        '* **[Webhook.site](https://webhook.site/)** – View, debug, and log incoming webhook requests in real time.': '* **[Webhook.site](https://webhook.site/)** – 实时查看、调试和记录传入的 webhook 请求。',
        'These tools help you verify that LangSmith is correctly triggering and sending webhooks to your service.': '这些工具帮助您验证 LangSmith 是否正确触发并向您的服务发送 webhook。',
    },
    'user-management': {
        'User management': '用户管理',
        'This page covers user management features in LangSmith, including access control, authentication, and automated user provisioning:': '本页涵盖 LangSmith 中的用户管理功能，包括访问控制、身份验证和自动用户配置：',
        '- [Set up access control](#set-up-access-control): Configure role-based access control (RBAC) to manage user permissions within workspaces, including creating custom roles and assigning them to users.': '- [设置访问控制](#set-up-access-control)：配置基于角色的访问控制 (RBAC) 来管理工作区内的用户权限，包括创建自定义角色并将其分配给用户。',
        '- [SAML SSO (Enterprise plan)](#set-up-saml-sso-for-your-organization): Set up Single Sign-On authentication for Enterprise customers using SAML 2.0, including configuration for popular identity providers.': '- [SAML SSO (Enterprise 计划)](#set-up-saml-sso-for-your-organization)：为使用 SAML 2.0 的企业客户设置单点登录身份验证，包括流行身份提供商的配置。',
        '- [SCIM User Provisioning (Enterprise plan)](#set-up-scim-for-your-organization): Automate user provisioning and deprovisioning between your identity provider and LangSmith using SCIM.': '- [SCIM 用户配置 (Enterprise 计划)](#set-up-scim-for-your-organization)：使用 SCIM 在您的身份提供商和 LangSmith 之间自动配置和取消配置用户。',
        '## Set up access control': '## 设置访问控制',
        '<Note>': '<Note>',
        'RBAC (Role-Based Access Control) is a feature that is only available to Enterprise customers. If you are interested in this feature, [contact our sales team](https://www.langchain.com/contact-sales). Other plans default to using the [`Admin` role](/langsmith/administration-overview) for all users.': 'RBAC（基于角色的访问控制）是一项仅适用于企业客户的功能。如果您对此功能感兴趣，请[联系我们的销售团队](https://www.langchain.com/contact-sales)。其他计划默认为所有用户使用 [`Admin` 角色](/langsmith/administration-overview)。',
        '<Check>': '<Check>',
        'You may find it helpful to read the [Administration overview](/langsmith/administration-overview) page before setting up access control.': '在设置访问控制之前，您可能会发现阅读[管理概述](/langsmith/administration-overview)页面很有帮助。',
        'LangSmith relies on RBAC to manage user permissions within a [workspace](/langsmith/administration-overview#workspaces). This allows you to control who can access your LangSmith workspace and what they can do within it. Users with the `workspaces:manage` permission can manage workspace settings, and users with the `workspaces:manage-members` permission can add, remove, and update workspace members. The built-in Workspace Admin role includes both permissions.': 'LangSmith 依靠 RBAC 来管理[工作区](/langsmith/administration-overview#workspaces)内的用户权限。这允许您控制谁可以访问您的 LangSmith 工作区以及他们可以在其中做什么。具有 `workspaces:manage` 权限的用户可以管理工作区设置，具有 `workspaces:manage-members` 权限的用户可以添加、删除和更新工作区成员。内置的 Workspace Admin 角色包含这两个权限。',
        'For a complete reference of workspace roles and their permissions, refer to the [Role-based access control](/langsmith/rbac#workspace-roles) guide. For specific operations each role can perform, refer to the [Organization and workspace operations reference](/langsmith/organization-workspace-operations).': '有关工作区角色及其权限的完整参考，请参阅[基于角色的访问控制](/langsmith/rbac#workspace-roles)指南。有关每个角色可以执行的特定操作，请参阅[组织和工作区操作参考](/langsmith/organization-workspace-operations)。',
        '### Create a role': '### 创建角色',
        'By default, LangSmith comes with a set of system roles:': '默认情况下，LangSmith 附带一组系统角色：',
        '- `Admin`: has full access to all resources within the workspace.': '- `Admin`：对工作区内的所有资源拥有完全访问权。',
        '- `Viewer`: has read-only access to all resources within the workspace.': '- `Viewer`：对工作区内的所有资源拥有只读访问权。',
        '- `Editor`: has full permissions except for workspace management (adding/removing users, changing roles, configuring service keys).': '- `Editor`：拥有除工作区管理（添加/删除用户、更改角色、配置服务密钥）外的全部权限。',
        'If these do not fit your access model, `Organization Admins` can create custom roles to suit your needs.': '如果这些不符合您的访问模型，`Organization Admins` 可以创建自定义角色来满足您的需求。',
        'To create a role, navigate to the **Roles** tab in the **Members and roles** section of the [Organization settings page](https://smith.langchain.com/settings). Note that new roles that you create will be usable across all workspaces within your organization.': '要创建角色，请导航到[组织设置页面](https://smith.langchain.com/settings)的 **Members and roles** 部分中的 **Roles** 选项卡。请注意，您创建的新角色可以在组织内的所有工作区中使用。',
        'Click on the **Create Role** button to create a new role. A **Create role** form will open.': '点击 **Create Role** 按钮创建一个新角色。**Create role** 表单将打开。',
        'Assign permissions for the different LangSmith resources that you want to control access to.': '为您想要控制访问的不同 LangSmith 资源分配权限。',
        '### Assign a role to a user': '### 为用户分配角色',
        'Once you have your roles set up, you can assign them to users. To assign a role to a user, navigate to the `Workspace members` tab in the `Workspaces` section of the [Organization settings page](https://smith.langchain.com/settings)': '一旦您设置好了角色，您就可以将它们分配给用户。要为用户分配角色，请导航到[组织设置页面](https://smith.langchain.com/settings)中 `Workspaces` 部分的 `Workspace members` 选项卡',
        'Each user will have a **Role** dropdown that you can use to assign a role to them.': '每个用户都有一个 **Role** 下拉菜单，您可以使用它来分配角色。',
        'You can also invite new users with a given role.': '您还可以使用给定角色邀请新用户。',
    },
}

files_to_translate_batch5 = [
    ('src/langsmith/upload-files-with-traces.mdx', 'docs_zh/langsmith/upload-files-with-traces.mdx', 'upload-files-with-traces'),
    ('src/langsmith/use-remote-graph.mdx', 'docs_zh/langsmith/use-remote-graph.mdx', 'use-remote-graph'),
    ('src/langsmith/use-threads.mdx', 'docs_zh/langsmith/use-threads.mdx', 'use-threads'),
    ('src/langsmith/use-tools.mdx', 'docs_zh/langsmith/use-tools.mdx', 'use-tools'),
    ('src/langsmith/use-webhooks.mdx', 'docs_zh/langsmith/use-webhooks.mdx', 'use-webhooks'),
    ('src/langsmith/user-management.mdx', 'docs_zh/langsmith/user-management.mdx', 'user-management'),
]

if __name__ == '__main__':
    count = 0
    for src, dst, key in files_to_translate_batch5:
        if os.path.exists(dst):
            print(f'Skipping existing: {dst}')
            continue
        if key in translations_batch5:
            translate_file(src, dst, translations_batch5[key])
            count += 1
    print(f'Translated {count} files')